/*
 * SPDX-FileCopyrightText: 2023-2024 Sony Semiconductor Solutions Corporation
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef SDK_READER_H
#define SDK_READER_H

/* Generated by flatcc 0.6.1 FlatBuffers schema compiler for C by dvide.com */

#ifndef FLATBUFFERS_COMMON_READER_H
#include "flatbuffers_common_reader.h"
#endif
#include "flatcc/flatcc_flatbuffers.h"
#ifndef __alignas_is_defined
#include <stdalign.h>
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension "bin"
#endif


typedef const struct EVP_SDK_Config_table *EVP_SDK_Config_table_t;
typedef struct EVP_SDK_Config_table *EVP_SDK_Config_mutable_table_t;
typedef const flatbuffers_uoffset_t *EVP_SDK_Config_vec_t;
typedef flatbuffers_uoffset_t *EVP_SDK_Config_mutable_vec_t;
typedef const struct EVP_SDK_StateInput_table *EVP_SDK_StateInput_table_t;
typedef struct EVP_SDK_StateInput_table *EVP_SDK_StateInput_mutable_table_t;
typedef const flatbuffers_uoffset_t *EVP_SDK_StateInput_vec_t;
typedef flatbuffers_uoffset_t *EVP_SDK_StateInput_mutable_vec_t;
typedef const struct EVP_SDK_StateOutput_table *EVP_SDK_StateOutput_table_t;
typedef struct EVP_SDK_StateOutput_table *EVP_SDK_StateOutput_mutable_table_t;
typedef const flatbuffers_uoffset_t *EVP_SDK_StateOutput_vec_t;
typedef flatbuffers_uoffset_t *EVP_SDK_StateOutput_mutable_vec_t;
typedef const struct EVP_SDK_Exit_table *EVP_SDK_Exit_table_t;
typedef struct EVP_SDK_Exit_table *EVP_SDK_Exit_mutable_table_t;
typedef const flatbuffers_uoffset_t *EVP_SDK_Exit_vec_t;
typedef flatbuffers_uoffset_t *EVP_SDK_Exit_mutable_vec_t;
typedef const struct EVP_SDK_BlobRequestAzureBlob_table *EVP_SDK_BlobRequestAzureBlob_table_t;
typedef struct EVP_SDK_BlobRequestAzureBlob_table *EVP_SDK_BlobRequestAzureBlob_mutable_table_t;
typedef const flatbuffers_uoffset_t *EVP_SDK_BlobRequestAzureBlob_vec_t;
typedef flatbuffers_uoffset_t *EVP_SDK_BlobRequestAzureBlob_mutable_vec_t;
typedef const struct EVP_SDK_BlobRequestEvp_table *EVP_SDK_BlobRequestEvp_table_t;
typedef struct EVP_SDK_BlobRequestEvp_table *EVP_SDK_BlobRequestEvp_mutable_table_t;
typedef const flatbuffers_uoffset_t *EVP_SDK_BlobRequestEvp_vec_t;
typedef flatbuffers_uoffset_t *EVP_SDK_BlobRequestEvp_mutable_vec_t;
typedef const struct EVP_SDK_BlobRequestHttp_table *EVP_SDK_BlobRequestHttp_table_t;
typedef struct EVP_SDK_BlobRequestHttp_table *EVP_SDK_BlobRequestHttp_mutable_table_t;
typedef const flatbuffers_uoffset_t *EVP_SDK_BlobRequestHttp_vec_t;
typedef flatbuffers_uoffset_t *EVP_SDK_BlobRequestHttp_mutable_vec_t;
typedef const struct EVP_SDK_BlobRequestHttpExt_table *EVP_SDK_BlobRequestHttpExt_table_t;
typedef struct EVP_SDK_BlobRequestHttpExt_table *EVP_SDK_BlobRequestHttpExt_mutable_table_t;
typedef const flatbuffers_uoffset_t *EVP_SDK_BlobRequestHttpExt_vec_t;
typedef flatbuffers_uoffset_t *EVP_SDK_BlobRequestHttpExt_mutable_vec_t;
typedef const struct EVP_SDK_BlobInput_table *EVP_SDK_BlobInput_table_t;
typedef struct EVP_SDK_BlobInput_table *EVP_SDK_BlobInput_mutable_table_t;
typedef const flatbuffers_uoffset_t *EVP_SDK_BlobInput_vec_t;
typedef flatbuffers_uoffset_t *EVP_SDK_BlobInput_mutable_vec_t;
typedef const struct EVP_SDK_BlobResultAzureBlob_table *EVP_SDK_BlobResultAzureBlob_table_t;
typedef struct EVP_SDK_BlobResultAzureBlob_table *EVP_SDK_BlobResultAzureBlob_mutable_table_t;
typedef const flatbuffers_uoffset_t *EVP_SDK_BlobResultAzureBlob_vec_t;
typedef flatbuffers_uoffset_t *EVP_SDK_BlobResultAzureBlob_mutable_vec_t;
typedef const struct EVP_SDK_BlobResultEvp_table *EVP_SDK_BlobResultEvp_table_t;
typedef struct EVP_SDK_BlobResultEvp_table *EVP_SDK_BlobResultEvp_mutable_table_t;
typedef const flatbuffers_uoffset_t *EVP_SDK_BlobResultEvp_vec_t;
typedef flatbuffers_uoffset_t *EVP_SDK_BlobResultEvp_mutable_vec_t;
typedef const struct EVP_SDK_BlobResultHttp_table *EVP_SDK_BlobResultHttp_table_t;
typedef struct EVP_SDK_BlobResultHttp_table *EVP_SDK_BlobResultHttp_mutable_table_t;
typedef const flatbuffers_uoffset_t *EVP_SDK_BlobResultHttp_vec_t;
typedef flatbuffers_uoffset_t *EVP_SDK_BlobResultHttp_mutable_vec_t;
typedef const struct EVP_SDK_BlobResultHttpExt_table *EVP_SDK_BlobResultHttpExt_table_t;
typedef struct EVP_SDK_BlobResultHttpExt_table *EVP_SDK_BlobResultHttpExt_mutable_table_t;
typedef const flatbuffers_uoffset_t *EVP_SDK_BlobResultHttpExt_vec_t;
typedef flatbuffers_uoffset_t *EVP_SDK_BlobResultHttpExt_mutable_vec_t;
typedef const struct EVP_SDK_BlobOutput_table *EVP_SDK_BlobOutput_table_t;
typedef struct EVP_SDK_BlobOutput_table *EVP_SDK_BlobOutput_mutable_table_t;
typedef const flatbuffers_uoffset_t *EVP_SDK_BlobOutput_vec_t;
typedef flatbuffers_uoffset_t *EVP_SDK_BlobOutput_mutable_vec_t;
typedef const struct EVP_SDK_MessageSentInput_table *EVP_SDK_MessageSentInput_table_t;
typedef struct EVP_SDK_MessageSentInput_table *EVP_SDK_MessageSentInput_mutable_table_t;
typedef const flatbuffers_uoffset_t *EVP_SDK_MessageSentInput_vec_t;
typedef flatbuffers_uoffset_t *EVP_SDK_MessageSentInput_mutable_vec_t;
typedef const struct EVP_SDK_MessageSentOutput_table *EVP_SDK_MessageSentOutput_table_t;
typedef struct EVP_SDK_MessageSentOutput_table *EVP_SDK_MessageSentOutput_mutable_table_t;
typedef const flatbuffers_uoffset_t *EVP_SDK_MessageSentOutput_vec_t;
typedef flatbuffers_uoffset_t *EVP_SDK_MessageSentOutput_mutable_vec_t;
typedef const struct EVP_SDK_MessageReceived_table *EVP_SDK_MessageReceived_table_t;
typedef struct EVP_SDK_MessageReceived_table *EVP_SDK_MessageReceived_mutable_table_t;
typedef const flatbuffers_uoffset_t *EVP_SDK_MessageReceived_vec_t;
typedef flatbuffers_uoffset_t *EVP_SDK_MessageReceived_mutable_vec_t;
typedef const struct EVP_SDK_TelemetryEntry_table *EVP_SDK_TelemetryEntry_table_t;
typedef struct EVP_SDK_TelemetryEntry_table *EVP_SDK_TelemetryEntry_mutable_table_t;
typedef const flatbuffers_uoffset_t *EVP_SDK_TelemetryEntry_vec_t;
typedef flatbuffers_uoffset_t *EVP_SDK_TelemetryEntry_mutable_vec_t;
typedef const struct EVP_SDK_TelemetryInput_table *EVP_SDK_TelemetryInput_table_t;
typedef struct EVP_SDK_TelemetryInput_table *EVP_SDK_TelemetryInput_mutable_table_t;
typedef const flatbuffers_uoffset_t *EVP_SDK_TelemetryInput_vec_t;
typedef flatbuffers_uoffset_t *EVP_SDK_TelemetryInput_mutable_vec_t;
typedef const struct EVP_SDK_TelemetryOutput_table *EVP_SDK_TelemetryOutput_table_t;
typedef struct EVP_SDK_TelemetryOutput_table *EVP_SDK_TelemetryOutput_mutable_table_t;
typedef const flatbuffers_uoffset_t *EVP_SDK_TelemetryOutput_vec_t;
typedef flatbuffers_uoffset_t *EVP_SDK_TelemetryOutput_mutable_vec_t;
typedef const struct EVP_SDK_RpcRequest_table *EVP_SDK_RpcRequest_table_t;
typedef struct EVP_SDK_RpcRequest_table *EVP_SDK_RpcRequest_mutable_table_t;
typedef const flatbuffers_uoffset_t *EVP_SDK_RpcRequest_vec_t;
typedef flatbuffers_uoffset_t *EVP_SDK_RpcRequest_mutable_vec_t;
typedef const struct EVP_SDK_RpcResponseInput_table *EVP_SDK_RpcResponseInput_table_t;
typedef struct EVP_SDK_RpcResponseInput_table *EVP_SDK_RpcResponseInput_mutable_table_t;
typedef const flatbuffers_uoffset_t *EVP_SDK_RpcResponseInput_vec_t;
typedef flatbuffers_uoffset_t *EVP_SDK_RpcResponseInput_mutable_vec_t;
typedef const struct EVP_SDK_RpcResponseOutput_table *EVP_SDK_RpcResponseOutput_table_t;
typedef struct EVP_SDK_RpcResponseOutput_table *EVP_SDK_RpcResponseOutput_mutable_table_t;
typedef const flatbuffers_uoffset_t *EVP_SDK_RpcResponseOutput_vec_t;
typedef flatbuffers_uoffset_t *EVP_SDK_RpcResponseOutput_mutable_vec_t;
typedef const struct EVP_SDK_Event_table *EVP_SDK_Event_table_t;
typedef struct EVP_SDK_Event_table *EVP_SDK_Event_mutable_table_t;
typedef const flatbuffers_uoffset_t *EVP_SDK_Event_vec_t;
typedef flatbuffers_uoffset_t *EVP_SDK_Event_mutable_vec_t;
typedef const struct EVP_SDK_GetEvent_table *EVP_SDK_GetEvent_table_t;
typedef struct EVP_SDK_GetEvent_table *EVP_SDK_GetEvent_mutable_table_t;
typedef const flatbuffers_uoffset_t *EVP_SDK_GetEvent_vec_t;
typedef flatbuffers_uoffset_t *EVP_SDK_GetEvent_mutable_vec_t;
typedef const struct EVP_SDK_RequestResendConfig_table *EVP_SDK_RequestResendConfig_table_t;
typedef struct EVP_SDK_RequestResendConfig_table *EVP_SDK_RequestResendConfig_mutable_table_t;
typedef const flatbuffers_uoffset_t *EVP_SDK_RequestResendConfig_vec_t;
typedef flatbuffers_uoffset_t *EVP_SDK_RequestResendConfig_mutable_vec_t;
typedef const struct EVP_SDK_Request_table *EVP_SDK_Request_table_t;
typedef struct EVP_SDK_Request_table *EVP_SDK_Request_mutable_table_t;
typedef const flatbuffers_uoffset_t *EVP_SDK_Request_vec_t;
typedef flatbuffers_uoffset_t *EVP_SDK_Request_mutable_vec_t;
typedef const struct EVP_SDK_Simple_table *EVP_SDK_Simple_table_t;
typedef struct EVP_SDK_Simple_table *EVP_SDK_Simple_mutable_table_t;
typedef const flatbuffers_uoffset_t *EVP_SDK_Simple_vec_t;
typedef flatbuffers_uoffset_t *EVP_SDK_Simple_mutable_vec_t;
typedef const struct EVP_SDK_Response_table *EVP_SDK_Response_table_t;
typedef struct EVP_SDK_Response_table *EVP_SDK_Response_mutable_table_t;
typedef const flatbuffers_uoffset_t *EVP_SDK_Response_vec_t;
typedef flatbuffers_uoffset_t *EVP_SDK_Response_mutable_vec_t;
typedef const struct EVP_SDK_StreamParamsRequest_table *EVP_SDK_StreamParamsRequest_table_t;
typedef struct EVP_SDK_StreamParamsRequest_table *EVP_SDK_StreamParamsRequest_mutable_table_t;
typedef const flatbuffers_uoffset_t *EVP_SDK_StreamParamsRequest_vec_t;
typedef flatbuffers_uoffset_t *EVP_SDK_StreamParamsRequest_mutable_vec_t;
typedef const struct EVP_SDK_StreamNng_table *EVP_SDK_StreamNng_table_t;
typedef struct EVP_SDK_StreamNng_table *EVP_SDK_StreamNng_mutable_table_t;
typedef const flatbuffers_uoffset_t *EVP_SDK_StreamNng_vec_t;
typedef flatbuffers_uoffset_t *EVP_SDK_StreamNng_mutable_vec_t;
typedef const struct EVP_SDK_StreamParamsResponse_table *EVP_SDK_StreamParamsResponse_table_t;
typedef struct EVP_SDK_StreamParamsResponse_table *EVP_SDK_StreamParamsResponse_mutable_table_t;
typedef const flatbuffers_uoffset_t *EVP_SDK_StreamParamsResponse_vec_t;
typedef flatbuffers_uoffset_t *EVP_SDK_StreamParamsResponse_mutable_vec_t;
#ifndef EVP_SDK_Config_file_identifier
#define EVP_SDK_Config_file_identifier 0
#endif
/* deprecated, use EVP_SDK_Config_file_identifier */
#ifndef EVP_SDK_Config_identifier
#define EVP_SDK_Config_identifier 0
#endif
#define EVP_SDK_Config_type_hash ((flatbuffers_thash_t)0x7364d710)
#define EVP_SDK_Config_type_identifier "\x10\xd7\x64\x73"
#ifndef EVP_SDK_Config_file_extension
#define EVP_SDK_Config_file_extension "bin"
#endif
#ifndef EVP_SDK_StateInput_file_identifier
#define EVP_SDK_StateInput_file_identifier 0
#endif
/* deprecated, use EVP_SDK_StateInput_file_identifier */
#ifndef EVP_SDK_StateInput_identifier
#define EVP_SDK_StateInput_identifier 0
#endif
#define EVP_SDK_StateInput_type_hash ((flatbuffers_thash_t)0xb2d1e079)
#define EVP_SDK_StateInput_type_identifier "\x79\xe0\xd1\xb2"
#ifndef EVP_SDK_StateInput_file_extension
#define EVP_SDK_StateInput_file_extension "bin"
#endif
#ifndef EVP_SDK_StateOutput_file_identifier
#define EVP_SDK_StateOutput_file_identifier 0
#endif
/* deprecated, use EVP_SDK_StateOutput_file_identifier */
#ifndef EVP_SDK_StateOutput_identifier
#define EVP_SDK_StateOutput_identifier 0
#endif
#define EVP_SDK_StateOutput_type_hash ((flatbuffers_thash_t)0xddff3836)
#define EVP_SDK_StateOutput_type_identifier "\x36\x38\xff\xdd"
#ifndef EVP_SDK_StateOutput_file_extension
#define EVP_SDK_StateOutput_file_extension "bin"
#endif
#ifndef EVP_SDK_Exit_file_identifier
#define EVP_SDK_Exit_file_identifier 0
#endif
/* deprecated, use EVP_SDK_Exit_file_identifier */
#ifndef EVP_SDK_Exit_identifier
#define EVP_SDK_Exit_identifier 0
#endif
#define EVP_SDK_Exit_type_hash ((flatbuffers_thash_t)0xfaa2e95e)
#define EVP_SDK_Exit_type_identifier "\x5e\xe9\xa2\xfa"
#ifndef EVP_SDK_Exit_file_extension
#define EVP_SDK_Exit_file_extension "bin"
#endif
#ifndef EVP_SDK_BlobRequestAzureBlob_file_identifier
#define EVP_SDK_BlobRequestAzureBlob_file_identifier 0
#endif
/* deprecated, use EVP_SDK_BlobRequestAzureBlob_file_identifier */
#ifndef EVP_SDK_BlobRequestAzureBlob_identifier
#define EVP_SDK_BlobRequestAzureBlob_identifier 0
#endif
#define EVP_SDK_BlobRequestAzureBlob_type_hash ((flatbuffers_thash_t)0x9b72ef62)
#define EVP_SDK_BlobRequestAzureBlob_type_identifier "\x62\xef\x72\x9b"
#ifndef EVP_SDK_BlobRequestAzureBlob_file_extension
#define EVP_SDK_BlobRequestAzureBlob_file_extension "bin"
#endif
#ifndef EVP_SDK_BlobRequestEvp_file_identifier
#define EVP_SDK_BlobRequestEvp_file_identifier 0
#endif
/* deprecated, use EVP_SDK_BlobRequestEvp_file_identifier */
#ifndef EVP_SDK_BlobRequestEvp_identifier
#define EVP_SDK_BlobRequestEvp_identifier 0
#endif
#define EVP_SDK_BlobRequestEvp_type_hash ((flatbuffers_thash_t)0xfb84e483)
#define EVP_SDK_BlobRequestEvp_type_identifier "\x83\xe4\x84\xfb"
#ifndef EVP_SDK_BlobRequestEvp_file_extension
#define EVP_SDK_BlobRequestEvp_file_extension "bin"
#endif
#ifndef EVP_SDK_BlobRequestHttp_file_identifier
#define EVP_SDK_BlobRequestHttp_file_identifier 0
#endif
/* deprecated, use EVP_SDK_BlobRequestHttp_file_identifier */
#ifndef EVP_SDK_BlobRequestHttp_identifier
#define EVP_SDK_BlobRequestHttp_identifier 0
#endif
#define EVP_SDK_BlobRequestHttp_type_hash ((flatbuffers_thash_t)0xffa84bb2)
#define EVP_SDK_BlobRequestHttp_type_identifier "\xb2\x4b\xa8\xff"
#ifndef EVP_SDK_BlobRequestHttp_file_extension
#define EVP_SDK_BlobRequestHttp_file_extension "bin"
#endif
#ifndef EVP_SDK_BlobRequestHttpExt_file_identifier
#define EVP_SDK_BlobRequestHttpExt_file_identifier 0
#endif
/* deprecated, use EVP_SDK_BlobRequestHttpExt_file_identifier */
#ifndef EVP_SDK_BlobRequestHttpExt_identifier
#define EVP_SDK_BlobRequestHttpExt_identifier 0
#endif
#define EVP_SDK_BlobRequestHttpExt_type_hash ((flatbuffers_thash_t)0x80f28419)
#define EVP_SDK_BlobRequestHttpExt_type_identifier "\x19\x84\xf2\x80"
#ifndef EVP_SDK_BlobRequestHttpExt_file_extension
#define EVP_SDK_BlobRequestHttpExt_file_extension "bin"
#endif
#ifndef EVP_SDK_BlobInput_file_identifier
#define EVP_SDK_BlobInput_file_identifier 0
#endif
/* deprecated, use EVP_SDK_BlobInput_file_identifier */
#ifndef EVP_SDK_BlobInput_identifier
#define EVP_SDK_BlobInput_identifier 0
#endif
#define EVP_SDK_BlobInput_type_hash ((flatbuffers_thash_t)0x670c46e3)
#define EVP_SDK_BlobInput_type_identifier "\xe3\x46\x0c\x67"
#ifndef EVP_SDK_BlobInput_file_extension
#define EVP_SDK_BlobInput_file_extension "bin"
#endif
#ifndef EVP_SDK_BlobResultAzureBlob_file_identifier
#define EVP_SDK_BlobResultAzureBlob_file_identifier 0
#endif
/* deprecated, use EVP_SDK_BlobResultAzureBlob_file_identifier */
#ifndef EVP_SDK_BlobResultAzureBlob_identifier
#define EVP_SDK_BlobResultAzureBlob_identifier 0
#endif
#define EVP_SDK_BlobResultAzureBlob_type_hash ((flatbuffers_thash_t)0xcd9e1ac4)
#define EVP_SDK_BlobResultAzureBlob_type_identifier "\xc4\x1a\x9e\xcd"
#ifndef EVP_SDK_BlobResultAzureBlob_file_extension
#define EVP_SDK_BlobResultAzureBlob_file_extension "bin"
#endif
#ifndef EVP_SDK_BlobResultEvp_file_identifier
#define EVP_SDK_BlobResultEvp_file_identifier 0
#endif
/* deprecated, use EVP_SDK_BlobResultEvp_file_identifier */
#ifndef EVP_SDK_BlobResultEvp_identifier
#define EVP_SDK_BlobResultEvp_identifier 0
#endif
#define EVP_SDK_BlobResultEvp_type_hash ((flatbuffers_thash_t)0x7f1996b5)
#define EVP_SDK_BlobResultEvp_type_identifier "\xb5\x96\x19\x7f"
#ifndef EVP_SDK_BlobResultEvp_file_extension
#define EVP_SDK_BlobResultEvp_file_extension "bin"
#endif
#ifndef EVP_SDK_BlobResultHttp_file_identifier
#define EVP_SDK_BlobResultHttp_file_identifier 0
#endif
/* deprecated, use EVP_SDK_BlobResultHttp_file_identifier */
#ifndef EVP_SDK_BlobResultHttp_identifier
#define EVP_SDK_BlobResultHttp_identifier 0
#endif
#define EVP_SDK_BlobResultHttp_type_hash ((flatbuffers_thash_t)0x6f9ccfac)
#define EVP_SDK_BlobResultHttp_type_identifier "\xac\xcf\x9c\x6f"
#ifndef EVP_SDK_BlobResultHttp_file_extension
#define EVP_SDK_BlobResultHttp_file_extension "bin"
#endif
#ifndef EVP_SDK_BlobResultHttpExt_file_identifier
#define EVP_SDK_BlobResultHttpExt_file_identifier 0
#endif
/* deprecated, use EVP_SDK_BlobResultHttpExt_file_identifier */
#ifndef EVP_SDK_BlobResultHttpExt_identifier
#define EVP_SDK_BlobResultHttpExt_identifier 0
#endif
#define EVP_SDK_BlobResultHttpExt_type_hash ((flatbuffers_thash_t)0xf56b4787)
#define EVP_SDK_BlobResultHttpExt_type_identifier "\x87\x47\x6b\xf5"
#ifndef EVP_SDK_BlobResultHttpExt_file_extension
#define EVP_SDK_BlobResultHttpExt_file_extension "bin"
#endif
#ifndef EVP_SDK_BlobOutput_file_identifier
#define EVP_SDK_BlobOutput_file_identifier 0
#endif
/* deprecated, use EVP_SDK_BlobOutput_file_identifier */
#ifndef EVP_SDK_BlobOutput_identifier
#define EVP_SDK_BlobOutput_identifier 0
#endif
#define EVP_SDK_BlobOutput_type_hash ((flatbuffers_thash_t)0x65b9ce6c)
#define EVP_SDK_BlobOutput_type_identifier "\x6c\xce\xb9\x65"
#ifndef EVP_SDK_BlobOutput_file_extension
#define EVP_SDK_BlobOutput_file_extension "bin"
#endif
#ifndef EVP_SDK_MessageSentInput_file_identifier
#define EVP_SDK_MessageSentInput_file_identifier 0
#endif
/* deprecated, use EVP_SDK_MessageSentInput_file_identifier */
#ifndef EVP_SDK_MessageSentInput_identifier
#define EVP_SDK_MessageSentInput_identifier 0
#endif
#define EVP_SDK_MessageSentInput_type_hash ((flatbuffers_thash_t)0x91727efd)
#define EVP_SDK_MessageSentInput_type_identifier "\xfd\x7e\x72\x91"
#ifndef EVP_SDK_MessageSentInput_file_extension
#define EVP_SDK_MessageSentInput_file_extension "bin"
#endif
#ifndef EVP_SDK_MessageSentOutput_file_identifier
#define EVP_SDK_MessageSentOutput_file_identifier 0
#endif
/* deprecated, use EVP_SDK_MessageSentOutput_file_identifier */
#ifndef EVP_SDK_MessageSentOutput_identifier
#define EVP_SDK_MessageSentOutput_identifier 0
#endif
#define EVP_SDK_MessageSentOutput_type_hash ((flatbuffers_thash_t)0xff303a2)
#define EVP_SDK_MessageSentOutput_type_identifier "\xa2\x03\xf3\x0f"
#ifndef EVP_SDK_MessageSentOutput_file_extension
#define EVP_SDK_MessageSentOutput_file_extension "bin"
#endif
#ifndef EVP_SDK_MessageReceived_file_identifier
#define EVP_SDK_MessageReceived_file_identifier 0
#endif
/* deprecated, use EVP_SDK_MessageReceived_file_identifier */
#ifndef EVP_SDK_MessageReceived_identifier
#define EVP_SDK_MessageReceived_identifier 0
#endif
#define EVP_SDK_MessageReceived_type_hash ((flatbuffers_thash_t)0xc41d61c2)
#define EVP_SDK_MessageReceived_type_identifier "\xc2\x61\x1d\xc4"
#ifndef EVP_SDK_MessageReceived_file_extension
#define EVP_SDK_MessageReceived_file_extension "bin"
#endif
#ifndef EVP_SDK_TelemetryEntry_file_identifier
#define EVP_SDK_TelemetryEntry_file_identifier 0
#endif
/* deprecated, use EVP_SDK_TelemetryEntry_file_identifier */
#ifndef EVP_SDK_TelemetryEntry_identifier
#define EVP_SDK_TelemetryEntry_identifier 0
#endif
#define EVP_SDK_TelemetryEntry_type_hash ((flatbuffers_thash_t)0x1df9492b)
#define EVP_SDK_TelemetryEntry_type_identifier "\x2b\x49\xf9\x1d"
#ifndef EVP_SDK_TelemetryEntry_file_extension
#define EVP_SDK_TelemetryEntry_file_extension "bin"
#endif
#ifndef EVP_SDK_TelemetryInput_file_identifier
#define EVP_SDK_TelemetryInput_file_identifier 0
#endif
/* deprecated, use EVP_SDK_TelemetryInput_file_identifier */
#ifndef EVP_SDK_TelemetryInput_identifier
#define EVP_SDK_TelemetryInput_identifier 0
#endif
#define EVP_SDK_TelemetryInput_type_hash ((flatbuffers_thash_t)0x5f6e5ad3)
#define EVP_SDK_TelemetryInput_type_identifier "\xd3\x5a\x6e\x5f"
#ifndef EVP_SDK_TelemetryInput_file_extension
#define EVP_SDK_TelemetryInput_file_extension "bin"
#endif
#ifndef EVP_SDK_TelemetryOutput_file_identifier
#define EVP_SDK_TelemetryOutput_file_identifier 0
#endif
/* deprecated, use EVP_SDK_TelemetryOutput_file_identifier */
#ifndef EVP_SDK_TelemetryOutput_identifier
#define EVP_SDK_TelemetryOutput_identifier 0
#endif
#define EVP_SDK_TelemetryOutput_type_hash ((flatbuffers_thash_t)0x4d6b10fc)
#define EVP_SDK_TelemetryOutput_type_identifier "\xfc\x10\x6b\x4d"
#ifndef EVP_SDK_TelemetryOutput_file_extension
#define EVP_SDK_TelemetryOutput_file_extension "bin"
#endif
#ifndef EVP_SDK_RpcRequest_file_identifier
#define EVP_SDK_RpcRequest_file_identifier 0
#endif
/* deprecated, use EVP_SDK_RpcRequest_file_identifier */
#ifndef EVP_SDK_RpcRequest_identifier
#define EVP_SDK_RpcRequest_identifier 0
#endif
#define EVP_SDK_RpcRequest_type_hash ((flatbuffers_thash_t)0xdaf8cf82)
#define EVP_SDK_RpcRequest_type_identifier "\x82\xcf\xf8\xda"
#ifndef EVP_SDK_RpcRequest_file_extension
#define EVP_SDK_RpcRequest_file_extension "bin"
#endif
#ifndef EVP_SDK_RpcResponseInput_file_identifier
#define EVP_SDK_RpcResponseInput_file_identifier 0
#endif
/* deprecated, use EVP_SDK_RpcResponseInput_file_identifier */
#ifndef EVP_SDK_RpcResponseInput_identifier
#define EVP_SDK_RpcResponseInput_identifier 0
#endif
#define EVP_SDK_RpcResponseInput_type_hash ((flatbuffers_thash_t)0x4dc1a472)
#define EVP_SDK_RpcResponseInput_type_identifier "\x72\xa4\xc1\x4d"
#ifndef EVP_SDK_RpcResponseInput_file_extension
#define EVP_SDK_RpcResponseInput_file_extension "bin"
#endif
#ifndef EVP_SDK_RpcResponseOutput_file_identifier
#define EVP_SDK_RpcResponseOutput_file_identifier 0
#endif
/* deprecated, use EVP_SDK_RpcResponseOutput_file_identifier */
#ifndef EVP_SDK_RpcResponseOutput_identifier
#define EVP_SDK_RpcResponseOutput_identifier 0
#endif
#define EVP_SDK_RpcResponseOutput_type_hash ((flatbuffers_thash_t)0x15d054e7)
#define EVP_SDK_RpcResponseOutput_type_identifier "\xe7\x54\xd0\x15"
#ifndef EVP_SDK_RpcResponseOutput_file_extension
#define EVP_SDK_RpcResponseOutput_file_extension "bin"
#endif
#ifndef EVP_SDK_Event_file_identifier
#define EVP_SDK_Event_file_identifier 0
#endif
/* deprecated, use EVP_SDK_Event_file_identifier */
#ifndef EVP_SDK_Event_identifier
#define EVP_SDK_Event_identifier 0
#endif
#define EVP_SDK_Event_type_hash ((flatbuffers_thash_t)0xba6188e2)
#define EVP_SDK_Event_type_identifier "\xe2\x88\x61\xba"
#ifndef EVP_SDK_Event_file_extension
#define EVP_SDK_Event_file_extension "bin"
#endif
#ifndef EVP_SDK_GetEvent_file_identifier
#define EVP_SDK_GetEvent_file_identifier 0
#endif
/* deprecated, use EVP_SDK_GetEvent_file_identifier */
#ifndef EVP_SDK_GetEvent_identifier
#define EVP_SDK_GetEvent_identifier 0
#endif
#define EVP_SDK_GetEvent_type_hash ((flatbuffers_thash_t)0xaa52d20e)
#define EVP_SDK_GetEvent_type_identifier "\x0e\xd2\x52\xaa"
#ifndef EVP_SDK_GetEvent_file_extension
#define EVP_SDK_GetEvent_file_extension "bin"
#endif
#ifndef EVP_SDK_RequestResendConfig_file_identifier
#define EVP_SDK_RequestResendConfig_file_identifier 0
#endif
/* deprecated, use EVP_SDK_RequestResendConfig_file_identifier */
#ifndef EVP_SDK_RequestResendConfig_identifier
#define EVP_SDK_RequestResendConfig_identifier 0
#endif
#define EVP_SDK_RequestResendConfig_type_hash ((flatbuffers_thash_t)0x6d80b9e6)
#define EVP_SDK_RequestResendConfig_type_identifier "\xe6\xb9\x80\x6d"
#ifndef EVP_SDK_RequestResendConfig_file_extension
#define EVP_SDK_RequestResendConfig_file_extension "bin"
#endif
#ifndef EVP_SDK_Request_file_identifier
#define EVP_SDK_Request_file_identifier 0
#endif
/* deprecated, use EVP_SDK_Request_file_identifier */
#ifndef EVP_SDK_Request_identifier
#define EVP_SDK_Request_identifier 0
#endif
#define EVP_SDK_Request_type_hash ((flatbuffers_thash_t)0x2960395b)
#define EVP_SDK_Request_type_identifier "\x5b\x39\x60\x29"
#ifndef EVP_SDK_Request_file_extension
#define EVP_SDK_Request_file_extension "bin"
#endif
#ifndef EVP_SDK_Simple_file_identifier
#define EVP_SDK_Simple_file_identifier 0
#endif
/* deprecated, use EVP_SDK_Simple_file_identifier */
#ifndef EVP_SDK_Simple_identifier
#define EVP_SDK_Simple_identifier 0
#endif
#define EVP_SDK_Simple_type_hash ((flatbuffers_thash_t)0xd737272c)
#define EVP_SDK_Simple_type_identifier "\x2c\x27\x37\xd7"
#ifndef EVP_SDK_Simple_file_extension
#define EVP_SDK_Simple_file_extension "bin"
#endif
#ifndef EVP_SDK_Response_file_identifier
#define EVP_SDK_Response_file_identifier 0
#endif
/* deprecated, use EVP_SDK_Response_file_identifier */
#ifndef EVP_SDK_Response_identifier
#define EVP_SDK_Response_identifier 0
#endif
#define EVP_SDK_Response_type_hash ((flatbuffers_thash_t)0x8c2c4f59)
#define EVP_SDK_Response_type_identifier "\x59\x4f\x2c\x8c"
#ifndef EVP_SDK_Response_file_extension
#define EVP_SDK_Response_file_extension "bin"
#endif
#ifndef EVP_SDK_StreamParamsRequest_file_identifier
#define EVP_SDK_StreamParamsRequest_file_identifier 0
#endif
/* deprecated, use EVP_SDK_StreamParamsRequest_file_identifier */
#ifndef EVP_SDK_StreamParamsRequest_identifier
#define EVP_SDK_StreamParamsRequest_identifier 0
#endif
#define EVP_SDK_StreamParamsRequest_type_hash ((flatbuffers_thash_t)0x3da8965)
#define EVP_SDK_StreamParamsRequest_type_identifier "\x65\x89\xda\x03"
#ifndef EVP_SDK_StreamParamsRequest_file_extension
#define EVP_SDK_StreamParamsRequest_file_extension "bin"
#endif
#ifndef EVP_SDK_StreamNng_file_identifier
#define EVP_SDK_StreamNng_file_identifier 0
#endif
/* deprecated, use EVP_SDK_StreamNng_file_identifier */
#ifndef EVP_SDK_StreamNng_identifier
#define EVP_SDK_StreamNng_identifier 0
#endif
#define EVP_SDK_StreamNng_type_hash ((flatbuffers_thash_t)0xa148609f)
#define EVP_SDK_StreamNng_type_identifier "\x9f\x60\x48\xa1"
#ifndef EVP_SDK_StreamNng_file_extension
#define EVP_SDK_StreamNng_file_extension "bin"
#endif
#ifndef EVP_SDK_StreamParamsResponse_file_identifier
#define EVP_SDK_StreamParamsResponse_file_identifier 0
#endif
/* deprecated, use EVP_SDK_StreamParamsResponse_file_identifier */
#ifndef EVP_SDK_StreamParamsResponse_identifier
#define EVP_SDK_StreamParamsResponse_identifier 0
#endif
#define EVP_SDK_StreamParamsResponse_type_hash ((flatbuffers_thash_t)0x6f321fbb)
#define EVP_SDK_StreamParamsResponse_type_identifier "\xbb\x1f\x32\x6f"
#ifndef EVP_SDK_StreamParamsResponse_file_extension
#define EVP_SDK_StreamParamsResponse_file_extension "bin"
#endif

typedef int8_t EVP_SDK_StreamNngMode_enum_t;
__flatbuffers_define_integer_type(EVP_SDK_StreamNngMode, EVP_SDK_StreamNngMode_enum_t, 8)
#define EVP_SDK_StreamNngMode_Dial ((EVP_SDK_StreamNngMode_enum_t)INT8_C(0))
#define EVP_SDK_StreamNngMode_Listen ((EVP_SDK_StreamNngMode_enum_t)INT8_C(1))

static inline const char *EVP_SDK_StreamNngMode_name(EVP_SDK_StreamNngMode_enum_t value)
{
    switch (value) {
    case EVP_SDK_StreamNngMode_Dial: return "Dial";
    case EVP_SDK_StreamNngMode_Listen: return "Listen";
    default: return "";
    }
}

static inline int EVP_SDK_StreamNngMode_is_known_value(EVP_SDK_StreamNngMode_enum_t value)
{
    switch (value) {
    case EVP_SDK_StreamNngMode_Dial: return 1;
    case EVP_SDK_StreamNngMode_Listen: return 1;
    default: return 0;
    }
}

typedef int8_t EVP_SDK_StreamNngProtocol_enum_t;
__flatbuffers_define_integer_type(EVP_SDK_StreamNngProtocol, EVP_SDK_StreamNngProtocol_enum_t, 8)
#define EVP_SDK_StreamNngProtocol_Push ((EVP_SDK_StreamNngProtocol_enum_t)INT8_C(0))
#define EVP_SDK_StreamNngProtocol_Pull ((EVP_SDK_StreamNngProtocol_enum_t)INT8_C(1))

static inline const char *EVP_SDK_StreamNngProtocol_name(EVP_SDK_StreamNngProtocol_enum_t value)
{
    switch (value) {
    case EVP_SDK_StreamNngProtocol_Push: return "Push";
    case EVP_SDK_StreamNngProtocol_Pull: return "Pull";
    default: return "";
    }
}

static inline int EVP_SDK_StreamNngProtocol_is_known_value(EVP_SDK_StreamNngProtocol_enum_t value)
{
    switch (value) {
    case EVP_SDK_StreamNngProtocol_Push: return 1;
    case EVP_SDK_StreamNngProtocol_Pull: return 1;
    default: return 0;
    }
}

typedef int8_t EVP_SDK_StreamType_enum_t;
__flatbuffers_define_integer_type(EVP_SDK_StreamType, EVP_SDK_StreamType_enum_t, 8)
#define EVP_SDK_StreamType_Null ((EVP_SDK_StreamType_enum_t)INT8_C(0))
#define EVP_SDK_StreamType_Nng ((EVP_SDK_StreamType_enum_t)INT8_C(1))

static inline const char *EVP_SDK_StreamType_name(EVP_SDK_StreamType_enum_t value)
{
    switch (value) {
    case EVP_SDK_StreamType_Null: return "Null";
    case EVP_SDK_StreamType_Nng: return "Nng";
    default: return "";
    }
}

static inline int EVP_SDK_StreamType_is_known_value(EVP_SDK_StreamType_enum_t value)
{
    switch (value) {
    case EVP_SDK_StreamType_Null: return 1;
    case EVP_SDK_StreamType_Nng: return 1;
    default: return 0;
    }
}

typedef int8_t EVP_SDK_StreamDirection_enum_t;
__flatbuffers_define_integer_type(EVP_SDK_StreamDirection, EVP_SDK_StreamDirection_enum_t, 8)
#define EVP_SDK_StreamDirection_In ((EVP_SDK_StreamDirection_enum_t)INT8_C(0))
#define EVP_SDK_StreamDirection_Out ((EVP_SDK_StreamDirection_enum_t)INT8_C(1))

static inline const char *EVP_SDK_StreamDirection_name(EVP_SDK_StreamDirection_enum_t value)
{
    switch (value) {
    case EVP_SDK_StreamDirection_In: return "In";
    case EVP_SDK_StreamDirection_Out: return "Out";
    default: return "";
    }
}

static inline int EVP_SDK_StreamDirection_is_known_value(EVP_SDK_StreamDirection_enum_t value)
{
    switch (value) {
    case EVP_SDK_StreamDirection_In: return 1;
    case EVP_SDK_StreamDirection_Out: return 1;
    default: return 0;
    }
}



struct EVP_SDK_Config_table { uint8_t unused__; };

static inline size_t EVP_SDK_Config_vec_len(EVP_SDK_Config_vec_t vec)
__flatbuffers_vec_len(vec)
static inline EVP_SDK_Config_table_t EVP_SDK_Config_vec_at(EVP_SDK_Config_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(EVP_SDK_Config_table_t, vec, i, 0)
__flatbuffers_table_as_root(EVP_SDK_Config)

__flatbuffers_define_string_field(0, EVP_SDK_Config, topic, 1)
__flatbuffers_define_vector_field(1, EVP_SDK_Config, blob, flatbuffers_uint8_vec_t, 1)

struct EVP_SDK_StateInput_table { uint8_t unused__; };

static inline size_t EVP_SDK_StateInput_vec_len(EVP_SDK_StateInput_vec_t vec)
__flatbuffers_vec_len(vec)
static inline EVP_SDK_StateInput_table_t EVP_SDK_StateInput_vec_at(EVP_SDK_StateInput_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(EVP_SDK_StateInput_table_t, vec, i, 0)
__flatbuffers_table_as_root(EVP_SDK_StateInput)

__flatbuffers_define_string_field(0, EVP_SDK_StateInput, topic, 1)
__flatbuffers_define_vector_field(1, EVP_SDK_StateInput, blob, flatbuffers_uint8_vec_t, 1)
__flatbuffers_define_scalar_field(2, EVP_SDK_StateInput, cb, flatbuffers_uint64, uint64_t, UINT64_C(0))
__flatbuffers_define_scalar_field(3, EVP_SDK_StateInput, cb_userdata, flatbuffers_uint64, uint64_t, UINT64_C(0))

struct EVP_SDK_StateOutput_table { uint8_t unused__; };

static inline size_t EVP_SDK_StateOutput_vec_len(EVP_SDK_StateOutput_vec_t vec)
__flatbuffers_vec_len(vec)
static inline EVP_SDK_StateOutput_table_t EVP_SDK_StateOutput_vec_at(EVP_SDK_StateOutput_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(EVP_SDK_StateOutput_table_t, vec, i, 0)
__flatbuffers_table_as_root(EVP_SDK_StateOutput)

__flatbuffers_define_scalar_field(0, EVP_SDK_StateOutput, cb, flatbuffers_uint64, uint64_t, UINT64_C(0))
__flatbuffers_define_scalar_field(1, EVP_SDK_StateOutput, reason, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_scalar_field(2, EVP_SDK_StateOutput, cb_userdata, flatbuffers_uint64, uint64_t, UINT64_C(0))

struct EVP_SDK_Exit_table { uint8_t unused__; };

static inline size_t EVP_SDK_Exit_vec_len(EVP_SDK_Exit_vec_t vec)
__flatbuffers_vec_len(vec)
static inline EVP_SDK_Exit_table_t EVP_SDK_Exit_vec_at(EVP_SDK_Exit_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(EVP_SDK_Exit_table_t, vec, i, 0)
__flatbuffers_table_as_root(EVP_SDK_Exit)


struct EVP_SDK_BlobRequestAzureBlob_table { uint8_t unused__; };

static inline size_t EVP_SDK_BlobRequestAzureBlob_vec_len(EVP_SDK_BlobRequestAzureBlob_vec_t vec)
__flatbuffers_vec_len(vec)
static inline EVP_SDK_BlobRequestAzureBlob_table_t EVP_SDK_BlobRequestAzureBlob_vec_at(EVP_SDK_BlobRequestAzureBlob_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(EVP_SDK_BlobRequestAzureBlob_table_t, vec, i, 0)
__flatbuffers_table_as_root(EVP_SDK_BlobRequestAzureBlob)

__flatbuffers_define_string_field(0, EVP_SDK_BlobRequestAzureBlob, url, 1)

struct EVP_SDK_BlobRequestEvp_table { uint8_t unused__; };

static inline size_t EVP_SDK_BlobRequestEvp_vec_len(EVP_SDK_BlobRequestEvp_vec_t vec)
__flatbuffers_vec_len(vec)
static inline EVP_SDK_BlobRequestEvp_table_t EVP_SDK_BlobRequestEvp_vec_at(EVP_SDK_BlobRequestEvp_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(EVP_SDK_BlobRequestEvp_table_t, vec, i, 0)
__flatbuffers_table_as_root(EVP_SDK_BlobRequestEvp)

__flatbuffers_define_string_field(0, EVP_SDK_BlobRequestEvp, remoteName, 1)
__flatbuffers_define_string_field(1, EVP_SDK_BlobRequestEvp, storageName, 0)

struct EVP_SDK_BlobRequestHttp_table { uint8_t unused__; };

static inline size_t EVP_SDK_BlobRequestHttp_vec_len(EVP_SDK_BlobRequestHttp_vec_t vec)
__flatbuffers_vec_len(vec)
static inline EVP_SDK_BlobRequestHttp_table_t EVP_SDK_BlobRequestHttp_vec_at(EVP_SDK_BlobRequestHttp_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(EVP_SDK_BlobRequestHttp_table_t, vec, i, 0)
__flatbuffers_table_as_root(EVP_SDK_BlobRequestHttp)

__flatbuffers_define_string_field(0, EVP_SDK_BlobRequestHttp, url, 1)

struct EVP_SDK_BlobRequestHttpExt_table { uint8_t unused__; };

static inline size_t EVP_SDK_BlobRequestHttpExt_vec_len(EVP_SDK_BlobRequestHttpExt_vec_t vec)
__flatbuffers_vec_len(vec)
static inline EVP_SDK_BlobRequestHttpExt_table_t EVP_SDK_BlobRequestHttpExt_vec_at(EVP_SDK_BlobRequestHttpExt_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(EVP_SDK_BlobRequestHttpExt_table_t, vec, i, 0)
__flatbuffers_table_as_root(EVP_SDK_BlobRequestHttpExt)

__flatbuffers_define_string_field(0, EVP_SDK_BlobRequestHttpExt, url, 1)
__flatbuffers_define_vector_field(1, EVP_SDK_BlobRequestHttpExt, headers, flatbuffers_string_vec_t, 1)
typedef uint8_t EVP_SDK_BlobRequestUnion_union_type_t;
__flatbuffers_define_integer_type(EVP_SDK_BlobRequestUnion, EVP_SDK_BlobRequestUnion_union_type_t, 8)
__flatbuffers_define_union(flatbuffers_, EVP_SDK_BlobRequestUnion)
#define EVP_SDK_BlobRequestUnion_NONE ((EVP_SDK_BlobRequestUnion_union_type_t)UINT8_C(0))
#define EVP_SDK_BlobRequestUnion_azureBlob ((EVP_SDK_BlobRequestUnion_union_type_t)UINT8_C(1))
#define EVP_SDK_BlobRequestUnion_evp ((EVP_SDK_BlobRequestUnion_union_type_t)UINT8_C(2))
#define EVP_SDK_BlobRequestUnion_http ((EVP_SDK_BlobRequestUnion_union_type_t)UINT8_C(3))
#define EVP_SDK_BlobRequestUnion_http_ext ((EVP_SDK_BlobRequestUnion_union_type_t)UINT8_C(4))

static inline const char *EVP_SDK_BlobRequestUnion_type_name(EVP_SDK_BlobRequestUnion_union_type_t type)
{
    switch (type) {
    case EVP_SDK_BlobRequestUnion_NONE: return "NONE";
    case EVP_SDK_BlobRequestUnion_azureBlob: return "azureBlob";
    case EVP_SDK_BlobRequestUnion_evp: return "evp";
    case EVP_SDK_BlobRequestUnion_http: return "http";
    case EVP_SDK_BlobRequestUnion_http_ext: return "http_ext";
    default: return "";
    }
}

static inline int EVP_SDK_BlobRequestUnion_is_known_type(EVP_SDK_BlobRequestUnion_union_type_t type)
{
    switch (type) {
    case EVP_SDK_BlobRequestUnion_NONE: return 1;
    case EVP_SDK_BlobRequestUnion_azureBlob: return 1;
    case EVP_SDK_BlobRequestUnion_evp: return 1;
    case EVP_SDK_BlobRequestUnion_http: return 1;
    case EVP_SDK_BlobRequestUnion_http_ext: return 1;
    default: return 0;
    }
}


struct EVP_SDK_BlobInput_table { uint8_t unused__; };

static inline size_t EVP_SDK_BlobInput_vec_len(EVP_SDK_BlobInput_vec_t vec)
__flatbuffers_vec_len(vec)
static inline EVP_SDK_BlobInput_table_t EVP_SDK_BlobInput_vec_at(EVP_SDK_BlobInput_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(EVP_SDK_BlobInput_table_t, vec, i, 0)
__flatbuffers_table_as_root(EVP_SDK_BlobInput)

__flatbuffers_define_scalar_field(0, EVP_SDK_BlobInput, type, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_scalar_field(1, EVP_SDK_BlobInput, op, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_union_field(flatbuffers_, 3, EVP_SDK_BlobInput, request, EVP_SDK_BlobRequestUnion, 1)
__flatbuffers_define_string_field(4, EVP_SDK_BlobInput, filename, 1)
__flatbuffers_define_scalar_field(5, EVP_SDK_BlobInput, cb, flatbuffers_uint64, uint64_t, UINT64_C(0))
__flatbuffers_define_scalar_field(6, EVP_SDK_BlobInput, cb_userdata, flatbuffers_uint64, uint64_t, UINT64_C(0))

struct EVP_SDK_BlobResultAzureBlob_table { uint8_t unused__; };

static inline size_t EVP_SDK_BlobResultAzureBlob_vec_len(EVP_SDK_BlobResultAzureBlob_vec_t vec)
__flatbuffers_vec_len(vec)
static inline EVP_SDK_BlobResultAzureBlob_table_t EVP_SDK_BlobResultAzureBlob_vec_at(EVP_SDK_BlobResultAzureBlob_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(EVP_SDK_BlobResultAzureBlob_table_t, vec, i, 0)
__flatbuffers_table_as_root(EVP_SDK_BlobResultAzureBlob)

__flatbuffers_define_scalar_field(0, EVP_SDK_BlobResultAzureBlob, result, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_scalar_field(1, EVP_SDK_BlobResultAzureBlob, error, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_scalar_field(2, EVP_SDK_BlobResultAzureBlob, http_status, flatbuffers_uint32, uint32_t, UINT32_C(0))

struct EVP_SDK_BlobResultEvp_table { uint8_t unused__; };

static inline size_t EVP_SDK_BlobResultEvp_vec_len(EVP_SDK_BlobResultEvp_vec_t vec)
__flatbuffers_vec_len(vec)
static inline EVP_SDK_BlobResultEvp_table_t EVP_SDK_BlobResultEvp_vec_at(EVP_SDK_BlobResultEvp_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(EVP_SDK_BlobResultEvp_table_t, vec, i, 0)
__flatbuffers_table_as_root(EVP_SDK_BlobResultEvp)

__flatbuffers_define_scalar_field(0, EVP_SDK_BlobResultEvp, result, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_scalar_field(1, EVP_SDK_BlobResultEvp, error, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_scalar_field(2, EVP_SDK_BlobResultEvp, http_status, flatbuffers_uint32, uint32_t, UINT32_C(0))

struct EVP_SDK_BlobResultHttp_table { uint8_t unused__; };

static inline size_t EVP_SDK_BlobResultHttp_vec_len(EVP_SDK_BlobResultHttp_vec_t vec)
__flatbuffers_vec_len(vec)
static inline EVP_SDK_BlobResultHttp_table_t EVP_SDK_BlobResultHttp_vec_at(EVP_SDK_BlobResultHttp_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(EVP_SDK_BlobResultHttp_table_t, vec, i, 0)
__flatbuffers_table_as_root(EVP_SDK_BlobResultHttp)

__flatbuffers_define_scalar_field(0, EVP_SDK_BlobResultHttp, result, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_scalar_field(1, EVP_SDK_BlobResultHttp, error, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_scalar_field(2, EVP_SDK_BlobResultHttp, http_status, flatbuffers_uint32, uint32_t, UINT32_C(0))

struct EVP_SDK_BlobResultHttpExt_table { uint8_t unused__; };

static inline size_t EVP_SDK_BlobResultHttpExt_vec_len(EVP_SDK_BlobResultHttpExt_vec_t vec)
__flatbuffers_vec_len(vec)
static inline EVP_SDK_BlobResultHttpExt_table_t EVP_SDK_BlobResultHttpExt_vec_at(EVP_SDK_BlobResultHttpExt_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(EVP_SDK_BlobResultHttpExt_table_t, vec, i, 0)
__flatbuffers_table_as_root(EVP_SDK_BlobResultHttpExt)

__flatbuffers_define_scalar_field(0, EVP_SDK_BlobResultHttpExt, result, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_scalar_field(1, EVP_SDK_BlobResultHttpExt, error, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_scalar_field(2, EVP_SDK_BlobResultHttpExt, http_status, flatbuffers_uint32, uint32_t, UINT32_C(0))
typedef uint8_t EVP_SDK_BlobResultUnion_union_type_t;
__flatbuffers_define_integer_type(EVP_SDK_BlobResultUnion, EVP_SDK_BlobResultUnion_union_type_t, 8)
__flatbuffers_define_union(flatbuffers_, EVP_SDK_BlobResultUnion)
#define EVP_SDK_BlobResultUnion_NONE ((EVP_SDK_BlobResultUnion_union_type_t)UINT8_C(0))
#define EVP_SDK_BlobResultUnion_azureBlob ((EVP_SDK_BlobResultUnion_union_type_t)UINT8_C(1))
#define EVP_SDK_BlobResultUnion_evp ((EVP_SDK_BlobResultUnion_union_type_t)UINT8_C(2))
#define EVP_SDK_BlobResultUnion_http ((EVP_SDK_BlobResultUnion_union_type_t)UINT8_C(3))
#define EVP_SDK_BlobResultUnion_http_ext ((EVP_SDK_BlobResultUnion_union_type_t)UINT8_C(4))

static inline const char *EVP_SDK_BlobResultUnion_type_name(EVP_SDK_BlobResultUnion_union_type_t type)
{
    switch (type) {
    case EVP_SDK_BlobResultUnion_NONE: return "NONE";
    case EVP_SDK_BlobResultUnion_azureBlob: return "azureBlob";
    case EVP_SDK_BlobResultUnion_evp: return "evp";
    case EVP_SDK_BlobResultUnion_http: return "http";
    case EVP_SDK_BlobResultUnion_http_ext: return "http_ext";
    default: return "";
    }
}

static inline int EVP_SDK_BlobResultUnion_is_known_type(EVP_SDK_BlobResultUnion_union_type_t type)
{
    switch (type) {
    case EVP_SDK_BlobResultUnion_NONE: return 1;
    case EVP_SDK_BlobResultUnion_azureBlob: return 1;
    case EVP_SDK_BlobResultUnion_evp: return 1;
    case EVP_SDK_BlobResultUnion_http: return 1;
    case EVP_SDK_BlobResultUnion_http_ext: return 1;
    default: return 0;
    }
}


struct EVP_SDK_BlobOutput_table { uint8_t unused__; };

static inline size_t EVP_SDK_BlobOutput_vec_len(EVP_SDK_BlobOutput_vec_t vec)
__flatbuffers_vec_len(vec)
static inline EVP_SDK_BlobOutput_table_t EVP_SDK_BlobOutput_vec_at(EVP_SDK_BlobOutput_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(EVP_SDK_BlobOutput_table_t, vec, i, 0)
__flatbuffers_table_as_root(EVP_SDK_BlobOutput)

__flatbuffers_define_union_field(flatbuffers_, 1, EVP_SDK_BlobOutput, result, EVP_SDK_BlobResultUnion, 0)
__flatbuffers_define_scalar_field(2, EVP_SDK_BlobOutput, cb, flatbuffers_uint64, uint64_t, UINT64_C(0))
__flatbuffers_define_scalar_field(3, EVP_SDK_BlobOutput, reason, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_scalar_field(4, EVP_SDK_BlobOutput, cb_userdata, flatbuffers_uint64, uint64_t, UINT64_C(0))

struct EVP_SDK_MessageSentInput_table { uint8_t unused__; };

static inline size_t EVP_SDK_MessageSentInput_vec_len(EVP_SDK_MessageSentInput_vec_t vec)
__flatbuffers_vec_len(vec)
static inline EVP_SDK_MessageSentInput_table_t EVP_SDK_MessageSentInput_vec_at(EVP_SDK_MessageSentInput_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(EVP_SDK_MessageSentInput_table_t, vec, i, 0)
__flatbuffers_table_as_root(EVP_SDK_MessageSentInput)

__flatbuffers_define_string_field(0, EVP_SDK_MessageSentInput, topic, 1)
__flatbuffers_define_vector_field(1, EVP_SDK_MessageSentInput, blob, flatbuffers_uint8_vec_t, 1)
__flatbuffers_define_scalar_field(2, EVP_SDK_MessageSentInput, cb, flatbuffers_uint64, uint64_t, UINT64_C(0))
__flatbuffers_define_scalar_field(3, EVP_SDK_MessageSentInput, cb_userdata, flatbuffers_uint64, uint64_t, UINT64_C(0))

struct EVP_SDK_MessageSentOutput_table { uint8_t unused__; };

static inline size_t EVP_SDK_MessageSentOutput_vec_len(EVP_SDK_MessageSentOutput_vec_t vec)
__flatbuffers_vec_len(vec)
static inline EVP_SDK_MessageSentOutput_table_t EVP_SDK_MessageSentOutput_vec_at(EVP_SDK_MessageSentOutput_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(EVP_SDK_MessageSentOutput_table_t, vec, i, 0)
__flatbuffers_table_as_root(EVP_SDK_MessageSentOutput)

__flatbuffers_define_scalar_field(0, EVP_SDK_MessageSentOutput, cb, flatbuffers_uint64, uint64_t, UINT64_C(0))
__flatbuffers_define_scalar_field(1, EVP_SDK_MessageSentOutput, reason, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_scalar_field(2, EVP_SDK_MessageSentOutput, cb_userdata, flatbuffers_uint64, uint64_t, UINT64_C(0))

struct EVP_SDK_MessageReceived_table { uint8_t unused__; };

static inline size_t EVP_SDK_MessageReceived_vec_len(EVP_SDK_MessageReceived_vec_t vec)
__flatbuffers_vec_len(vec)
static inline EVP_SDK_MessageReceived_table_t EVP_SDK_MessageReceived_vec_at(EVP_SDK_MessageReceived_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(EVP_SDK_MessageReceived_table_t, vec, i, 0)
__flatbuffers_table_as_root(EVP_SDK_MessageReceived)

__flatbuffers_define_string_field(0, EVP_SDK_MessageReceived, topic, 1)
__flatbuffers_define_vector_field(1, EVP_SDK_MessageReceived, blob, flatbuffers_uint8_vec_t, 1)

struct EVP_SDK_TelemetryEntry_table { uint8_t unused__; };

static inline size_t EVP_SDK_TelemetryEntry_vec_len(EVP_SDK_TelemetryEntry_vec_t vec)
__flatbuffers_vec_len(vec)
static inline EVP_SDK_TelemetryEntry_table_t EVP_SDK_TelemetryEntry_vec_at(EVP_SDK_TelemetryEntry_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(EVP_SDK_TelemetryEntry_table_t, vec, i, 0)
__flatbuffers_table_as_root(EVP_SDK_TelemetryEntry)

__flatbuffers_define_string_field(0, EVP_SDK_TelemetryEntry, key, 1)
__flatbuffers_define_string_field(1, EVP_SDK_TelemetryEntry, value, 1)

struct EVP_SDK_TelemetryInput_table { uint8_t unused__; };

static inline size_t EVP_SDK_TelemetryInput_vec_len(EVP_SDK_TelemetryInput_vec_t vec)
__flatbuffers_vec_len(vec)
static inline EVP_SDK_TelemetryInput_table_t EVP_SDK_TelemetryInput_vec_at(EVP_SDK_TelemetryInput_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(EVP_SDK_TelemetryInput_table_t, vec, i, 0)
__flatbuffers_table_as_root(EVP_SDK_TelemetryInput)

__flatbuffers_define_vector_field(0, EVP_SDK_TelemetryInput, entries, EVP_SDK_TelemetryEntry_vec_t, 0)
__flatbuffers_define_scalar_field(1, EVP_SDK_TelemetryInput, cb, flatbuffers_uint64, uint64_t, UINT64_C(0))
__flatbuffers_define_scalar_field(2, EVP_SDK_TelemetryInput, cb_userdata, flatbuffers_uint64, uint64_t, UINT64_C(0))

struct EVP_SDK_TelemetryOutput_table { uint8_t unused__; };

static inline size_t EVP_SDK_TelemetryOutput_vec_len(EVP_SDK_TelemetryOutput_vec_t vec)
__flatbuffers_vec_len(vec)
static inline EVP_SDK_TelemetryOutput_table_t EVP_SDK_TelemetryOutput_vec_at(EVP_SDK_TelemetryOutput_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(EVP_SDK_TelemetryOutput_table_t, vec, i, 0)
__flatbuffers_table_as_root(EVP_SDK_TelemetryOutput)

__flatbuffers_define_scalar_field(0, EVP_SDK_TelemetryOutput, cb, flatbuffers_uint64, uint64_t, UINT64_C(0))
__flatbuffers_define_scalar_field(1, EVP_SDK_TelemetryOutput, reason, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_scalar_field(2, EVP_SDK_TelemetryOutput, cb_userdata, flatbuffers_uint64, uint64_t, UINT64_C(0))

struct EVP_SDK_RpcRequest_table { uint8_t unused__; };

static inline size_t EVP_SDK_RpcRequest_vec_len(EVP_SDK_RpcRequest_vec_t vec)
__flatbuffers_vec_len(vec)
static inline EVP_SDK_RpcRequest_table_t EVP_SDK_RpcRequest_vec_at(EVP_SDK_RpcRequest_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(EVP_SDK_RpcRequest_table_t, vec, i, 0)
__flatbuffers_table_as_root(EVP_SDK_RpcRequest)

__flatbuffers_define_scalar_field(0, EVP_SDK_RpcRequest, id, flatbuffers_uint64, uint64_t, UINT64_C(0))
__flatbuffers_define_string_field(1, EVP_SDK_RpcRequest, method, 1)
__flatbuffers_define_string_field(2, EVP_SDK_RpcRequest, params, 1)

struct EVP_SDK_RpcResponseInput_table { uint8_t unused__; };

static inline size_t EVP_SDK_RpcResponseInput_vec_len(EVP_SDK_RpcResponseInput_vec_t vec)
__flatbuffers_vec_len(vec)
static inline EVP_SDK_RpcResponseInput_table_t EVP_SDK_RpcResponseInput_vec_at(EVP_SDK_RpcResponseInput_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(EVP_SDK_RpcResponseInput_table_t, vec, i, 0)
__flatbuffers_table_as_root(EVP_SDK_RpcResponseInput)

__flatbuffers_define_scalar_field(0, EVP_SDK_RpcResponseInput, id, flatbuffers_uint64, uint64_t, UINT64_C(0))
__flatbuffers_define_string_field(1, EVP_SDK_RpcResponseInput, response, 0)
__flatbuffers_define_scalar_field(2, EVP_SDK_RpcResponseInput, status, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_scalar_field(3, EVP_SDK_RpcResponseInput, cb, flatbuffers_uint64, uint64_t, UINT64_C(0))
__flatbuffers_define_scalar_field(4, EVP_SDK_RpcResponseInput, cb_userdata, flatbuffers_uint64, uint64_t, UINT64_C(0))

struct EVP_SDK_RpcResponseOutput_table { uint8_t unused__; };

static inline size_t EVP_SDK_RpcResponseOutput_vec_len(EVP_SDK_RpcResponseOutput_vec_t vec)
__flatbuffers_vec_len(vec)
static inline EVP_SDK_RpcResponseOutput_table_t EVP_SDK_RpcResponseOutput_vec_at(EVP_SDK_RpcResponseOutput_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(EVP_SDK_RpcResponseOutput_table_t, vec, i, 0)
__flatbuffers_table_as_root(EVP_SDK_RpcResponseOutput)

__flatbuffers_define_scalar_field(0, EVP_SDK_RpcResponseOutput, cb, flatbuffers_uint64, uint64_t, UINT64_C(0))
__flatbuffers_define_scalar_field(1, EVP_SDK_RpcResponseOutput, reason, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_scalar_field(2, EVP_SDK_RpcResponseOutput, cb_userdata, flatbuffers_uint64, uint64_t, UINT64_C(0))
typedef uint8_t EVP_SDK_EventBody_union_type_t;
__flatbuffers_define_integer_type(EVP_SDK_EventBody, EVP_SDK_EventBody_union_type_t, 8)
__flatbuffers_define_union(flatbuffers_, EVP_SDK_EventBody)
#define EVP_SDK_EventBody_NONE ((EVP_SDK_EventBody_union_type_t)UINT8_C(0))
#define EVP_SDK_EventBody_config ((EVP_SDK_EventBody_union_type_t)UINT8_C(1))
#define EVP_SDK_EventBody_state ((EVP_SDK_EventBody_union_type_t)UINT8_C(2))
#define EVP_SDK_EventBody_exit ((EVP_SDK_EventBody_union_type_t)UINT8_C(3))
#define EVP_SDK_EventBody_blob ((EVP_SDK_EventBody_union_type_t)UINT8_C(4))
#define EVP_SDK_EventBody_messageSent ((EVP_SDK_EventBody_union_type_t)UINT8_C(5))
#define EVP_SDK_EventBody_messageReceived ((EVP_SDK_EventBody_union_type_t)UINT8_C(6))
#define EVP_SDK_EventBody_telemetry ((EVP_SDK_EventBody_union_type_t)UINT8_C(7))
#define EVP_SDK_EventBody_rpcRequest ((EVP_SDK_EventBody_union_type_t)UINT8_C(8))
#define EVP_SDK_EventBody_rpcResponse ((EVP_SDK_EventBody_union_type_t)UINT8_C(9))

static inline const char *EVP_SDK_EventBody_type_name(EVP_SDK_EventBody_union_type_t type)
{
    switch (type) {
    case EVP_SDK_EventBody_NONE: return "NONE";
    case EVP_SDK_EventBody_config: return "config";
    case EVP_SDK_EventBody_state: return "state";
    case EVP_SDK_EventBody_exit: return "exit";
    case EVP_SDK_EventBody_blob: return "blob";
    case EVP_SDK_EventBody_messageSent: return "messageSent";
    case EVP_SDK_EventBody_messageReceived: return "messageReceived";
    case EVP_SDK_EventBody_telemetry: return "telemetry";
    case EVP_SDK_EventBody_rpcRequest: return "rpcRequest";
    case EVP_SDK_EventBody_rpcResponse: return "rpcResponse";
    default: return "";
    }
}

static inline int EVP_SDK_EventBody_is_known_type(EVP_SDK_EventBody_union_type_t type)
{
    switch (type) {
    case EVP_SDK_EventBody_NONE: return 1;
    case EVP_SDK_EventBody_config: return 1;
    case EVP_SDK_EventBody_state: return 1;
    case EVP_SDK_EventBody_exit: return 1;
    case EVP_SDK_EventBody_blob: return 1;
    case EVP_SDK_EventBody_messageSent: return 1;
    case EVP_SDK_EventBody_messageReceived: return 1;
    case EVP_SDK_EventBody_telemetry: return 1;
    case EVP_SDK_EventBody_rpcRequest: return 1;
    case EVP_SDK_EventBody_rpcResponse: return 1;
    default: return 0;
    }
}


struct EVP_SDK_Event_table { uint8_t unused__; };

static inline size_t EVP_SDK_Event_vec_len(EVP_SDK_Event_vec_t vec)
__flatbuffers_vec_len(vec)
static inline EVP_SDK_Event_table_t EVP_SDK_Event_vec_at(EVP_SDK_Event_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(EVP_SDK_Event_table_t, vec, i, 0)
__flatbuffers_table_as_root(EVP_SDK_Event)

__flatbuffers_define_union_field(flatbuffers_, 1, EVP_SDK_Event, body, EVP_SDK_EventBody, 0)

struct EVP_SDK_GetEvent_table { uint8_t unused__; };

static inline size_t EVP_SDK_GetEvent_vec_len(EVP_SDK_GetEvent_vec_t vec)
__flatbuffers_vec_len(vec)
static inline EVP_SDK_GetEvent_table_t EVP_SDK_GetEvent_vec_at(EVP_SDK_GetEvent_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(EVP_SDK_GetEvent_table_t, vec, i, 0)
__flatbuffers_table_as_root(EVP_SDK_GetEvent)

__flatbuffers_define_scalar_field(0, EVP_SDK_GetEvent, timeout_sec, flatbuffers_uint64, uint64_t, UINT64_C(0))
__flatbuffers_define_scalar_field(1, EVP_SDK_GetEvent, timeout_nsec, flatbuffers_uint64, uint64_t, UINT64_C(0))

struct EVP_SDK_RequestResendConfig_table { uint8_t unused__; };

static inline size_t EVP_SDK_RequestResendConfig_vec_len(EVP_SDK_RequestResendConfig_vec_t vec)
__flatbuffers_vec_len(vec)
static inline EVP_SDK_RequestResendConfig_table_t EVP_SDK_RequestResendConfig_vec_at(EVP_SDK_RequestResendConfig_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(EVP_SDK_RequestResendConfig_table_t, vec, i, 0)
__flatbuffers_table_as_root(EVP_SDK_RequestResendConfig)

typedef uint8_t EVP_SDK_RequestUnion_union_type_t;
__flatbuffers_define_integer_type(EVP_SDK_RequestUnion, EVP_SDK_RequestUnion_union_type_t, 8)
__flatbuffers_define_union(flatbuffers_, EVP_SDK_RequestUnion)
#define EVP_SDK_RequestUnion_NONE ((EVP_SDK_RequestUnion_union_type_t)UINT8_C(0))
#define EVP_SDK_RequestUnion_getEvent ((EVP_SDK_RequestUnion_union_type_t)UINT8_C(1))
#define EVP_SDK_RequestUnion_sendState ((EVP_SDK_RequestUnion_union_type_t)UINT8_C(2))
#define EVP_SDK_RequestUnion_requestResendConfig ((EVP_SDK_RequestUnion_union_type_t)UINT8_C(3))
#define EVP_SDK_RequestUnion_blobOperation ((EVP_SDK_RequestUnion_union_type_t)UINT8_C(4))
#define EVP_SDK_RequestUnion_sendTelemetry ((EVP_SDK_RequestUnion_union_type_t)UINT8_C(5))
#define EVP_SDK_RequestUnion_sendMessage ((EVP_SDK_RequestUnion_union_type_t)UINT8_C(6))
#define EVP_SDK_RequestUnion_sendRpcResponse ((EVP_SDK_RequestUnion_union_type_t)UINT8_C(7))
#define EVP_SDK_RequestUnion_streamParamsRequest ((EVP_SDK_RequestUnion_union_type_t)UINT8_C(8))

static inline const char *EVP_SDK_RequestUnion_type_name(EVP_SDK_RequestUnion_union_type_t type)
{
    switch (type) {
    case EVP_SDK_RequestUnion_NONE: return "NONE";
    case EVP_SDK_RequestUnion_getEvent: return "getEvent";
    case EVP_SDK_RequestUnion_sendState: return "sendState";
    case EVP_SDK_RequestUnion_requestResendConfig: return "requestResendConfig";
    case EVP_SDK_RequestUnion_blobOperation: return "blobOperation";
    case EVP_SDK_RequestUnion_sendTelemetry: return "sendTelemetry";
    case EVP_SDK_RequestUnion_sendMessage: return "sendMessage";
    case EVP_SDK_RequestUnion_sendRpcResponse: return "sendRpcResponse";
    case EVP_SDK_RequestUnion_streamParamsRequest: return "streamParamsRequest";
    default: return "";
    }
}

static inline int EVP_SDK_RequestUnion_is_known_type(EVP_SDK_RequestUnion_union_type_t type)
{
    switch (type) {
    case EVP_SDK_RequestUnion_NONE: return 1;
    case EVP_SDK_RequestUnion_getEvent: return 1;
    case EVP_SDK_RequestUnion_sendState: return 1;
    case EVP_SDK_RequestUnion_requestResendConfig: return 1;
    case EVP_SDK_RequestUnion_blobOperation: return 1;
    case EVP_SDK_RequestUnion_sendTelemetry: return 1;
    case EVP_SDK_RequestUnion_sendMessage: return 1;
    case EVP_SDK_RequestUnion_sendRpcResponse: return 1;
    case EVP_SDK_RequestUnion_streamParamsRequest: return 1;
    default: return 0;
    }
}


struct EVP_SDK_Request_table { uint8_t unused__; };

static inline size_t EVP_SDK_Request_vec_len(EVP_SDK_Request_vec_t vec)
__flatbuffers_vec_len(vec)
static inline EVP_SDK_Request_table_t EVP_SDK_Request_vec_at(EVP_SDK_Request_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(EVP_SDK_Request_table_t, vec, i, 0)
__flatbuffers_table_as_root(EVP_SDK_Request)

__flatbuffers_define_union_field(flatbuffers_, 1, EVP_SDK_Request, body, EVP_SDK_RequestUnion, 1)

struct EVP_SDK_Simple_table { uint8_t unused__; };

static inline size_t EVP_SDK_Simple_vec_len(EVP_SDK_Simple_vec_t vec)
__flatbuffers_vec_len(vec)
static inline EVP_SDK_Simple_table_t EVP_SDK_Simple_vec_at(EVP_SDK_Simple_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(EVP_SDK_Simple_table_t, vec, i, 0)
__flatbuffers_table_as_root(EVP_SDK_Simple)

__flatbuffers_define_scalar_field(0, EVP_SDK_Simple, result, flatbuffers_uint32, uint32_t, UINT32_C(0))
typedef uint8_t EVP_SDK_ResponseUnion_union_type_t;
__flatbuffers_define_integer_type(EVP_SDK_ResponseUnion, EVP_SDK_ResponseUnion_union_type_t, 8)
__flatbuffers_define_union(flatbuffers_, EVP_SDK_ResponseUnion)
#define EVP_SDK_ResponseUnion_NONE ((EVP_SDK_ResponseUnion_union_type_t)UINT8_C(0))
#define EVP_SDK_ResponseUnion_getEvent ((EVP_SDK_ResponseUnion_union_type_t)UINT8_C(1))
#define EVP_SDK_ResponseUnion_simple ((EVP_SDK_ResponseUnion_union_type_t)UINT8_C(2))
#define EVP_SDK_ResponseUnion_streamParamsResponse ((EVP_SDK_ResponseUnion_union_type_t)UINT8_C(3))

static inline const char *EVP_SDK_ResponseUnion_type_name(EVP_SDK_ResponseUnion_union_type_t type)
{
    switch (type) {
    case EVP_SDK_ResponseUnion_NONE: return "NONE";
    case EVP_SDK_ResponseUnion_getEvent: return "getEvent";
    case EVP_SDK_ResponseUnion_simple: return "simple";
    case EVP_SDK_ResponseUnion_streamParamsResponse: return "streamParamsResponse";
    default: return "";
    }
}

static inline int EVP_SDK_ResponseUnion_is_known_type(EVP_SDK_ResponseUnion_union_type_t type)
{
    switch (type) {
    case EVP_SDK_ResponseUnion_NONE: return 1;
    case EVP_SDK_ResponseUnion_getEvent: return 1;
    case EVP_SDK_ResponseUnion_simple: return 1;
    case EVP_SDK_ResponseUnion_streamParamsResponse: return 1;
    default: return 0;
    }
}


struct EVP_SDK_Response_table { uint8_t unused__; };

static inline size_t EVP_SDK_Response_vec_len(EVP_SDK_Response_vec_t vec)
__flatbuffers_vec_len(vec)
static inline EVP_SDK_Response_table_t EVP_SDK_Response_vec_at(EVP_SDK_Response_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(EVP_SDK_Response_table_t, vec, i, 0)
__flatbuffers_table_as_root(EVP_SDK_Response)

__flatbuffers_define_union_field(flatbuffers_, 1, EVP_SDK_Response, body, EVP_SDK_ResponseUnion, 1)

struct EVP_SDK_StreamParamsRequest_table { uint8_t unused__; };

static inline size_t EVP_SDK_StreamParamsRequest_vec_len(EVP_SDK_StreamParamsRequest_vec_t vec)
__flatbuffers_vec_len(vec)
static inline EVP_SDK_StreamParamsRequest_table_t EVP_SDK_StreamParamsRequest_vec_at(EVP_SDK_StreamParamsRequest_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(EVP_SDK_StreamParamsRequest_table_t, vec, i, 0)
__flatbuffers_table_as_root(EVP_SDK_StreamParamsRequest)

__flatbuffers_define_string_field(0, EVP_SDK_StreamParamsRequest, name, 0)

struct EVP_SDK_StreamNng_table { uint8_t unused__; };

static inline size_t EVP_SDK_StreamNng_vec_len(EVP_SDK_StreamNng_vec_t vec)
__flatbuffers_vec_len(vec)
static inline EVP_SDK_StreamNng_table_t EVP_SDK_StreamNng_vec_at(EVP_SDK_StreamNng_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(EVP_SDK_StreamNng_table_t, vec, i, 0)
__flatbuffers_table_as_root(EVP_SDK_StreamNng)

__flatbuffers_define_scalar_field(0, EVP_SDK_StreamNng, mode, EVP_SDK_StreamNngMode, EVP_SDK_StreamNngMode_enum_t, INT8_C(0))
__flatbuffers_define_scalar_field(1, EVP_SDK_StreamNng, protocol, EVP_SDK_StreamNngProtocol, EVP_SDK_StreamNngProtocol_enum_t, INT8_C(0))
__flatbuffers_define_string_field(2, EVP_SDK_StreamNng, connection, 0)
typedef uint8_t EVP_SDK_StreamParams_union_type_t;
__flatbuffers_define_integer_type(EVP_SDK_StreamParams, EVP_SDK_StreamParams_union_type_t, 8)
__flatbuffers_define_union(flatbuffers_, EVP_SDK_StreamParams)
#define EVP_SDK_StreamParams_NONE ((EVP_SDK_StreamParams_union_type_t)UINT8_C(0))
#define EVP_SDK_StreamParams_nng ((EVP_SDK_StreamParams_union_type_t)UINT8_C(1))

static inline const char *EVP_SDK_StreamParams_type_name(EVP_SDK_StreamParams_union_type_t type)
{
    switch (type) {
    case EVP_SDK_StreamParams_NONE: return "NONE";
    case EVP_SDK_StreamParams_nng: return "nng";
    default: return "";
    }
}

static inline int EVP_SDK_StreamParams_is_known_type(EVP_SDK_StreamParams_union_type_t type)
{
    switch (type) {
    case EVP_SDK_StreamParams_NONE: return 1;
    case EVP_SDK_StreamParams_nng: return 1;
    default: return 0;
    }
}


struct EVP_SDK_StreamParamsResponse_table { uint8_t unused__; };

static inline size_t EVP_SDK_StreamParamsResponse_vec_len(EVP_SDK_StreamParamsResponse_vec_t vec)
__flatbuffers_vec_len(vec)
static inline EVP_SDK_StreamParamsResponse_table_t EVP_SDK_StreamParamsResponse_vec_at(EVP_SDK_StreamParamsResponse_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(EVP_SDK_StreamParamsResponse_table_t, vec, i, 0)
__flatbuffers_table_as_root(EVP_SDK_StreamParamsResponse)

__flatbuffers_define_scalar_field(0, EVP_SDK_StreamParamsResponse, result, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_scalar_field(1, EVP_SDK_StreamParamsResponse, type, EVP_SDK_StreamType, EVP_SDK_StreamType_enum_t, INT8_C(0))
__flatbuffers_define_scalar_field(2, EVP_SDK_StreamParamsResponse, direction, EVP_SDK_StreamDirection, EVP_SDK_StreamDirection_enum_t, INT8_C(0))
__flatbuffers_define_union_field(flatbuffers_, 4, EVP_SDK_StreamParamsResponse, params, EVP_SDK_StreamParams, 0)


#include "flatcc/flatcc_epilogue.h"
#endif /* SDK_READER_H */
