/*
 * SPDX-FileCopyrightText: 2023-2024 Sony Semiconductor Solutions Corporation
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef SDK_BUILDER_H
#define SDK_BUILDER_H

/* Generated by flatcc 0.6.1 FlatBuffers schema compiler for C by dvide.com */

#ifndef SDK_READER_H
#include "sdk_reader.h"
#endif
#ifndef FLATBUFFERS_COMMON_BUILDER_H
#include "flatbuffers_common_builder.h"
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension "bin"
#endif

#define __EVP_SDK_StreamNngMode_formal_args , EVP_SDK_StreamNngMode_enum_t v0
#define __EVP_SDK_StreamNngMode_call_args , v0
__flatbuffers_build_scalar(flatbuffers_, EVP_SDK_StreamNngMode, EVP_SDK_StreamNngMode_enum_t)
#define __EVP_SDK_StreamNngProtocol_formal_args , EVP_SDK_StreamNngProtocol_enum_t v0
#define __EVP_SDK_StreamNngProtocol_call_args , v0
__flatbuffers_build_scalar(flatbuffers_, EVP_SDK_StreamNngProtocol, EVP_SDK_StreamNngProtocol_enum_t)
#define __EVP_SDK_StreamType_formal_args , EVP_SDK_StreamType_enum_t v0
#define __EVP_SDK_StreamType_call_args , v0
__flatbuffers_build_scalar(flatbuffers_, EVP_SDK_StreamType, EVP_SDK_StreamType_enum_t)
#define __EVP_SDK_StreamDirection_formal_args , EVP_SDK_StreamDirection_enum_t v0
#define __EVP_SDK_StreamDirection_call_args , v0
__flatbuffers_build_scalar(flatbuffers_, EVP_SDK_StreamDirection, EVP_SDK_StreamDirection_enum_t)

typedef flatbuffers_union_ref_t EVP_SDK_BlobRequestUnion_union_ref_t;
typedef flatbuffers_union_vec_ref_t EVP_SDK_BlobRequestUnion_union_vec_ref_t;
static EVP_SDK_BlobRequestUnion_union_ref_t EVP_SDK_BlobRequestUnion_clone(flatbuffers_builder_t *B, EVP_SDK_BlobRequestUnion_union_t t);
typedef flatbuffers_union_ref_t EVP_SDK_BlobResultUnion_union_ref_t;
typedef flatbuffers_union_vec_ref_t EVP_SDK_BlobResultUnion_union_vec_ref_t;
static EVP_SDK_BlobResultUnion_union_ref_t EVP_SDK_BlobResultUnion_clone(flatbuffers_builder_t *B, EVP_SDK_BlobResultUnion_union_t t);
typedef flatbuffers_union_ref_t EVP_SDK_EventBody_union_ref_t;
typedef flatbuffers_union_vec_ref_t EVP_SDK_EventBody_union_vec_ref_t;
static EVP_SDK_EventBody_union_ref_t EVP_SDK_EventBody_clone(flatbuffers_builder_t *B, EVP_SDK_EventBody_union_t t);
typedef flatbuffers_union_ref_t EVP_SDK_RequestUnion_union_ref_t;
typedef flatbuffers_union_vec_ref_t EVP_SDK_RequestUnion_union_vec_ref_t;
static EVP_SDK_RequestUnion_union_ref_t EVP_SDK_RequestUnion_clone(flatbuffers_builder_t *B, EVP_SDK_RequestUnion_union_t t);
typedef flatbuffers_union_ref_t EVP_SDK_ResponseUnion_union_ref_t;
typedef flatbuffers_union_vec_ref_t EVP_SDK_ResponseUnion_union_vec_ref_t;
static EVP_SDK_ResponseUnion_union_ref_t EVP_SDK_ResponseUnion_clone(flatbuffers_builder_t *B, EVP_SDK_ResponseUnion_union_t t);
typedef flatbuffers_union_ref_t EVP_SDK_StreamParams_union_ref_t;
typedef flatbuffers_union_vec_ref_t EVP_SDK_StreamParams_union_vec_ref_t;
static EVP_SDK_StreamParams_union_ref_t EVP_SDK_StreamParams_clone(flatbuffers_builder_t *B, EVP_SDK_StreamParams_union_t t);

static const flatbuffers_voffset_t __EVP_SDK_Config_required[] = { 0, 1, 0 };
typedef flatbuffers_ref_t EVP_SDK_Config_ref_t;
static EVP_SDK_Config_ref_t EVP_SDK_Config_clone(flatbuffers_builder_t *B, EVP_SDK_Config_table_t t);
__flatbuffers_build_table(flatbuffers_, EVP_SDK_Config, 2)

static const flatbuffers_voffset_t __EVP_SDK_StateInput_required[] = { 0, 1, 0 };
typedef flatbuffers_ref_t EVP_SDK_StateInput_ref_t;
static EVP_SDK_StateInput_ref_t EVP_SDK_StateInput_clone(flatbuffers_builder_t *B, EVP_SDK_StateInput_table_t t);
__flatbuffers_build_table(flatbuffers_, EVP_SDK_StateInput, 4)

static const flatbuffers_voffset_t __EVP_SDK_StateOutput_required[] = { 0 };
typedef flatbuffers_ref_t EVP_SDK_StateOutput_ref_t;
static EVP_SDK_StateOutput_ref_t EVP_SDK_StateOutput_clone(flatbuffers_builder_t *B, EVP_SDK_StateOutput_table_t t);
__flatbuffers_build_table(flatbuffers_, EVP_SDK_StateOutput, 3)

static const flatbuffers_voffset_t __EVP_SDK_Exit_required[] = { 0 };
typedef flatbuffers_ref_t EVP_SDK_Exit_ref_t;
static EVP_SDK_Exit_ref_t EVP_SDK_Exit_clone(flatbuffers_builder_t *B, EVP_SDK_Exit_table_t t);
__flatbuffers_build_table(flatbuffers_, EVP_SDK_Exit, 0)

static const flatbuffers_voffset_t __EVP_SDK_BlobRequestAzureBlob_required[] = { 0, 0 };
typedef flatbuffers_ref_t EVP_SDK_BlobRequestAzureBlob_ref_t;
static EVP_SDK_BlobRequestAzureBlob_ref_t EVP_SDK_BlobRequestAzureBlob_clone(flatbuffers_builder_t *B, EVP_SDK_BlobRequestAzureBlob_table_t t);
__flatbuffers_build_table(flatbuffers_, EVP_SDK_BlobRequestAzureBlob, 1)

static const flatbuffers_voffset_t __EVP_SDK_BlobRequestEvp_required[] = { 0, 0 };
typedef flatbuffers_ref_t EVP_SDK_BlobRequestEvp_ref_t;
static EVP_SDK_BlobRequestEvp_ref_t EVP_SDK_BlobRequestEvp_clone(flatbuffers_builder_t *B, EVP_SDK_BlobRequestEvp_table_t t);
__flatbuffers_build_table(flatbuffers_, EVP_SDK_BlobRequestEvp, 2)

static const flatbuffers_voffset_t __EVP_SDK_BlobRequestHttp_required[] = { 0, 0 };
typedef flatbuffers_ref_t EVP_SDK_BlobRequestHttp_ref_t;
static EVP_SDK_BlobRequestHttp_ref_t EVP_SDK_BlobRequestHttp_clone(flatbuffers_builder_t *B, EVP_SDK_BlobRequestHttp_table_t t);
__flatbuffers_build_table(flatbuffers_, EVP_SDK_BlobRequestHttp, 1)

static const flatbuffers_voffset_t __EVP_SDK_BlobRequestHttpExt_required[] = { 0, 1, 0 };
typedef flatbuffers_ref_t EVP_SDK_BlobRequestHttpExt_ref_t;
static EVP_SDK_BlobRequestHttpExt_ref_t EVP_SDK_BlobRequestHttpExt_clone(flatbuffers_builder_t *B, EVP_SDK_BlobRequestHttpExt_table_t t);
__flatbuffers_build_table(flatbuffers_, EVP_SDK_BlobRequestHttpExt, 2)

static const flatbuffers_voffset_t __EVP_SDK_BlobInput_required[] = { 3, 4, 0 };
typedef flatbuffers_ref_t EVP_SDK_BlobInput_ref_t;
static EVP_SDK_BlobInput_ref_t EVP_SDK_BlobInput_clone(flatbuffers_builder_t *B, EVP_SDK_BlobInput_table_t t);
__flatbuffers_build_table(flatbuffers_, EVP_SDK_BlobInput, 7)

static const flatbuffers_voffset_t __EVP_SDK_BlobResultAzureBlob_required[] = { 0 };
typedef flatbuffers_ref_t EVP_SDK_BlobResultAzureBlob_ref_t;
static EVP_SDK_BlobResultAzureBlob_ref_t EVP_SDK_BlobResultAzureBlob_clone(flatbuffers_builder_t *B, EVP_SDK_BlobResultAzureBlob_table_t t);
__flatbuffers_build_table(flatbuffers_, EVP_SDK_BlobResultAzureBlob, 3)

static const flatbuffers_voffset_t __EVP_SDK_BlobResultEvp_required[] = { 0 };
typedef flatbuffers_ref_t EVP_SDK_BlobResultEvp_ref_t;
static EVP_SDK_BlobResultEvp_ref_t EVP_SDK_BlobResultEvp_clone(flatbuffers_builder_t *B, EVP_SDK_BlobResultEvp_table_t t);
__flatbuffers_build_table(flatbuffers_, EVP_SDK_BlobResultEvp, 3)

static const flatbuffers_voffset_t __EVP_SDK_BlobResultHttp_required[] = { 0 };
typedef flatbuffers_ref_t EVP_SDK_BlobResultHttp_ref_t;
static EVP_SDK_BlobResultHttp_ref_t EVP_SDK_BlobResultHttp_clone(flatbuffers_builder_t *B, EVP_SDK_BlobResultHttp_table_t t);
__flatbuffers_build_table(flatbuffers_, EVP_SDK_BlobResultHttp, 3)

static const flatbuffers_voffset_t __EVP_SDK_BlobResultHttpExt_required[] = { 0 };
typedef flatbuffers_ref_t EVP_SDK_BlobResultHttpExt_ref_t;
static EVP_SDK_BlobResultHttpExt_ref_t EVP_SDK_BlobResultHttpExt_clone(flatbuffers_builder_t *B, EVP_SDK_BlobResultHttpExt_table_t t);
__flatbuffers_build_table(flatbuffers_, EVP_SDK_BlobResultHttpExt, 3)

static const flatbuffers_voffset_t __EVP_SDK_BlobOutput_required[] = { 0 };
typedef flatbuffers_ref_t EVP_SDK_BlobOutput_ref_t;
static EVP_SDK_BlobOutput_ref_t EVP_SDK_BlobOutput_clone(flatbuffers_builder_t *B, EVP_SDK_BlobOutput_table_t t);
__flatbuffers_build_table(flatbuffers_, EVP_SDK_BlobOutput, 5)

static const flatbuffers_voffset_t __EVP_SDK_MessageSentInput_required[] = { 0, 1, 0 };
typedef flatbuffers_ref_t EVP_SDK_MessageSentInput_ref_t;
static EVP_SDK_MessageSentInput_ref_t EVP_SDK_MessageSentInput_clone(flatbuffers_builder_t *B, EVP_SDK_MessageSentInput_table_t t);
__flatbuffers_build_table(flatbuffers_, EVP_SDK_MessageSentInput, 4)

static const flatbuffers_voffset_t __EVP_SDK_MessageSentOutput_required[] = { 0 };
typedef flatbuffers_ref_t EVP_SDK_MessageSentOutput_ref_t;
static EVP_SDK_MessageSentOutput_ref_t EVP_SDK_MessageSentOutput_clone(flatbuffers_builder_t *B, EVP_SDK_MessageSentOutput_table_t t);
__flatbuffers_build_table(flatbuffers_, EVP_SDK_MessageSentOutput, 3)

static const flatbuffers_voffset_t __EVP_SDK_MessageReceived_required[] = { 0, 1, 0 };
typedef flatbuffers_ref_t EVP_SDK_MessageReceived_ref_t;
static EVP_SDK_MessageReceived_ref_t EVP_SDK_MessageReceived_clone(flatbuffers_builder_t *B, EVP_SDK_MessageReceived_table_t t);
__flatbuffers_build_table(flatbuffers_, EVP_SDK_MessageReceived, 2)

static const flatbuffers_voffset_t __EVP_SDK_TelemetryEntry_required[] = { 0, 1, 0 };
typedef flatbuffers_ref_t EVP_SDK_TelemetryEntry_ref_t;
static EVP_SDK_TelemetryEntry_ref_t EVP_SDK_TelemetryEntry_clone(flatbuffers_builder_t *B, EVP_SDK_TelemetryEntry_table_t t);
__flatbuffers_build_table(flatbuffers_, EVP_SDK_TelemetryEntry, 2)

static const flatbuffers_voffset_t __EVP_SDK_TelemetryInput_required[] = { 0 };
typedef flatbuffers_ref_t EVP_SDK_TelemetryInput_ref_t;
static EVP_SDK_TelemetryInput_ref_t EVP_SDK_TelemetryInput_clone(flatbuffers_builder_t *B, EVP_SDK_TelemetryInput_table_t t);
__flatbuffers_build_table(flatbuffers_, EVP_SDK_TelemetryInput, 3)

static const flatbuffers_voffset_t __EVP_SDK_TelemetryOutput_required[] = { 0 };
typedef flatbuffers_ref_t EVP_SDK_TelemetryOutput_ref_t;
static EVP_SDK_TelemetryOutput_ref_t EVP_SDK_TelemetryOutput_clone(flatbuffers_builder_t *B, EVP_SDK_TelemetryOutput_table_t t);
__flatbuffers_build_table(flatbuffers_, EVP_SDK_TelemetryOutput, 3)

static const flatbuffers_voffset_t __EVP_SDK_RpcRequest_required[] = { 1, 2, 0 };
typedef flatbuffers_ref_t EVP_SDK_RpcRequest_ref_t;
static EVP_SDK_RpcRequest_ref_t EVP_SDK_RpcRequest_clone(flatbuffers_builder_t *B, EVP_SDK_RpcRequest_table_t t);
__flatbuffers_build_table(flatbuffers_, EVP_SDK_RpcRequest, 3)

static const flatbuffers_voffset_t __EVP_SDK_RpcResponseInput_required[] = { 0 };
typedef flatbuffers_ref_t EVP_SDK_RpcResponseInput_ref_t;
static EVP_SDK_RpcResponseInput_ref_t EVP_SDK_RpcResponseInput_clone(flatbuffers_builder_t *B, EVP_SDK_RpcResponseInput_table_t t);
__flatbuffers_build_table(flatbuffers_, EVP_SDK_RpcResponseInput, 5)

static const flatbuffers_voffset_t __EVP_SDK_RpcResponseOutput_required[] = { 0 };
typedef flatbuffers_ref_t EVP_SDK_RpcResponseOutput_ref_t;
static EVP_SDK_RpcResponseOutput_ref_t EVP_SDK_RpcResponseOutput_clone(flatbuffers_builder_t *B, EVP_SDK_RpcResponseOutput_table_t t);
__flatbuffers_build_table(flatbuffers_, EVP_SDK_RpcResponseOutput, 3)

static const flatbuffers_voffset_t __EVP_SDK_Event_required[] = { 0 };
typedef flatbuffers_ref_t EVP_SDK_Event_ref_t;
static EVP_SDK_Event_ref_t EVP_SDK_Event_clone(flatbuffers_builder_t *B, EVP_SDK_Event_table_t t);
__flatbuffers_build_table(flatbuffers_, EVP_SDK_Event, 2)

static const flatbuffers_voffset_t __EVP_SDK_GetEvent_required[] = { 0 };
typedef flatbuffers_ref_t EVP_SDK_GetEvent_ref_t;
static EVP_SDK_GetEvent_ref_t EVP_SDK_GetEvent_clone(flatbuffers_builder_t *B, EVP_SDK_GetEvent_table_t t);
__flatbuffers_build_table(flatbuffers_, EVP_SDK_GetEvent, 2)

static const flatbuffers_voffset_t __EVP_SDK_RequestResendConfig_required[] = { 0 };
typedef flatbuffers_ref_t EVP_SDK_RequestResendConfig_ref_t;
static EVP_SDK_RequestResendConfig_ref_t EVP_SDK_RequestResendConfig_clone(flatbuffers_builder_t *B, EVP_SDK_RequestResendConfig_table_t t);
__flatbuffers_build_table(flatbuffers_, EVP_SDK_RequestResendConfig, 0)

static const flatbuffers_voffset_t __EVP_SDK_Request_required[] = { 1, 0 };
typedef flatbuffers_ref_t EVP_SDK_Request_ref_t;
static EVP_SDK_Request_ref_t EVP_SDK_Request_clone(flatbuffers_builder_t *B, EVP_SDK_Request_table_t t);
__flatbuffers_build_table(flatbuffers_, EVP_SDK_Request, 2)

static const flatbuffers_voffset_t __EVP_SDK_Simple_required[] = { 0 };
typedef flatbuffers_ref_t EVP_SDK_Simple_ref_t;
static EVP_SDK_Simple_ref_t EVP_SDK_Simple_clone(flatbuffers_builder_t *B, EVP_SDK_Simple_table_t t);
__flatbuffers_build_table(flatbuffers_, EVP_SDK_Simple, 1)

static const flatbuffers_voffset_t __EVP_SDK_Response_required[] = { 1, 0 };
typedef flatbuffers_ref_t EVP_SDK_Response_ref_t;
static EVP_SDK_Response_ref_t EVP_SDK_Response_clone(flatbuffers_builder_t *B, EVP_SDK_Response_table_t t);
__flatbuffers_build_table(flatbuffers_, EVP_SDK_Response, 2)

static const flatbuffers_voffset_t __EVP_SDK_StreamParamsRequest_required[] = { 0 };
typedef flatbuffers_ref_t EVP_SDK_StreamParamsRequest_ref_t;
static EVP_SDK_StreamParamsRequest_ref_t EVP_SDK_StreamParamsRequest_clone(flatbuffers_builder_t *B, EVP_SDK_StreamParamsRequest_table_t t);
__flatbuffers_build_table(flatbuffers_, EVP_SDK_StreamParamsRequest, 1)

static const flatbuffers_voffset_t __EVP_SDK_StreamNng_required[] = { 0 };
typedef flatbuffers_ref_t EVP_SDK_StreamNng_ref_t;
static EVP_SDK_StreamNng_ref_t EVP_SDK_StreamNng_clone(flatbuffers_builder_t *B, EVP_SDK_StreamNng_table_t t);
__flatbuffers_build_table(flatbuffers_, EVP_SDK_StreamNng, 3)

static const flatbuffers_voffset_t __EVP_SDK_StreamParamsResponse_required[] = { 0 };
typedef flatbuffers_ref_t EVP_SDK_StreamParamsResponse_ref_t;
static EVP_SDK_StreamParamsResponse_ref_t EVP_SDK_StreamParamsResponse_clone(flatbuffers_builder_t *B, EVP_SDK_StreamParamsResponse_table_t t);
__flatbuffers_build_table(flatbuffers_, EVP_SDK_StreamParamsResponse, 5)

#define __EVP_SDK_Config_formal_args , flatbuffers_string_ref_t v0, flatbuffers_uint8_vec_ref_t v1
#define __EVP_SDK_Config_call_args , v0, v1
static inline EVP_SDK_Config_ref_t EVP_SDK_Config_create(flatbuffers_builder_t *B __EVP_SDK_Config_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, EVP_SDK_Config, EVP_SDK_Config_file_identifier, EVP_SDK_Config_type_identifier)

#define __EVP_SDK_StateInput_formal_args , flatbuffers_string_ref_t v0, flatbuffers_uint8_vec_ref_t v1, uint64_t v2, uint64_t v3
#define __EVP_SDK_StateInput_call_args , v0, v1, v2, v3
static inline EVP_SDK_StateInput_ref_t EVP_SDK_StateInput_create(flatbuffers_builder_t *B __EVP_SDK_StateInput_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, EVP_SDK_StateInput, EVP_SDK_StateInput_file_identifier, EVP_SDK_StateInput_type_identifier)

#define __EVP_SDK_StateOutput_formal_args , uint64_t v0, uint32_t v1, uint64_t v2
#define __EVP_SDK_StateOutput_call_args , v0, v1, v2
static inline EVP_SDK_StateOutput_ref_t EVP_SDK_StateOutput_create(flatbuffers_builder_t *B __EVP_SDK_StateOutput_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, EVP_SDK_StateOutput, EVP_SDK_StateOutput_file_identifier, EVP_SDK_StateOutput_type_identifier)

#define __EVP_SDK_Exit_formal_args 
#define __EVP_SDK_Exit_call_args 
static inline EVP_SDK_Exit_ref_t EVP_SDK_Exit_create(flatbuffers_builder_t *B __EVP_SDK_Exit_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, EVP_SDK_Exit, EVP_SDK_Exit_file_identifier, EVP_SDK_Exit_type_identifier)

#define __EVP_SDK_BlobRequestAzureBlob_formal_args , flatbuffers_string_ref_t v0
#define __EVP_SDK_BlobRequestAzureBlob_call_args , v0
static inline EVP_SDK_BlobRequestAzureBlob_ref_t EVP_SDK_BlobRequestAzureBlob_create(flatbuffers_builder_t *B __EVP_SDK_BlobRequestAzureBlob_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, EVP_SDK_BlobRequestAzureBlob, EVP_SDK_BlobRequestAzureBlob_file_identifier, EVP_SDK_BlobRequestAzureBlob_type_identifier)

#define __EVP_SDK_BlobRequestEvp_formal_args , flatbuffers_string_ref_t v0, flatbuffers_string_ref_t v1
#define __EVP_SDK_BlobRequestEvp_call_args , v0, v1
static inline EVP_SDK_BlobRequestEvp_ref_t EVP_SDK_BlobRequestEvp_create(flatbuffers_builder_t *B __EVP_SDK_BlobRequestEvp_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, EVP_SDK_BlobRequestEvp, EVP_SDK_BlobRequestEvp_file_identifier, EVP_SDK_BlobRequestEvp_type_identifier)

#define __EVP_SDK_BlobRequestHttp_formal_args , flatbuffers_string_ref_t v0
#define __EVP_SDK_BlobRequestHttp_call_args , v0
static inline EVP_SDK_BlobRequestHttp_ref_t EVP_SDK_BlobRequestHttp_create(flatbuffers_builder_t *B __EVP_SDK_BlobRequestHttp_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, EVP_SDK_BlobRequestHttp, EVP_SDK_BlobRequestHttp_file_identifier, EVP_SDK_BlobRequestHttp_type_identifier)

#define __EVP_SDK_BlobRequestHttpExt_formal_args , flatbuffers_string_ref_t v0, flatbuffers_string_vec_ref_t v1
#define __EVP_SDK_BlobRequestHttpExt_call_args , v0, v1
static inline EVP_SDK_BlobRequestHttpExt_ref_t EVP_SDK_BlobRequestHttpExt_create(flatbuffers_builder_t *B __EVP_SDK_BlobRequestHttpExt_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, EVP_SDK_BlobRequestHttpExt, EVP_SDK_BlobRequestHttpExt_file_identifier, EVP_SDK_BlobRequestHttpExt_type_identifier)

#define __EVP_SDK_BlobInput_formal_args ,\
  uint32_t v0, uint32_t v1, EVP_SDK_BlobRequestUnion_union_ref_t v3, flatbuffers_string_ref_t v4, uint64_t v5, uint64_t v6
#define __EVP_SDK_BlobInput_call_args ,\
  v0, v1, v3, v4, v5, v6
static inline EVP_SDK_BlobInput_ref_t EVP_SDK_BlobInput_create(flatbuffers_builder_t *B __EVP_SDK_BlobInput_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, EVP_SDK_BlobInput, EVP_SDK_BlobInput_file_identifier, EVP_SDK_BlobInput_type_identifier)

#define __EVP_SDK_BlobResultAzureBlob_formal_args , uint32_t v0, uint32_t v1, uint32_t v2
#define __EVP_SDK_BlobResultAzureBlob_call_args , v0, v1, v2
static inline EVP_SDK_BlobResultAzureBlob_ref_t EVP_SDK_BlobResultAzureBlob_create(flatbuffers_builder_t *B __EVP_SDK_BlobResultAzureBlob_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, EVP_SDK_BlobResultAzureBlob, EVP_SDK_BlobResultAzureBlob_file_identifier, EVP_SDK_BlobResultAzureBlob_type_identifier)

#define __EVP_SDK_BlobResultEvp_formal_args , uint32_t v0, uint32_t v1, uint32_t v2
#define __EVP_SDK_BlobResultEvp_call_args , v0, v1, v2
static inline EVP_SDK_BlobResultEvp_ref_t EVP_SDK_BlobResultEvp_create(flatbuffers_builder_t *B __EVP_SDK_BlobResultEvp_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, EVP_SDK_BlobResultEvp, EVP_SDK_BlobResultEvp_file_identifier, EVP_SDK_BlobResultEvp_type_identifier)

#define __EVP_SDK_BlobResultHttp_formal_args , uint32_t v0, uint32_t v1, uint32_t v2
#define __EVP_SDK_BlobResultHttp_call_args , v0, v1, v2
static inline EVP_SDK_BlobResultHttp_ref_t EVP_SDK_BlobResultHttp_create(flatbuffers_builder_t *B __EVP_SDK_BlobResultHttp_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, EVP_SDK_BlobResultHttp, EVP_SDK_BlobResultHttp_file_identifier, EVP_SDK_BlobResultHttp_type_identifier)

#define __EVP_SDK_BlobResultHttpExt_formal_args , uint32_t v0, uint32_t v1, uint32_t v2
#define __EVP_SDK_BlobResultHttpExt_call_args , v0, v1, v2
static inline EVP_SDK_BlobResultHttpExt_ref_t EVP_SDK_BlobResultHttpExt_create(flatbuffers_builder_t *B __EVP_SDK_BlobResultHttpExt_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, EVP_SDK_BlobResultHttpExt, EVP_SDK_BlobResultHttpExt_file_identifier, EVP_SDK_BlobResultHttpExt_type_identifier)

#define __EVP_SDK_BlobOutput_formal_args , EVP_SDK_BlobResultUnion_union_ref_t v1, uint64_t v2, uint32_t v3, uint64_t v4
#define __EVP_SDK_BlobOutput_call_args , v1, v2, v3, v4
static inline EVP_SDK_BlobOutput_ref_t EVP_SDK_BlobOutput_create(flatbuffers_builder_t *B __EVP_SDK_BlobOutput_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, EVP_SDK_BlobOutput, EVP_SDK_BlobOutput_file_identifier, EVP_SDK_BlobOutput_type_identifier)

#define __EVP_SDK_MessageSentInput_formal_args , flatbuffers_string_ref_t v0, flatbuffers_uint8_vec_ref_t v1, uint64_t v2, uint64_t v3
#define __EVP_SDK_MessageSentInput_call_args , v0, v1, v2, v3
static inline EVP_SDK_MessageSentInput_ref_t EVP_SDK_MessageSentInput_create(flatbuffers_builder_t *B __EVP_SDK_MessageSentInput_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, EVP_SDK_MessageSentInput, EVP_SDK_MessageSentInput_file_identifier, EVP_SDK_MessageSentInput_type_identifier)

#define __EVP_SDK_MessageSentOutput_formal_args , uint64_t v0, uint32_t v1, uint64_t v2
#define __EVP_SDK_MessageSentOutput_call_args , v0, v1, v2
static inline EVP_SDK_MessageSentOutput_ref_t EVP_SDK_MessageSentOutput_create(flatbuffers_builder_t *B __EVP_SDK_MessageSentOutput_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, EVP_SDK_MessageSentOutput, EVP_SDK_MessageSentOutput_file_identifier, EVP_SDK_MessageSentOutput_type_identifier)

#define __EVP_SDK_MessageReceived_formal_args , flatbuffers_string_ref_t v0, flatbuffers_uint8_vec_ref_t v1
#define __EVP_SDK_MessageReceived_call_args , v0, v1
static inline EVP_SDK_MessageReceived_ref_t EVP_SDK_MessageReceived_create(flatbuffers_builder_t *B __EVP_SDK_MessageReceived_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, EVP_SDK_MessageReceived, EVP_SDK_MessageReceived_file_identifier, EVP_SDK_MessageReceived_type_identifier)

#define __EVP_SDK_TelemetryEntry_formal_args , flatbuffers_string_ref_t v0, flatbuffers_string_ref_t v1
#define __EVP_SDK_TelemetryEntry_call_args , v0, v1
static inline EVP_SDK_TelemetryEntry_ref_t EVP_SDK_TelemetryEntry_create(flatbuffers_builder_t *B __EVP_SDK_TelemetryEntry_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, EVP_SDK_TelemetryEntry, EVP_SDK_TelemetryEntry_file_identifier, EVP_SDK_TelemetryEntry_type_identifier)

#define __EVP_SDK_TelemetryInput_formal_args , EVP_SDK_TelemetryEntry_vec_ref_t v0, uint64_t v1, uint64_t v2
#define __EVP_SDK_TelemetryInput_call_args , v0, v1, v2
static inline EVP_SDK_TelemetryInput_ref_t EVP_SDK_TelemetryInput_create(flatbuffers_builder_t *B __EVP_SDK_TelemetryInput_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, EVP_SDK_TelemetryInput, EVP_SDK_TelemetryInput_file_identifier, EVP_SDK_TelemetryInput_type_identifier)

#define __EVP_SDK_TelemetryOutput_formal_args , uint64_t v0, uint32_t v1, uint64_t v2
#define __EVP_SDK_TelemetryOutput_call_args , v0, v1, v2
static inline EVP_SDK_TelemetryOutput_ref_t EVP_SDK_TelemetryOutput_create(flatbuffers_builder_t *B __EVP_SDK_TelemetryOutput_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, EVP_SDK_TelemetryOutput, EVP_SDK_TelemetryOutput_file_identifier, EVP_SDK_TelemetryOutput_type_identifier)

#define __EVP_SDK_RpcRequest_formal_args , uint64_t v0, flatbuffers_string_ref_t v1, flatbuffers_string_ref_t v2
#define __EVP_SDK_RpcRequest_call_args , v0, v1, v2
static inline EVP_SDK_RpcRequest_ref_t EVP_SDK_RpcRequest_create(flatbuffers_builder_t *B __EVP_SDK_RpcRequest_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, EVP_SDK_RpcRequest, EVP_SDK_RpcRequest_file_identifier, EVP_SDK_RpcRequest_type_identifier)

#define __EVP_SDK_RpcResponseInput_formal_args ,\
  uint64_t v0, flatbuffers_string_ref_t v1, uint32_t v2, uint64_t v3, uint64_t v4
#define __EVP_SDK_RpcResponseInput_call_args ,\
  v0, v1, v2, v3, v4
static inline EVP_SDK_RpcResponseInput_ref_t EVP_SDK_RpcResponseInput_create(flatbuffers_builder_t *B __EVP_SDK_RpcResponseInput_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, EVP_SDK_RpcResponseInput, EVP_SDK_RpcResponseInput_file_identifier, EVP_SDK_RpcResponseInput_type_identifier)

#define __EVP_SDK_RpcResponseOutput_formal_args , uint64_t v0, uint32_t v1, uint64_t v2
#define __EVP_SDK_RpcResponseOutput_call_args , v0, v1, v2
static inline EVP_SDK_RpcResponseOutput_ref_t EVP_SDK_RpcResponseOutput_create(flatbuffers_builder_t *B __EVP_SDK_RpcResponseOutput_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, EVP_SDK_RpcResponseOutput, EVP_SDK_RpcResponseOutput_file_identifier, EVP_SDK_RpcResponseOutput_type_identifier)

#define __EVP_SDK_Event_formal_args , EVP_SDK_EventBody_union_ref_t v1
#define __EVP_SDK_Event_call_args , v1
static inline EVP_SDK_Event_ref_t EVP_SDK_Event_create(flatbuffers_builder_t *B __EVP_SDK_Event_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, EVP_SDK_Event, EVP_SDK_Event_file_identifier, EVP_SDK_Event_type_identifier)

#define __EVP_SDK_GetEvent_formal_args , uint64_t v0, uint64_t v1
#define __EVP_SDK_GetEvent_call_args , v0, v1
static inline EVP_SDK_GetEvent_ref_t EVP_SDK_GetEvent_create(flatbuffers_builder_t *B __EVP_SDK_GetEvent_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, EVP_SDK_GetEvent, EVP_SDK_GetEvent_file_identifier, EVP_SDK_GetEvent_type_identifier)

#define __EVP_SDK_RequestResendConfig_formal_args 
#define __EVP_SDK_RequestResendConfig_call_args 
static inline EVP_SDK_RequestResendConfig_ref_t EVP_SDK_RequestResendConfig_create(flatbuffers_builder_t *B __EVP_SDK_RequestResendConfig_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, EVP_SDK_RequestResendConfig, EVP_SDK_RequestResendConfig_file_identifier, EVP_SDK_RequestResendConfig_type_identifier)

#define __EVP_SDK_Request_formal_args , EVP_SDK_RequestUnion_union_ref_t v1
#define __EVP_SDK_Request_call_args , v1
static inline EVP_SDK_Request_ref_t EVP_SDK_Request_create(flatbuffers_builder_t *B __EVP_SDK_Request_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, EVP_SDK_Request, EVP_SDK_Request_file_identifier, EVP_SDK_Request_type_identifier)

#define __EVP_SDK_Simple_formal_args , uint32_t v0
#define __EVP_SDK_Simple_call_args , v0
static inline EVP_SDK_Simple_ref_t EVP_SDK_Simple_create(flatbuffers_builder_t *B __EVP_SDK_Simple_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, EVP_SDK_Simple, EVP_SDK_Simple_file_identifier, EVP_SDK_Simple_type_identifier)

#define __EVP_SDK_Response_formal_args , EVP_SDK_ResponseUnion_union_ref_t v1
#define __EVP_SDK_Response_call_args , v1
static inline EVP_SDK_Response_ref_t EVP_SDK_Response_create(flatbuffers_builder_t *B __EVP_SDK_Response_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, EVP_SDK_Response, EVP_SDK_Response_file_identifier, EVP_SDK_Response_type_identifier)

#define __EVP_SDK_StreamParamsRequest_formal_args , flatbuffers_string_ref_t v0
#define __EVP_SDK_StreamParamsRequest_call_args , v0
static inline EVP_SDK_StreamParamsRequest_ref_t EVP_SDK_StreamParamsRequest_create(flatbuffers_builder_t *B __EVP_SDK_StreamParamsRequest_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, EVP_SDK_StreamParamsRequest, EVP_SDK_StreamParamsRequest_file_identifier, EVP_SDK_StreamParamsRequest_type_identifier)

#define __EVP_SDK_StreamNng_formal_args , EVP_SDK_StreamNngMode_enum_t v0, EVP_SDK_StreamNngProtocol_enum_t v1, flatbuffers_string_ref_t v2
#define __EVP_SDK_StreamNng_call_args , v0, v1, v2
static inline EVP_SDK_StreamNng_ref_t EVP_SDK_StreamNng_create(flatbuffers_builder_t *B __EVP_SDK_StreamNng_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, EVP_SDK_StreamNng, EVP_SDK_StreamNng_file_identifier, EVP_SDK_StreamNng_type_identifier)

#define __EVP_SDK_StreamParamsResponse_formal_args , uint32_t v0, EVP_SDK_StreamType_enum_t v1, EVP_SDK_StreamDirection_enum_t v2, EVP_SDK_StreamParams_union_ref_t v4
#define __EVP_SDK_StreamParamsResponse_call_args , v0, v1, v2, v4
static inline EVP_SDK_StreamParamsResponse_ref_t EVP_SDK_StreamParamsResponse_create(flatbuffers_builder_t *B __EVP_SDK_StreamParamsResponse_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, EVP_SDK_StreamParamsResponse, EVP_SDK_StreamParamsResponse_file_identifier, EVP_SDK_StreamParamsResponse_type_identifier)

static inline EVP_SDK_BlobRequestUnion_union_ref_t EVP_SDK_BlobRequestUnion_as_NONE(void)
{ EVP_SDK_BlobRequestUnion_union_ref_t uref; uref.type = EVP_SDK_BlobRequestUnion_NONE; uref.value = 0; return uref; }
static inline EVP_SDK_BlobRequestUnion_union_ref_t EVP_SDK_BlobRequestUnion_as_azureBlob(EVP_SDK_BlobRequestAzureBlob_ref_t ref)
{ EVP_SDK_BlobRequestUnion_union_ref_t uref; uref.type = EVP_SDK_BlobRequestUnion_azureBlob; uref.value = ref; return uref; }
static inline EVP_SDK_BlobRequestUnion_union_ref_t EVP_SDK_BlobRequestUnion_as_evp(EVP_SDK_BlobRequestEvp_ref_t ref)
{ EVP_SDK_BlobRequestUnion_union_ref_t uref; uref.type = EVP_SDK_BlobRequestUnion_evp; uref.value = ref; return uref; }
static inline EVP_SDK_BlobRequestUnion_union_ref_t EVP_SDK_BlobRequestUnion_as_http(EVP_SDK_BlobRequestHttp_ref_t ref)
{ EVP_SDK_BlobRequestUnion_union_ref_t uref; uref.type = EVP_SDK_BlobRequestUnion_http; uref.value = ref; return uref; }
static inline EVP_SDK_BlobRequestUnion_union_ref_t EVP_SDK_BlobRequestUnion_as_http_ext(EVP_SDK_BlobRequestHttpExt_ref_t ref)
{ EVP_SDK_BlobRequestUnion_union_ref_t uref; uref.type = EVP_SDK_BlobRequestUnion_http_ext; uref.value = ref; return uref; }
__flatbuffers_build_union_vector(flatbuffers_, EVP_SDK_BlobRequestUnion)

static EVP_SDK_BlobRequestUnion_union_ref_t EVP_SDK_BlobRequestUnion_clone(flatbuffers_builder_t *B, EVP_SDK_BlobRequestUnion_union_t u)
{
    switch (u.type) {
    case 1: return EVP_SDK_BlobRequestUnion_as_azureBlob(EVP_SDK_BlobRequestAzureBlob_clone(B, (EVP_SDK_BlobRequestAzureBlob_table_t)u.value));
    case 2: return EVP_SDK_BlobRequestUnion_as_evp(EVP_SDK_BlobRequestEvp_clone(B, (EVP_SDK_BlobRequestEvp_table_t)u.value));
    case 3: return EVP_SDK_BlobRequestUnion_as_http(EVP_SDK_BlobRequestHttp_clone(B, (EVP_SDK_BlobRequestHttp_table_t)u.value));
    case 4: return EVP_SDK_BlobRequestUnion_as_http_ext(EVP_SDK_BlobRequestHttpExt_clone(B, (EVP_SDK_BlobRequestHttpExt_table_t)u.value));
    default: return EVP_SDK_BlobRequestUnion_as_NONE();
    }
}

static inline EVP_SDK_BlobResultUnion_union_ref_t EVP_SDK_BlobResultUnion_as_NONE(void)
{ EVP_SDK_BlobResultUnion_union_ref_t uref; uref.type = EVP_SDK_BlobResultUnion_NONE; uref.value = 0; return uref; }
static inline EVP_SDK_BlobResultUnion_union_ref_t EVP_SDK_BlobResultUnion_as_azureBlob(EVP_SDK_BlobResultAzureBlob_ref_t ref)
{ EVP_SDK_BlobResultUnion_union_ref_t uref; uref.type = EVP_SDK_BlobResultUnion_azureBlob; uref.value = ref; return uref; }
static inline EVP_SDK_BlobResultUnion_union_ref_t EVP_SDK_BlobResultUnion_as_evp(EVP_SDK_BlobResultEvp_ref_t ref)
{ EVP_SDK_BlobResultUnion_union_ref_t uref; uref.type = EVP_SDK_BlobResultUnion_evp; uref.value = ref; return uref; }
static inline EVP_SDK_BlobResultUnion_union_ref_t EVP_SDK_BlobResultUnion_as_http(EVP_SDK_BlobResultHttp_ref_t ref)
{ EVP_SDK_BlobResultUnion_union_ref_t uref; uref.type = EVP_SDK_BlobResultUnion_http; uref.value = ref; return uref; }
static inline EVP_SDK_BlobResultUnion_union_ref_t EVP_SDK_BlobResultUnion_as_http_ext(EVP_SDK_BlobResultHttpExt_ref_t ref)
{ EVP_SDK_BlobResultUnion_union_ref_t uref; uref.type = EVP_SDK_BlobResultUnion_http_ext; uref.value = ref; return uref; }
__flatbuffers_build_union_vector(flatbuffers_, EVP_SDK_BlobResultUnion)

static EVP_SDK_BlobResultUnion_union_ref_t EVP_SDK_BlobResultUnion_clone(flatbuffers_builder_t *B, EVP_SDK_BlobResultUnion_union_t u)
{
    switch (u.type) {
    case 1: return EVP_SDK_BlobResultUnion_as_azureBlob(EVP_SDK_BlobResultAzureBlob_clone(B, (EVP_SDK_BlobResultAzureBlob_table_t)u.value));
    case 2: return EVP_SDK_BlobResultUnion_as_evp(EVP_SDK_BlobResultEvp_clone(B, (EVP_SDK_BlobResultEvp_table_t)u.value));
    case 3: return EVP_SDK_BlobResultUnion_as_http(EVP_SDK_BlobResultHttp_clone(B, (EVP_SDK_BlobResultHttp_table_t)u.value));
    case 4: return EVP_SDK_BlobResultUnion_as_http_ext(EVP_SDK_BlobResultHttpExt_clone(B, (EVP_SDK_BlobResultHttpExt_table_t)u.value));
    default: return EVP_SDK_BlobResultUnion_as_NONE();
    }
}

static inline EVP_SDK_EventBody_union_ref_t EVP_SDK_EventBody_as_NONE(void)
{ EVP_SDK_EventBody_union_ref_t uref; uref.type = EVP_SDK_EventBody_NONE; uref.value = 0; return uref; }
static inline EVP_SDK_EventBody_union_ref_t EVP_SDK_EventBody_as_config(EVP_SDK_Config_ref_t ref)
{ EVP_SDK_EventBody_union_ref_t uref; uref.type = EVP_SDK_EventBody_config; uref.value = ref; return uref; }
static inline EVP_SDK_EventBody_union_ref_t EVP_SDK_EventBody_as_state(EVP_SDK_StateOutput_ref_t ref)
{ EVP_SDK_EventBody_union_ref_t uref; uref.type = EVP_SDK_EventBody_state; uref.value = ref; return uref; }
static inline EVP_SDK_EventBody_union_ref_t EVP_SDK_EventBody_as_exit(EVP_SDK_Exit_ref_t ref)
{ EVP_SDK_EventBody_union_ref_t uref; uref.type = EVP_SDK_EventBody_exit; uref.value = ref; return uref; }
static inline EVP_SDK_EventBody_union_ref_t EVP_SDK_EventBody_as_blob(EVP_SDK_BlobOutput_ref_t ref)
{ EVP_SDK_EventBody_union_ref_t uref; uref.type = EVP_SDK_EventBody_blob; uref.value = ref; return uref; }
static inline EVP_SDK_EventBody_union_ref_t EVP_SDK_EventBody_as_messageSent(EVP_SDK_MessageSentOutput_ref_t ref)
{ EVP_SDK_EventBody_union_ref_t uref; uref.type = EVP_SDK_EventBody_messageSent; uref.value = ref; return uref; }
static inline EVP_SDK_EventBody_union_ref_t EVP_SDK_EventBody_as_messageReceived(EVP_SDK_MessageReceived_ref_t ref)
{ EVP_SDK_EventBody_union_ref_t uref; uref.type = EVP_SDK_EventBody_messageReceived; uref.value = ref; return uref; }
static inline EVP_SDK_EventBody_union_ref_t EVP_SDK_EventBody_as_telemetry(EVP_SDK_TelemetryOutput_ref_t ref)
{ EVP_SDK_EventBody_union_ref_t uref; uref.type = EVP_SDK_EventBody_telemetry; uref.value = ref; return uref; }
static inline EVP_SDK_EventBody_union_ref_t EVP_SDK_EventBody_as_rpcRequest(EVP_SDK_RpcRequest_ref_t ref)
{ EVP_SDK_EventBody_union_ref_t uref; uref.type = EVP_SDK_EventBody_rpcRequest; uref.value = ref; return uref; }
static inline EVP_SDK_EventBody_union_ref_t EVP_SDK_EventBody_as_rpcResponse(EVP_SDK_RpcResponseOutput_ref_t ref)
{ EVP_SDK_EventBody_union_ref_t uref; uref.type = EVP_SDK_EventBody_rpcResponse; uref.value = ref; return uref; }
__flatbuffers_build_union_vector(flatbuffers_, EVP_SDK_EventBody)

static EVP_SDK_EventBody_union_ref_t EVP_SDK_EventBody_clone(flatbuffers_builder_t *B, EVP_SDK_EventBody_union_t u)
{
    switch (u.type) {
    case 1: return EVP_SDK_EventBody_as_config(EVP_SDK_Config_clone(B, (EVP_SDK_Config_table_t)u.value));
    case 2: return EVP_SDK_EventBody_as_state(EVP_SDK_StateOutput_clone(B, (EVP_SDK_StateOutput_table_t)u.value));
    case 3: return EVP_SDK_EventBody_as_exit(EVP_SDK_Exit_clone(B, (EVP_SDK_Exit_table_t)u.value));
    case 4: return EVP_SDK_EventBody_as_blob(EVP_SDK_BlobOutput_clone(B, (EVP_SDK_BlobOutput_table_t)u.value));
    case 5: return EVP_SDK_EventBody_as_messageSent(EVP_SDK_MessageSentOutput_clone(B, (EVP_SDK_MessageSentOutput_table_t)u.value));
    case 6: return EVP_SDK_EventBody_as_messageReceived(EVP_SDK_MessageReceived_clone(B, (EVP_SDK_MessageReceived_table_t)u.value));
    case 7: return EVP_SDK_EventBody_as_telemetry(EVP_SDK_TelemetryOutput_clone(B, (EVP_SDK_TelemetryOutput_table_t)u.value));
    case 8: return EVP_SDK_EventBody_as_rpcRequest(EVP_SDK_RpcRequest_clone(B, (EVP_SDK_RpcRequest_table_t)u.value));
    case 9: return EVP_SDK_EventBody_as_rpcResponse(EVP_SDK_RpcResponseOutput_clone(B, (EVP_SDK_RpcResponseOutput_table_t)u.value));
    default: return EVP_SDK_EventBody_as_NONE();
    }
}

static inline EVP_SDK_RequestUnion_union_ref_t EVP_SDK_RequestUnion_as_NONE(void)
{ EVP_SDK_RequestUnion_union_ref_t uref; uref.type = EVP_SDK_RequestUnion_NONE; uref.value = 0; return uref; }
static inline EVP_SDK_RequestUnion_union_ref_t EVP_SDK_RequestUnion_as_getEvent(EVP_SDK_GetEvent_ref_t ref)
{ EVP_SDK_RequestUnion_union_ref_t uref; uref.type = EVP_SDK_RequestUnion_getEvent; uref.value = ref; return uref; }
static inline EVP_SDK_RequestUnion_union_ref_t EVP_SDK_RequestUnion_as_sendState(EVP_SDK_StateInput_ref_t ref)
{ EVP_SDK_RequestUnion_union_ref_t uref; uref.type = EVP_SDK_RequestUnion_sendState; uref.value = ref; return uref; }
static inline EVP_SDK_RequestUnion_union_ref_t EVP_SDK_RequestUnion_as_requestResendConfig(EVP_SDK_RequestResendConfig_ref_t ref)
{ EVP_SDK_RequestUnion_union_ref_t uref; uref.type = EVP_SDK_RequestUnion_requestResendConfig; uref.value = ref; return uref; }
static inline EVP_SDK_RequestUnion_union_ref_t EVP_SDK_RequestUnion_as_blobOperation(EVP_SDK_BlobInput_ref_t ref)
{ EVP_SDK_RequestUnion_union_ref_t uref; uref.type = EVP_SDK_RequestUnion_blobOperation; uref.value = ref; return uref; }
static inline EVP_SDK_RequestUnion_union_ref_t EVP_SDK_RequestUnion_as_sendTelemetry(EVP_SDK_TelemetryInput_ref_t ref)
{ EVP_SDK_RequestUnion_union_ref_t uref; uref.type = EVP_SDK_RequestUnion_sendTelemetry; uref.value = ref; return uref; }
static inline EVP_SDK_RequestUnion_union_ref_t EVP_SDK_RequestUnion_as_sendMessage(EVP_SDK_MessageSentInput_ref_t ref)
{ EVP_SDK_RequestUnion_union_ref_t uref; uref.type = EVP_SDK_RequestUnion_sendMessage; uref.value = ref; return uref; }
static inline EVP_SDK_RequestUnion_union_ref_t EVP_SDK_RequestUnion_as_sendRpcResponse(EVP_SDK_RpcResponseInput_ref_t ref)
{ EVP_SDK_RequestUnion_union_ref_t uref; uref.type = EVP_SDK_RequestUnion_sendRpcResponse; uref.value = ref; return uref; }
static inline EVP_SDK_RequestUnion_union_ref_t EVP_SDK_RequestUnion_as_streamParamsRequest(EVP_SDK_StreamParamsRequest_ref_t ref)
{ EVP_SDK_RequestUnion_union_ref_t uref; uref.type = EVP_SDK_RequestUnion_streamParamsRequest; uref.value = ref; return uref; }
__flatbuffers_build_union_vector(flatbuffers_, EVP_SDK_RequestUnion)

static EVP_SDK_RequestUnion_union_ref_t EVP_SDK_RequestUnion_clone(flatbuffers_builder_t *B, EVP_SDK_RequestUnion_union_t u)
{
    switch (u.type) {
    case 1: return EVP_SDK_RequestUnion_as_getEvent(EVP_SDK_GetEvent_clone(B, (EVP_SDK_GetEvent_table_t)u.value));
    case 2: return EVP_SDK_RequestUnion_as_sendState(EVP_SDK_StateInput_clone(B, (EVP_SDK_StateInput_table_t)u.value));
    case 3: return EVP_SDK_RequestUnion_as_requestResendConfig(EVP_SDK_RequestResendConfig_clone(B, (EVP_SDK_RequestResendConfig_table_t)u.value));
    case 4: return EVP_SDK_RequestUnion_as_blobOperation(EVP_SDK_BlobInput_clone(B, (EVP_SDK_BlobInput_table_t)u.value));
    case 5: return EVP_SDK_RequestUnion_as_sendTelemetry(EVP_SDK_TelemetryInput_clone(B, (EVP_SDK_TelemetryInput_table_t)u.value));
    case 6: return EVP_SDK_RequestUnion_as_sendMessage(EVP_SDK_MessageSentInput_clone(B, (EVP_SDK_MessageSentInput_table_t)u.value));
    case 7: return EVP_SDK_RequestUnion_as_sendRpcResponse(EVP_SDK_RpcResponseInput_clone(B, (EVP_SDK_RpcResponseInput_table_t)u.value));
    case 8: return EVP_SDK_RequestUnion_as_streamParamsRequest(EVP_SDK_StreamParamsRequest_clone(B, (EVP_SDK_StreamParamsRequest_table_t)u.value));
    default: return EVP_SDK_RequestUnion_as_NONE();
    }
}

static inline EVP_SDK_ResponseUnion_union_ref_t EVP_SDK_ResponseUnion_as_NONE(void)
{ EVP_SDK_ResponseUnion_union_ref_t uref; uref.type = EVP_SDK_ResponseUnion_NONE; uref.value = 0; return uref; }
static inline EVP_SDK_ResponseUnion_union_ref_t EVP_SDK_ResponseUnion_as_getEvent(EVP_SDK_Event_ref_t ref)
{ EVP_SDK_ResponseUnion_union_ref_t uref; uref.type = EVP_SDK_ResponseUnion_getEvent; uref.value = ref; return uref; }
static inline EVP_SDK_ResponseUnion_union_ref_t EVP_SDK_ResponseUnion_as_simple(EVP_SDK_Simple_ref_t ref)
{ EVP_SDK_ResponseUnion_union_ref_t uref; uref.type = EVP_SDK_ResponseUnion_simple; uref.value = ref; return uref; }
static inline EVP_SDK_ResponseUnion_union_ref_t EVP_SDK_ResponseUnion_as_streamParamsResponse(EVP_SDK_StreamParamsResponse_ref_t ref)
{ EVP_SDK_ResponseUnion_union_ref_t uref; uref.type = EVP_SDK_ResponseUnion_streamParamsResponse; uref.value = ref; return uref; }
__flatbuffers_build_union_vector(flatbuffers_, EVP_SDK_ResponseUnion)

static EVP_SDK_ResponseUnion_union_ref_t EVP_SDK_ResponseUnion_clone(flatbuffers_builder_t *B, EVP_SDK_ResponseUnion_union_t u)
{
    switch (u.type) {
    case 1: return EVP_SDK_ResponseUnion_as_getEvent(EVP_SDK_Event_clone(B, (EVP_SDK_Event_table_t)u.value));
    case 2: return EVP_SDK_ResponseUnion_as_simple(EVP_SDK_Simple_clone(B, (EVP_SDK_Simple_table_t)u.value));
    case 3: return EVP_SDK_ResponseUnion_as_streamParamsResponse(EVP_SDK_StreamParamsResponse_clone(B, (EVP_SDK_StreamParamsResponse_table_t)u.value));
    default: return EVP_SDK_ResponseUnion_as_NONE();
    }
}

static inline EVP_SDK_StreamParams_union_ref_t EVP_SDK_StreamParams_as_NONE(void)
{ EVP_SDK_StreamParams_union_ref_t uref; uref.type = EVP_SDK_StreamParams_NONE; uref.value = 0; return uref; }
static inline EVP_SDK_StreamParams_union_ref_t EVP_SDK_StreamParams_as_nng(EVP_SDK_StreamNng_ref_t ref)
{ EVP_SDK_StreamParams_union_ref_t uref; uref.type = EVP_SDK_StreamParams_nng; uref.value = ref; return uref; }
__flatbuffers_build_union_vector(flatbuffers_, EVP_SDK_StreamParams)

static EVP_SDK_StreamParams_union_ref_t EVP_SDK_StreamParams_clone(flatbuffers_builder_t *B, EVP_SDK_StreamParams_union_t u)
{
    switch (u.type) {
    case 1: return EVP_SDK_StreamParams_as_nng(EVP_SDK_StreamNng_clone(B, (EVP_SDK_StreamNng_table_t)u.value));
    default: return EVP_SDK_StreamParams_as_NONE();
    }
}

__flatbuffers_build_string_field(0, flatbuffers_, EVP_SDK_Config_topic, EVP_SDK_Config)
__flatbuffers_build_vector_field(1, flatbuffers_, EVP_SDK_Config_blob, flatbuffers_uint8, uint8_t, EVP_SDK_Config)

static inline EVP_SDK_Config_ref_t EVP_SDK_Config_create(flatbuffers_builder_t *B __EVP_SDK_Config_formal_args)
{
    if (EVP_SDK_Config_start(B)
        || EVP_SDK_Config_topic_add(B, v0)
        || EVP_SDK_Config_blob_add(B, v1)) {
        return 0;
    }
    return EVP_SDK_Config_end(B);
}

static EVP_SDK_Config_ref_t EVP_SDK_Config_clone(flatbuffers_builder_t *B, EVP_SDK_Config_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (EVP_SDK_Config_start(B)
        || EVP_SDK_Config_topic_pick(B, t)
        || EVP_SDK_Config_blob_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, EVP_SDK_Config_end(B));
}

__flatbuffers_build_string_field(0, flatbuffers_, EVP_SDK_StateInput_topic, EVP_SDK_StateInput)
__flatbuffers_build_vector_field(1, flatbuffers_, EVP_SDK_StateInput_blob, flatbuffers_uint8, uint8_t, EVP_SDK_StateInput)
__flatbuffers_build_scalar_field(2, flatbuffers_, EVP_SDK_StateInput_cb, flatbuffers_uint64, uint64_t, 8, 8, UINT64_C(0), EVP_SDK_StateInput)
__flatbuffers_build_scalar_field(3, flatbuffers_, EVP_SDK_StateInput_cb_userdata, flatbuffers_uint64, uint64_t, 8, 8, UINT64_C(0), EVP_SDK_StateInput)

static inline EVP_SDK_StateInput_ref_t EVP_SDK_StateInput_create(flatbuffers_builder_t *B __EVP_SDK_StateInput_formal_args)
{
    if (EVP_SDK_StateInput_start(B)
        || EVP_SDK_StateInput_cb_add(B, v2)
        || EVP_SDK_StateInput_cb_userdata_add(B, v3)
        || EVP_SDK_StateInput_topic_add(B, v0)
        || EVP_SDK_StateInput_blob_add(B, v1)) {
        return 0;
    }
    return EVP_SDK_StateInput_end(B);
}

static EVP_SDK_StateInput_ref_t EVP_SDK_StateInput_clone(flatbuffers_builder_t *B, EVP_SDK_StateInput_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (EVP_SDK_StateInput_start(B)
        || EVP_SDK_StateInput_cb_pick(B, t)
        || EVP_SDK_StateInput_cb_userdata_pick(B, t)
        || EVP_SDK_StateInput_topic_pick(B, t)
        || EVP_SDK_StateInput_blob_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, EVP_SDK_StateInput_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, EVP_SDK_StateOutput_cb, flatbuffers_uint64, uint64_t, 8, 8, UINT64_C(0), EVP_SDK_StateOutput)
__flatbuffers_build_scalar_field(1, flatbuffers_, EVP_SDK_StateOutput_reason, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), EVP_SDK_StateOutput)
__flatbuffers_build_scalar_field(2, flatbuffers_, EVP_SDK_StateOutput_cb_userdata, flatbuffers_uint64, uint64_t, 8, 8, UINT64_C(0), EVP_SDK_StateOutput)

static inline EVP_SDK_StateOutput_ref_t EVP_SDK_StateOutput_create(flatbuffers_builder_t *B __EVP_SDK_StateOutput_formal_args)
{
    if (EVP_SDK_StateOutput_start(B)
        || EVP_SDK_StateOutput_cb_add(B, v0)
        || EVP_SDK_StateOutput_cb_userdata_add(B, v2)
        || EVP_SDK_StateOutput_reason_add(B, v1)) {
        return 0;
    }
    return EVP_SDK_StateOutput_end(B);
}

static EVP_SDK_StateOutput_ref_t EVP_SDK_StateOutput_clone(flatbuffers_builder_t *B, EVP_SDK_StateOutput_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (EVP_SDK_StateOutput_start(B)
        || EVP_SDK_StateOutput_cb_pick(B, t)
        || EVP_SDK_StateOutput_cb_userdata_pick(B, t)
        || EVP_SDK_StateOutput_reason_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, EVP_SDK_StateOutput_end(B));
}


static inline EVP_SDK_Exit_ref_t EVP_SDK_Exit_create(flatbuffers_builder_t *B __EVP_SDK_Exit_formal_args)
{
    if (EVP_SDK_Exit_start(B)) {
        return 0;
    }
    return EVP_SDK_Exit_end(B);
}

static EVP_SDK_Exit_ref_t EVP_SDK_Exit_clone(flatbuffers_builder_t *B, EVP_SDK_Exit_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (EVP_SDK_Exit_start(B)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, EVP_SDK_Exit_end(B));
}

__flatbuffers_build_string_field(0, flatbuffers_, EVP_SDK_BlobRequestAzureBlob_url, EVP_SDK_BlobRequestAzureBlob)

static inline EVP_SDK_BlobRequestAzureBlob_ref_t EVP_SDK_BlobRequestAzureBlob_create(flatbuffers_builder_t *B __EVP_SDK_BlobRequestAzureBlob_formal_args)
{
    if (EVP_SDK_BlobRequestAzureBlob_start(B)
        || EVP_SDK_BlobRequestAzureBlob_url_add(B, v0)) {
        return 0;
    }
    return EVP_SDK_BlobRequestAzureBlob_end(B);
}

static EVP_SDK_BlobRequestAzureBlob_ref_t EVP_SDK_BlobRequestAzureBlob_clone(flatbuffers_builder_t *B, EVP_SDK_BlobRequestAzureBlob_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (EVP_SDK_BlobRequestAzureBlob_start(B)
        || EVP_SDK_BlobRequestAzureBlob_url_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, EVP_SDK_BlobRequestAzureBlob_end(B));
}

__flatbuffers_build_string_field(0, flatbuffers_, EVP_SDK_BlobRequestEvp_remoteName, EVP_SDK_BlobRequestEvp)
__flatbuffers_build_string_field(1, flatbuffers_, EVP_SDK_BlobRequestEvp_storageName, EVP_SDK_BlobRequestEvp)

static inline EVP_SDK_BlobRequestEvp_ref_t EVP_SDK_BlobRequestEvp_create(flatbuffers_builder_t *B __EVP_SDK_BlobRequestEvp_formal_args)
{
    if (EVP_SDK_BlobRequestEvp_start(B)
        || EVP_SDK_BlobRequestEvp_remoteName_add(B, v0)
        || EVP_SDK_BlobRequestEvp_storageName_add(B, v1)) {
        return 0;
    }
    return EVP_SDK_BlobRequestEvp_end(B);
}

static EVP_SDK_BlobRequestEvp_ref_t EVP_SDK_BlobRequestEvp_clone(flatbuffers_builder_t *B, EVP_SDK_BlobRequestEvp_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (EVP_SDK_BlobRequestEvp_start(B)
        || EVP_SDK_BlobRequestEvp_remoteName_pick(B, t)
        || EVP_SDK_BlobRequestEvp_storageName_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, EVP_SDK_BlobRequestEvp_end(B));
}

__flatbuffers_build_string_field(0, flatbuffers_, EVP_SDK_BlobRequestHttp_url, EVP_SDK_BlobRequestHttp)

static inline EVP_SDK_BlobRequestHttp_ref_t EVP_SDK_BlobRequestHttp_create(flatbuffers_builder_t *B __EVP_SDK_BlobRequestHttp_formal_args)
{
    if (EVP_SDK_BlobRequestHttp_start(B)
        || EVP_SDK_BlobRequestHttp_url_add(B, v0)) {
        return 0;
    }
    return EVP_SDK_BlobRequestHttp_end(B);
}

static EVP_SDK_BlobRequestHttp_ref_t EVP_SDK_BlobRequestHttp_clone(flatbuffers_builder_t *B, EVP_SDK_BlobRequestHttp_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (EVP_SDK_BlobRequestHttp_start(B)
        || EVP_SDK_BlobRequestHttp_url_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, EVP_SDK_BlobRequestHttp_end(B));
}

__flatbuffers_build_string_field(0, flatbuffers_, EVP_SDK_BlobRequestHttpExt_url, EVP_SDK_BlobRequestHttpExt)
__flatbuffers_build_string_vector_field(1, flatbuffers_, EVP_SDK_BlobRequestHttpExt_headers, EVP_SDK_BlobRequestHttpExt)

static inline EVP_SDK_BlobRequestHttpExt_ref_t EVP_SDK_BlobRequestHttpExt_create(flatbuffers_builder_t *B __EVP_SDK_BlobRequestHttpExt_formal_args)
{
    if (EVP_SDK_BlobRequestHttpExt_start(B)
        || EVP_SDK_BlobRequestHttpExt_url_add(B, v0)
        || EVP_SDK_BlobRequestHttpExt_headers_add(B, v1)) {
        return 0;
    }
    return EVP_SDK_BlobRequestHttpExt_end(B);
}

static EVP_SDK_BlobRequestHttpExt_ref_t EVP_SDK_BlobRequestHttpExt_clone(flatbuffers_builder_t *B, EVP_SDK_BlobRequestHttpExt_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (EVP_SDK_BlobRequestHttpExt_start(B)
        || EVP_SDK_BlobRequestHttpExt_url_pick(B, t)
        || EVP_SDK_BlobRequestHttpExt_headers_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, EVP_SDK_BlobRequestHttpExt_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, EVP_SDK_BlobInput_type, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), EVP_SDK_BlobInput)
__flatbuffers_build_scalar_field(1, flatbuffers_, EVP_SDK_BlobInput_op, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), EVP_SDK_BlobInput)
__flatbuffers_build_union_field(3, flatbuffers_, EVP_SDK_BlobInput_request, EVP_SDK_BlobRequestUnion, EVP_SDK_BlobInput)
__flatbuffers_build_union_table_value_field(flatbuffers_, EVP_SDK_BlobInput_request, EVP_SDK_BlobRequestUnion, azureBlob, EVP_SDK_BlobRequestAzureBlob)
__flatbuffers_build_union_table_value_field(flatbuffers_, EVP_SDK_BlobInput_request, EVP_SDK_BlobRequestUnion, evp, EVP_SDK_BlobRequestEvp)
__flatbuffers_build_union_table_value_field(flatbuffers_, EVP_SDK_BlobInput_request, EVP_SDK_BlobRequestUnion, http, EVP_SDK_BlobRequestHttp)
__flatbuffers_build_union_table_value_field(flatbuffers_, EVP_SDK_BlobInput_request, EVP_SDK_BlobRequestUnion, http_ext, EVP_SDK_BlobRequestHttpExt)
__flatbuffers_build_string_field(4, flatbuffers_, EVP_SDK_BlobInput_filename, EVP_SDK_BlobInput)
__flatbuffers_build_scalar_field(5, flatbuffers_, EVP_SDK_BlobInput_cb, flatbuffers_uint64, uint64_t, 8, 8, UINT64_C(0), EVP_SDK_BlobInput)
__flatbuffers_build_scalar_field(6, flatbuffers_, EVP_SDK_BlobInput_cb_userdata, flatbuffers_uint64, uint64_t, 8, 8, UINT64_C(0), EVP_SDK_BlobInput)

static inline EVP_SDK_BlobInput_ref_t EVP_SDK_BlobInput_create(flatbuffers_builder_t *B __EVP_SDK_BlobInput_formal_args)
{
    if (EVP_SDK_BlobInput_start(B)
        || EVP_SDK_BlobInput_cb_add(B, v5)
        || EVP_SDK_BlobInput_cb_userdata_add(B, v6)
        || EVP_SDK_BlobInput_type_add(B, v0)
        || EVP_SDK_BlobInput_op_add(B, v1)
        || EVP_SDK_BlobInput_request_add_value(B, v3)
        || EVP_SDK_BlobInput_filename_add(B, v4)
        || EVP_SDK_BlobInput_request_add_type(B, v3.type)) {
        return 0;
    }
    return EVP_SDK_BlobInput_end(B);
}

static EVP_SDK_BlobInput_ref_t EVP_SDK_BlobInput_clone(flatbuffers_builder_t *B, EVP_SDK_BlobInput_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (EVP_SDK_BlobInput_start(B)
        || EVP_SDK_BlobInput_cb_pick(B, t)
        || EVP_SDK_BlobInput_cb_userdata_pick(B, t)
        || EVP_SDK_BlobInput_type_pick(B, t)
        || EVP_SDK_BlobInput_op_pick(B, t)
        || EVP_SDK_BlobInput_request_pick(B, t)
        || EVP_SDK_BlobInput_filename_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, EVP_SDK_BlobInput_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, EVP_SDK_BlobResultAzureBlob_result, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), EVP_SDK_BlobResultAzureBlob)
__flatbuffers_build_scalar_field(1, flatbuffers_, EVP_SDK_BlobResultAzureBlob_error, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), EVP_SDK_BlobResultAzureBlob)
__flatbuffers_build_scalar_field(2, flatbuffers_, EVP_SDK_BlobResultAzureBlob_http_status, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), EVP_SDK_BlobResultAzureBlob)

static inline EVP_SDK_BlobResultAzureBlob_ref_t EVP_SDK_BlobResultAzureBlob_create(flatbuffers_builder_t *B __EVP_SDK_BlobResultAzureBlob_formal_args)
{
    if (EVP_SDK_BlobResultAzureBlob_start(B)
        || EVP_SDK_BlobResultAzureBlob_result_add(B, v0)
        || EVP_SDK_BlobResultAzureBlob_error_add(B, v1)
        || EVP_SDK_BlobResultAzureBlob_http_status_add(B, v2)) {
        return 0;
    }
    return EVP_SDK_BlobResultAzureBlob_end(B);
}

static EVP_SDK_BlobResultAzureBlob_ref_t EVP_SDK_BlobResultAzureBlob_clone(flatbuffers_builder_t *B, EVP_SDK_BlobResultAzureBlob_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (EVP_SDK_BlobResultAzureBlob_start(B)
        || EVP_SDK_BlobResultAzureBlob_result_pick(B, t)
        || EVP_SDK_BlobResultAzureBlob_error_pick(B, t)
        || EVP_SDK_BlobResultAzureBlob_http_status_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, EVP_SDK_BlobResultAzureBlob_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, EVP_SDK_BlobResultEvp_result, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), EVP_SDK_BlobResultEvp)
__flatbuffers_build_scalar_field(1, flatbuffers_, EVP_SDK_BlobResultEvp_error, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), EVP_SDK_BlobResultEvp)
__flatbuffers_build_scalar_field(2, flatbuffers_, EVP_SDK_BlobResultEvp_http_status, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), EVP_SDK_BlobResultEvp)

static inline EVP_SDK_BlobResultEvp_ref_t EVP_SDK_BlobResultEvp_create(flatbuffers_builder_t *B __EVP_SDK_BlobResultEvp_formal_args)
{
    if (EVP_SDK_BlobResultEvp_start(B)
        || EVP_SDK_BlobResultEvp_result_add(B, v0)
        || EVP_SDK_BlobResultEvp_error_add(B, v1)
        || EVP_SDK_BlobResultEvp_http_status_add(B, v2)) {
        return 0;
    }
    return EVP_SDK_BlobResultEvp_end(B);
}

static EVP_SDK_BlobResultEvp_ref_t EVP_SDK_BlobResultEvp_clone(flatbuffers_builder_t *B, EVP_SDK_BlobResultEvp_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (EVP_SDK_BlobResultEvp_start(B)
        || EVP_SDK_BlobResultEvp_result_pick(B, t)
        || EVP_SDK_BlobResultEvp_error_pick(B, t)
        || EVP_SDK_BlobResultEvp_http_status_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, EVP_SDK_BlobResultEvp_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, EVP_SDK_BlobResultHttp_result, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), EVP_SDK_BlobResultHttp)
__flatbuffers_build_scalar_field(1, flatbuffers_, EVP_SDK_BlobResultHttp_error, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), EVP_SDK_BlobResultHttp)
__flatbuffers_build_scalar_field(2, flatbuffers_, EVP_SDK_BlobResultHttp_http_status, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), EVP_SDK_BlobResultHttp)

static inline EVP_SDK_BlobResultHttp_ref_t EVP_SDK_BlobResultHttp_create(flatbuffers_builder_t *B __EVP_SDK_BlobResultHttp_formal_args)
{
    if (EVP_SDK_BlobResultHttp_start(B)
        || EVP_SDK_BlobResultHttp_result_add(B, v0)
        || EVP_SDK_BlobResultHttp_error_add(B, v1)
        || EVP_SDK_BlobResultHttp_http_status_add(B, v2)) {
        return 0;
    }
    return EVP_SDK_BlobResultHttp_end(B);
}

static EVP_SDK_BlobResultHttp_ref_t EVP_SDK_BlobResultHttp_clone(flatbuffers_builder_t *B, EVP_SDK_BlobResultHttp_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (EVP_SDK_BlobResultHttp_start(B)
        || EVP_SDK_BlobResultHttp_result_pick(B, t)
        || EVP_SDK_BlobResultHttp_error_pick(B, t)
        || EVP_SDK_BlobResultHttp_http_status_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, EVP_SDK_BlobResultHttp_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, EVP_SDK_BlobResultHttpExt_result, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), EVP_SDK_BlobResultHttpExt)
__flatbuffers_build_scalar_field(1, flatbuffers_, EVP_SDK_BlobResultHttpExt_error, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), EVP_SDK_BlobResultHttpExt)
__flatbuffers_build_scalar_field(2, flatbuffers_, EVP_SDK_BlobResultHttpExt_http_status, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), EVP_SDK_BlobResultHttpExt)

static inline EVP_SDK_BlobResultHttpExt_ref_t EVP_SDK_BlobResultHttpExt_create(flatbuffers_builder_t *B __EVP_SDK_BlobResultHttpExt_formal_args)
{
    if (EVP_SDK_BlobResultHttpExt_start(B)
        || EVP_SDK_BlobResultHttpExt_result_add(B, v0)
        || EVP_SDK_BlobResultHttpExt_error_add(B, v1)
        || EVP_SDK_BlobResultHttpExt_http_status_add(B, v2)) {
        return 0;
    }
    return EVP_SDK_BlobResultHttpExt_end(B);
}

static EVP_SDK_BlobResultHttpExt_ref_t EVP_SDK_BlobResultHttpExt_clone(flatbuffers_builder_t *B, EVP_SDK_BlobResultHttpExt_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (EVP_SDK_BlobResultHttpExt_start(B)
        || EVP_SDK_BlobResultHttpExt_result_pick(B, t)
        || EVP_SDK_BlobResultHttpExt_error_pick(B, t)
        || EVP_SDK_BlobResultHttpExt_http_status_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, EVP_SDK_BlobResultHttpExt_end(B));
}

__flatbuffers_build_union_field(1, flatbuffers_, EVP_SDK_BlobOutput_result, EVP_SDK_BlobResultUnion, EVP_SDK_BlobOutput)
__flatbuffers_build_union_table_value_field(flatbuffers_, EVP_SDK_BlobOutput_result, EVP_SDK_BlobResultUnion, azureBlob, EVP_SDK_BlobResultAzureBlob)
__flatbuffers_build_union_table_value_field(flatbuffers_, EVP_SDK_BlobOutput_result, EVP_SDK_BlobResultUnion, evp, EVP_SDK_BlobResultEvp)
__flatbuffers_build_union_table_value_field(flatbuffers_, EVP_SDK_BlobOutput_result, EVP_SDK_BlobResultUnion, http, EVP_SDK_BlobResultHttp)
__flatbuffers_build_union_table_value_field(flatbuffers_, EVP_SDK_BlobOutput_result, EVP_SDK_BlobResultUnion, http_ext, EVP_SDK_BlobResultHttpExt)
__flatbuffers_build_scalar_field(2, flatbuffers_, EVP_SDK_BlobOutput_cb, flatbuffers_uint64, uint64_t, 8, 8, UINT64_C(0), EVP_SDK_BlobOutput)
__flatbuffers_build_scalar_field(3, flatbuffers_, EVP_SDK_BlobOutput_reason, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), EVP_SDK_BlobOutput)
__flatbuffers_build_scalar_field(4, flatbuffers_, EVP_SDK_BlobOutput_cb_userdata, flatbuffers_uint64, uint64_t, 8, 8, UINT64_C(0), EVP_SDK_BlobOutput)

static inline EVP_SDK_BlobOutput_ref_t EVP_SDK_BlobOutput_create(flatbuffers_builder_t *B __EVP_SDK_BlobOutput_formal_args)
{
    if (EVP_SDK_BlobOutput_start(B)
        || EVP_SDK_BlobOutput_cb_add(B, v2)
        || EVP_SDK_BlobOutput_cb_userdata_add(B, v4)
        || EVP_SDK_BlobOutput_result_add_value(B, v1)
        || EVP_SDK_BlobOutput_reason_add(B, v3)
        || EVP_SDK_BlobOutput_result_add_type(B, v1.type)) {
        return 0;
    }
    return EVP_SDK_BlobOutput_end(B);
}

static EVP_SDK_BlobOutput_ref_t EVP_SDK_BlobOutput_clone(flatbuffers_builder_t *B, EVP_SDK_BlobOutput_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (EVP_SDK_BlobOutput_start(B)
        || EVP_SDK_BlobOutput_cb_pick(B, t)
        || EVP_SDK_BlobOutput_cb_userdata_pick(B, t)
        || EVP_SDK_BlobOutput_result_pick(B, t)
        || EVP_SDK_BlobOutput_reason_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, EVP_SDK_BlobOutput_end(B));
}

__flatbuffers_build_string_field(0, flatbuffers_, EVP_SDK_MessageSentInput_topic, EVP_SDK_MessageSentInput)
__flatbuffers_build_vector_field(1, flatbuffers_, EVP_SDK_MessageSentInput_blob, flatbuffers_uint8, uint8_t, EVP_SDK_MessageSentInput)
__flatbuffers_build_scalar_field(2, flatbuffers_, EVP_SDK_MessageSentInput_cb, flatbuffers_uint64, uint64_t, 8, 8, UINT64_C(0), EVP_SDK_MessageSentInput)
__flatbuffers_build_scalar_field(3, flatbuffers_, EVP_SDK_MessageSentInput_cb_userdata, flatbuffers_uint64, uint64_t, 8, 8, UINT64_C(0), EVP_SDK_MessageSentInput)

static inline EVP_SDK_MessageSentInput_ref_t EVP_SDK_MessageSentInput_create(flatbuffers_builder_t *B __EVP_SDK_MessageSentInput_formal_args)
{
    if (EVP_SDK_MessageSentInput_start(B)
        || EVP_SDK_MessageSentInput_cb_add(B, v2)
        || EVP_SDK_MessageSentInput_cb_userdata_add(B, v3)
        || EVP_SDK_MessageSentInput_topic_add(B, v0)
        || EVP_SDK_MessageSentInput_blob_add(B, v1)) {
        return 0;
    }
    return EVP_SDK_MessageSentInput_end(B);
}

static EVP_SDK_MessageSentInput_ref_t EVP_SDK_MessageSentInput_clone(flatbuffers_builder_t *B, EVP_SDK_MessageSentInput_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (EVP_SDK_MessageSentInput_start(B)
        || EVP_SDK_MessageSentInput_cb_pick(B, t)
        || EVP_SDK_MessageSentInput_cb_userdata_pick(B, t)
        || EVP_SDK_MessageSentInput_topic_pick(B, t)
        || EVP_SDK_MessageSentInput_blob_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, EVP_SDK_MessageSentInput_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, EVP_SDK_MessageSentOutput_cb, flatbuffers_uint64, uint64_t, 8, 8, UINT64_C(0), EVP_SDK_MessageSentOutput)
__flatbuffers_build_scalar_field(1, flatbuffers_, EVP_SDK_MessageSentOutput_reason, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), EVP_SDK_MessageSentOutput)
__flatbuffers_build_scalar_field(2, flatbuffers_, EVP_SDK_MessageSentOutput_cb_userdata, flatbuffers_uint64, uint64_t, 8, 8, UINT64_C(0), EVP_SDK_MessageSentOutput)

static inline EVP_SDK_MessageSentOutput_ref_t EVP_SDK_MessageSentOutput_create(flatbuffers_builder_t *B __EVP_SDK_MessageSentOutput_formal_args)
{
    if (EVP_SDK_MessageSentOutput_start(B)
        || EVP_SDK_MessageSentOutput_cb_add(B, v0)
        || EVP_SDK_MessageSentOutput_cb_userdata_add(B, v2)
        || EVP_SDK_MessageSentOutput_reason_add(B, v1)) {
        return 0;
    }
    return EVP_SDK_MessageSentOutput_end(B);
}

static EVP_SDK_MessageSentOutput_ref_t EVP_SDK_MessageSentOutput_clone(flatbuffers_builder_t *B, EVP_SDK_MessageSentOutput_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (EVP_SDK_MessageSentOutput_start(B)
        || EVP_SDK_MessageSentOutput_cb_pick(B, t)
        || EVP_SDK_MessageSentOutput_cb_userdata_pick(B, t)
        || EVP_SDK_MessageSentOutput_reason_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, EVP_SDK_MessageSentOutput_end(B));
}

__flatbuffers_build_string_field(0, flatbuffers_, EVP_SDK_MessageReceived_topic, EVP_SDK_MessageReceived)
__flatbuffers_build_vector_field(1, flatbuffers_, EVP_SDK_MessageReceived_blob, flatbuffers_uint8, uint8_t, EVP_SDK_MessageReceived)

static inline EVP_SDK_MessageReceived_ref_t EVP_SDK_MessageReceived_create(flatbuffers_builder_t *B __EVP_SDK_MessageReceived_formal_args)
{
    if (EVP_SDK_MessageReceived_start(B)
        || EVP_SDK_MessageReceived_topic_add(B, v0)
        || EVP_SDK_MessageReceived_blob_add(B, v1)) {
        return 0;
    }
    return EVP_SDK_MessageReceived_end(B);
}

static EVP_SDK_MessageReceived_ref_t EVP_SDK_MessageReceived_clone(flatbuffers_builder_t *B, EVP_SDK_MessageReceived_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (EVP_SDK_MessageReceived_start(B)
        || EVP_SDK_MessageReceived_topic_pick(B, t)
        || EVP_SDK_MessageReceived_blob_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, EVP_SDK_MessageReceived_end(B));
}

__flatbuffers_build_string_field(0, flatbuffers_, EVP_SDK_TelemetryEntry_key, EVP_SDK_TelemetryEntry)
__flatbuffers_build_string_field(1, flatbuffers_, EVP_SDK_TelemetryEntry_value, EVP_SDK_TelemetryEntry)

static inline EVP_SDK_TelemetryEntry_ref_t EVP_SDK_TelemetryEntry_create(flatbuffers_builder_t *B __EVP_SDK_TelemetryEntry_formal_args)
{
    if (EVP_SDK_TelemetryEntry_start(B)
        || EVP_SDK_TelemetryEntry_key_add(B, v0)
        || EVP_SDK_TelemetryEntry_value_add(B, v1)) {
        return 0;
    }
    return EVP_SDK_TelemetryEntry_end(B);
}

static EVP_SDK_TelemetryEntry_ref_t EVP_SDK_TelemetryEntry_clone(flatbuffers_builder_t *B, EVP_SDK_TelemetryEntry_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (EVP_SDK_TelemetryEntry_start(B)
        || EVP_SDK_TelemetryEntry_key_pick(B, t)
        || EVP_SDK_TelemetryEntry_value_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, EVP_SDK_TelemetryEntry_end(B));
}

__flatbuffers_build_table_vector_field(0, flatbuffers_, EVP_SDK_TelemetryInput_entries, EVP_SDK_TelemetryEntry, EVP_SDK_TelemetryInput)
__flatbuffers_build_scalar_field(1, flatbuffers_, EVP_SDK_TelemetryInput_cb, flatbuffers_uint64, uint64_t, 8, 8, UINT64_C(0), EVP_SDK_TelemetryInput)
__flatbuffers_build_scalar_field(2, flatbuffers_, EVP_SDK_TelemetryInput_cb_userdata, flatbuffers_uint64, uint64_t, 8, 8, UINT64_C(0), EVP_SDK_TelemetryInput)

static inline EVP_SDK_TelemetryInput_ref_t EVP_SDK_TelemetryInput_create(flatbuffers_builder_t *B __EVP_SDK_TelemetryInput_formal_args)
{
    if (EVP_SDK_TelemetryInput_start(B)
        || EVP_SDK_TelemetryInput_cb_add(B, v1)
        || EVP_SDK_TelemetryInput_cb_userdata_add(B, v2)
        || EVP_SDK_TelemetryInput_entries_add(B, v0)) {
        return 0;
    }
    return EVP_SDK_TelemetryInput_end(B);
}

static EVP_SDK_TelemetryInput_ref_t EVP_SDK_TelemetryInput_clone(flatbuffers_builder_t *B, EVP_SDK_TelemetryInput_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (EVP_SDK_TelemetryInput_start(B)
        || EVP_SDK_TelemetryInput_cb_pick(B, t)
        || EVP_SDK_TelemetryInput_cb_userdata_pick(B, t)
        || EVP_SDK_TelemetryInput_entries_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, EVP_SDK_TelemetryInput_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, EVP_SDK_TelemetryOutput_cb, flatbuffers_uint64, uint64_t, 8, 8, UINT64_C(0), EVP_SDK_TelemetryOutput)
__flatbuffers_build_scalar_field(1, flatbuffers_, EVP_SDK_TelemetryOutput_reason, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), EVP_SDK_TelemetryOutput)
__flatbuffers_build_scalar_field(2, flatbuffers_, EVP_SDK_TelemetryOutput_cb_userdata, flatbuffers_uint64, uint64_t, 8, 8, UINT64_C(0), EVP_SDK_TelemetryOutput)

static inline EVP_SDK_TelemetryOutput_ref_t EVP_SDK_TelemetryOutput_create(flatbuffers_builder_t *B __EVP_SDK_TelemetryOutput_formal_args)
{
    if (EVP_SDK_TelemetryOutput_start(B)
        || EVP_SDK_TelemetryOutput_cb_add(B, v0)
        || EVP_SDK_TelemetryOutput_cb_userdata_add(B, v2)
        || EVP_SDK_TelemetryOutput_reason_add(B, v1)) {
        return 0;
    }
    return EVP_SDK_TelemetryOutput_end(B);
}

static EVP_SDK_TelemetryOutput_ref_t EVP_SDK_TelemetryOutput_clone(flatbuffers_builder_t *B, EVP_SDK_TelemetryOutput_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (EVP_SDK_TelemetryOutput_start(B)
        || EVP_SDK_TelemetryOutput_cb_pick(B, t)
        || EVP_SDK_TelemetryOutput_cb_userdata_pick(B, t)
        || EVP_SDK_TelemetryOutput_reason_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, EVP_SDK_TelemetryOutput_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, EVP_SDK_RpcRequest_id, flatbuffers_uint64, uint64_t, 8, 8, UINT64_C(0), EVP_SDK_RpcRequest)
__flatbuffers_build_string_field(1, flatbuffers_, EVP_SDK_RpcRequest_method, EVP_SDK_RpcRequest)
__flatbuffers_build_string_field(2, flatbuffers_, EVP_SDK_RpcRequest_params, EVP_SDK_RpcRequest)

static inline EVP_SDK_RpcRequest_ref_t EVP_SDK_RpcRequest_create(flatbuffers_builder_t *B __EVP_SDK_RpcRequest_formal_args)
{
    if (EVP_SDK_RpcRequest_start(B)
        || EVP_SDK_RpcRequest_id_add(B, v0)
        || EVP_SDK_RpcRequest_method_add(B, v1)
        || EVP_SDK_RpcRequest_params_add(B, v2)) {
        return 0;
    }
    return EVP_SDK_RpcRequest_end(B);
}

static EVP_SDK_RpcRequest_ref_t EVP_SDK_RpcRequest_clone(flatbuffers_builder_t *B, EVP_SDK_RpcRequest_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (EVP_SDK_RpcRequest_start(B)
        || EVP_SDK_RpcRequest_id_pick(B, t)
        || EVP_SDK_RpcRequest_method_pick(B, t)
        || EVP_SDK_RpcRequest_params_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, EVP_SDK_RpcRequest_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, EVP_SDK_RpcResponseInput_id, flatbuffers_uint64, uint64_t, 8, 8, UINT64_C(0), EVP_SDK_RpcResponseInput)
__flatbuffers_build_string_field(1, flatbuffers_, EVP_SDK_RpcResponseInput_response, EVP_SDK_RpcResponseInput)
__flatbuffers_build_scalar_field(2, flatbuffers_, EVP_SDK_RpcResponseInput_status, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), EVP_SDK_RpcResponseInput)
__flatbuffers_build_scalar_field(3, flatbuffers_, EVP_SDK_RpcResponseInput_cb, flatbuffers_uint64, uint64_t, 8, 8, UINT64_C(0), EVP_SDK_RpcResponseInput)
__flatbuffers_build_scalar_field(4, flatbuffers_, EVP_SDK_RpcResponseInput_cb_userdata, flatbuffers_uint64, uint64_t, 8, 8, UINT64_C(0), EVP_SDK_RpcResponseInput)

static inline EVP_SDK_RpcResponseInput_ref_t EVP_SDK_RpcResponseInput_create(flatbuffers_builder_t *B __EVP_SDK_RpcResponseInput_formal_args)
{
    if (EVP_SDK_RpcResponseInput_start(B)
        || EVP_SDK_RpcResponseInput_id_add(B, v0)
        || EVP_SDK_RpcResponseInput_cb_add(B, v3)
        || EVP_SDK_RpcResponseInput_cb_userdata_add(B, v4)
        || EVP_SDK_RpcResponseInput_response_add(B, v1)
        || EVP_SDK_RpcResponseInput_status_add(B, v2)) {
        return 0;
    }
    return EVP_SDK_RpcResponseInput_end(B);
}

static EVP_SDK_RpcResponseInput_ref_t EVP_SDK_RpcResponseInput_clone(flatbuffers_builder_t *B, EVP_SDK_RpcResponseInput_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (EVP_SDK_RpcResponseInput_start(B)
        || EVP_SDK_RpcResponseInput_id_pick(B, t)
        || EVP_SDK_RpcResponseInput_cb_pick(B, t)
        || EVP_SDK_RpcResponseInput_cb_userdata_pick(B, t)
        || EVP_SDK_RpcResponseInput_response_pick(B, t)
        || EVP_SDK_RpcResponseInput_status_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, EVP_SDK_RpcResponseInput_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, EVP_SDK_RpcResponseOutput_cb, flatbuffers_uint64, uint64_t, 8, 8, UINT64_C(0), EVP_SDK_RpcResponseOutput)
__flatbuffers_build_scalar_field(1, flatbuffers_, EVP_SDK_RpcResponseOutput_reason, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), EVP_SDK_RpcResponseOutput)
__flatbuffers_build_scalar_field(2, flatbuffers_, EVP_SDK_RpcResponseOutput_cb_userdata, flatbuffers_uint64, uint64_t, 8, 8, UINT64_C(0), EVP_SDK_RpcResponseOutput)

static inline EVP_SDK_RpcResponseOutput_ref_t EVP_SDK_RpcResponseOutput_create(flatbuffers_builder_t *B __EVP_SDK_RpcResponseOutput_formal_args)
{
    if (EVP_SDK_RpcResponseOutput_start(B)
        || EVP_SDK_RpcResponseOutput_cb_add(B, v0)
        || EVP_SDK_RpcResponseOutput_cb_userdata_add(B, v2)
        || EVP_SDK_RpcResponseOutput_reason_add(B, v1)) {
        return 0;
    }
    return EVP_SDK_RpcResponseOutput_end(B);
}

static EVP_SDK_RpcResponseOutput_ref_t EVP_SDK_RpcResponseOutput_clone(flatbuffers_builder_t *B, EVP_SDK_RpcResponseOutput_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (EVP_SDK_RpcResponseOutput_start(B)
        || EVP_SDK_RpcResponseOutput_cb_pick(B, t)
        || EVP_SDK_RpcResponseOutput_cb_userdata_pick(B, t)
        || EVP_SDK_RpcResponseOutput_reason_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, EVP_SDK_RpcResponseOutput_end(B));
}

__flatbuffers_build_union_field(1, flatbuffers_, EVP_SDK_Event_body, EVP_SDK_EventBody, EVP_SDK_Event)
__flatbuffers_build_union_table_value_field(flatbuffers_, EVP_SDK_Event_body, EVP_SDK_EventBody, config, EVP_SDK_Config)
__flatbuffers_build_union_table_value_field(flatbuffers_, EVP_SDK_Event_body, EVP_SDK_EventBody, state, EVP_SDK_StateOutput)
__flatbuffers_build_union_table_value_field(flatbuffers_, EVP_SDK_Event_body, EVP_SDK_EventBody, exit, EVP_SDK_Exit)
__flatbuffers_build_union_table_value_field(flatbuffers_, EVP_SDK_Event_body, EVP_SDK_EventBody, blob, EVP_SDK_BlobOutput)
__flatbuffers_build_union_table_value_field(flatbuffers_, EVP_SDK_Event_body, EVP_SDK_EventBody, messageSent, EVP_SDK_MessageSentOutput)
__flatbuffers_build_union_table_value_field(flatbuffers_, EVP_SDK_Event_body, EVP_SDK_EventBody, messageReceived, EVP_SDK_MessageReceived)
__flatbuffers_build_union_table_value_field(flatbuffers_, EVP_SDK_Event_body, EVP_SDK_EventBody, telemetry, EVP_SDK_TelemetryOutput)
__flatbuffers_build_union_table_value_field(flatbuffers_, EVP_SDK_Event_body, EVP_SDK_EventBody, rpcRequest, EVP_SDK_RpcRequest)
__flatbuffers_build_union_table_value_field(flatbuffers_, EVP_SDK_Event_body, EVP_SDK_EventBody, rpcResponse, EVP_SDK_RpcResponseOutput)

static inline EVP_SDK_Event_ref_t EVP_SDK_Event_create(flatbuffers_builder_t *B __EVP_SDK_Event_formal_args)
{
    if (EVP_SDK_Event_start(B)
        || EVP_SDK_Event_body_add_value(B, v1)
        || EVP_SDK_Event_body_add_type(B, v1.type)) {
        return 0;
    }
    return EVP_SDK_Event_end(B);
}

static EVP_SDK_Event_ref_t EVP_SDK_Event_clone(flatbuffers_builder_t *B, EVP_SDK_Event_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (EVP_SDK_Event_start(B)
        || EVP_SDK_Event_body_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, EVP_SDK_Event_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, EVP_SDK_GetEvent_timeout_sec, flatbuffers_uint64, uint64_t, 8, 8, UINT64_C(0), EVP_SDK_GetEvent)
__flatbuffers_build_scalar_field(1, flatbuffers_, EVP_SDK_GetEvent_timeout_nsec, flatbuffers_uint64, uint64_t, 8, 8, UINT64_C(0), EVP_SDK_GetEvent)

static inline EVP_SDK_GetEvent_ref_t EVP_SDK_GetEvent_create(flatbuffers_builder_t *B __EVP_SDK_GetEvent_formal_args)
{
    if (EVP_SDK_GetEvent_start(B)
        || EVP_SDK_GetEvent_timeout_sec_add(B, v0)
        || EVP_SDK_GetEvent_timeout_nsec_add(B, v1)) {
        return 0;
    }
    return EVP_SDK_GetEvent_end(B);
}

static EVP_SDK_GetEvent_ref_t EVP_SDK_GetEvent_clone(flatbuffers_builder_t *B, EVP_SDK_GetEvent_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (EVP_SDK_GetEvent_start(B)
        || EVP_SDK_GetEvent_timeout_sec_pick(B, t)
        || EVP_SDK_GetEvent_timeout_nsec_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, EVP_SDK_GetEvent_end(B));
}


static inline EVP_SDK_RequestResendConfig_ref_t EVP_SDK_RequestResendConfig_create(flatbuffers_builder_t *B __EVP_SDK_RequestResendConfig_formal_args)
{
    if (EVP_SDK_RequestResendConfig_start(B)) {
        return 0;
    }
    return EVP_SDK_RequestResendConfig_end(B);
}

static EVP_SDK_RequestResendConfig_ref_t EVP_SDK_RequestResendConfig_clone(flatbuffers_builder_t *B, EVP_SDK_RequestResendConfig_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (EVP_SDK_RequestResendConfig_start(B)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, EVP_SDK_RequestResendConfig_end(B));
}

__flatbuffers_build_union_field(1, flatbuffers_, EVP_SDK_Request_body, EVP_SDK_RequestUnion, EVP_SDK_Request)
__flatbuffers_build_union_table_value_field(flatbuffers_, EVP_SDK_Request_body, EVP_SDK_RequestUnion, getEvent, EVP_SDK_GetEvent)
__flatbuffers_build_union_table_value_field(flatbuffers_, EVP_SDK_Request_body, EVP_SDK_RequestUnion, sendState, EVP_SDK_StateInput)
__flatbuffers_build_union_table_value_field(flatbuffers_, EVP_SDK_Request_body, EVP_SDK_RequestUnion, requestResendConfig, EVP_SDK_RequestResendConfig)
__flatbuffers_build_union_table_value_field(flatbuffers_, EVP_SDK_Request_body, EVP_SDK_RequestUnion, blobOperation, EVP_SDK_BlobInput)
__flatbuffers_build_union_table_value_field(flatbuffers_, EVP_SDK_Request_body, EVP_SDK_RequestUnion, sendTelemetry, EVP_SDK_TelemetryInput)
__flatbuffers_build_union_table_value_field(flatbuffers_, EVP_SDK_Request_body, EVP_SDK_RequestUnion, sendMessage, EVP_SDK_MessageSentInput)
__flatbuffers_build_union_table_value_field(flatbuffers_, EVP_SDK_Request_body, EVP_SDK_RequestUnion, sendRpcResponse, EVP_SDK_RpcResponseInput)
__flatbuffers_build_union_table_value_field(flatbuffers_, EVP_SDK_Request_body, EVP_SDK_RequestUnion, streamParamsRequest, EVP_SDK_StreamParamsRequest)

static inline EVP_SDK_Request_ref_t EVP_SDK_Request_create(flatbuffers_builder_t *B __EVP_SDK_Request_formal_args)
{
    if (EVP_SDK_Request_start(B)
        || EVP_SDK_Request_body_add_value(B, v1)
        || EVP_SDK_Request_body_add_type(B, v1.type)) {
        return 0;
    }
    return EVP_SDK_Request_end(B);
}

static EVP_SDK_Request_ref_t EVP_SDK_Request_clone(flatbuffers_builder_t *B, EVP_SDK_Request_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (EVP_SDK_Request_start(B)
        || EVP_SDK_Request_body_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, EVP_SDK_Request_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, EVP_SDK_Simple_result, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), EVP_SDK_Simple)

static inline EVP_SDK_Simple_ref_t EVP_SDK_Simple_create(flatbuffers_builder_t *B __EVP_SDK_Simple_formal_args)
{
    if (EVP_SDK_Simple_start(B)
        || EVP_SDK_Simple_result_add(B, v0)) {
        return 0;
    }
    return EVP_SDK_Simple_end(B);
}

static EVP_SDK_Simple_ref_t EVP_SDK_Simple_clone(flatbuffers_builder_t *B, EVP_SDK_Simple_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (EVP_SDK_Simple_start(B)
        || EVP_SDK_Simple_result_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, EVP_SDK_Simple_end(B));
}

__flatbuffers_build_union_field(1, flatbuffers_, EVP_SDK_Response_body, EVP_SDK_ResponseUnion, EVP_SDK_Response)
__flatbuffers_build_union_table_value_field(flatbuffers_, EVP_SDK_Response_body, EVP_SDK_ResponseUnion, getEvent, EVP_SDK_Event)
__flatbuffers_build_union_table_value_field(flatbuffers_, EVP_SDK_Response_body, EVP_SDK_ResponseUnion, simple, EVP_SDK_Simple)
__flatbuffers_build_union_table_value_field(flatbuffers_, EVP_SDK_Response_body, EVP_SDK_ResponseUnion, streamParamsResponse, EVP_SDK_StreamParamsResponse)

static inline EVP_SDK_Response_ref_t EVP_SDK_Response_create(flatbuffers_builder_t *B __EVP_SDK_Response_formal_args)
{
    if (EVP_SDK_Response_start(B)
        || EVP_SDK_Response_body_add_value(B, v1)
        || EVP_SDK_Response_body_add_type(B, v1.type)) {
        return 0;
    }
    return EVP_SDK_Response_end(B);
}

static EVP_SDK_Response_ref_t EVP_SDK_Response_clone(flatbuffers_builder_t *B, EVP_SDK_Response_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (EVP_SDK_Response_start(B)
        || EVP_SDK_Response_body_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, EVP_SDK_Response_end(B));
}

__flatbuffers_build_string_field(0, flatbuffers_, EVP_SDK_StreamParamsRequest_name, EVP_SDK_StreamParamsRequest)

static inline EVP_SDK_StreamParamsRequest_ref_t EVP_SDK_StreamParamsRequest_create(flatbuffers_builder_t *B __EVP_SDK_StreamParamsRequest_formal_args)
{
    if (EVP_SDK_StreamParamsRequest_start(B)
        || EVP_SDK_StreamParamsRequest_name_add(B, v0)) {
        return 0;
    }
    return EVP_SDK_StreamParamsRequest_end(B);
}

static EVP_SDK_StreamParamsRequest_ref_t EVP_SDK_StreamParamsRequest_clone(flatbuffers_builder_t *B, EVP_SDK_StreamParamsRequest_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (EVP_SDK_StreamParamsRequest_start(B)
        || EVP_SDK_StreamParamsRequest_name_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, EVP_SDK_StreamParamsRequest_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, EVP_SDK_StreamNng_mode, EVP_SDK_StreamNngMode, EVP_SDK_StreamNngMode_enum_t, 1, 1, INT8_C(0), EVP_SDK_StreamNng)
__flatbuffers_build_scalar_field(1, flatbuffers_, EVP_SDK_StreamNng_protocol, EVP_SDK_StreamNngProtocol, EVP_SDK_StreamNngProtocol_enum_t, 1, 1, INT8_C(0), EVP_SDK_StreamNng)
__flatbuffers_build_string_field(2, flatbuffers_, EVP_SDK_StreamNng_connection, EVP_SDK_StreamNng)

static inline EVP_SDK_StreamNng_ref_t EVP_SDK_StreamNng_create(flatbuffers_builder_t *B __EVP_SDK_StreamNng_formal_args)
{
    if (EVP_SDK_StreamNng_start(B)
        || EVP_SDK_StreamNng_connection_add(B, v2)
        || EVP_SDK_StreamNng_mode_add(B, v0)
        || EVP_SDK_StreamNng_protocol_add(B, v1)) {
        return 0;
    }
    return EVP_SDK_StreamNng_end(B);
}

static EVP_SDK_StreamNng_ref_t EVP_SDK_StreamNng_clone(flatbuffers_builder_t *B, EVP_SDK_StreamNng_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (EVP_SDK_StreamNng_start(B)
        || EVP_SDK_StreamNng_connection_pick(B, t)
        || EVP_SDK_StreamNng_mode_pick(B, t)
        || EVP_SDK_StreamNng_protocol_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, EVP_SDK_StreamNng_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, EVP_SDK_StreamParamsResponse_result, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), EVP_SDK_StreamParamsResponse)
__flatbuffers_build_scalar_field(1, flatbuffers_, EVP_SDK_StreamParamsResponse_type, EVP_SDK_StreamType, EVP_SDK_StreamType_enum_t, 1, 1, INT8_C(0), EVP_SDK_StreamParamsResponse)
__flatbuffers_build_scalar_field(2, flatbuffers_, EVP_SDK_StreamParamsResponse_direction, EVP_SDK_StreamDirection, EVP_SDK_StreamDirection_enum_t, 1, 1, INT8_C(0), EVP_SDK_StreamParamsResponse)
__flatbuffers_build_union_field(4, flatbuffers_, EVP_SDK_StreamParamsResponse_params, EVP_SDK_StreamParams, EVP_SDK_StreamParamsResponse)
__flatbuffers_build_union_table_value_field(flatbuffers_, EVP_SDK_StreamParamsResponse_params, EVP_SDK_StreamParams, nng, EVP_SDK_StreamNng)

static inline EVP_SDK_StreamParamsResponse_ref_t EVP_SDK_StreamParamsResponse_create(flatbuffers_builder_t *B __EVP_SDK_StreamParamsResponse_formal_args)
{
    if (EVP_SDK_StreamParamsResponse_start(B)
        || EVP_SDK_StreamParamsResponse_result_add(B, v0)
        || EVP_SDK_StreamParamsResponse_params_add_value(B, v4)
        || EVP_SDK_StreamParamsResponse_type_add(B, v1)
        || EVP_SDK_StreamParamsResponse_direction_add(B, v2)
        || EVP_SDK_StreamParamsResponse_params_add_type(B, v4.type)) {
        return 0;
    }
    return EVP_SDK_StreamParamsResponse_end(B);
}

static EVP_SDK_StreamParamsResponse_ref_t EVP_SDK_StreamParamsResponse_clone(flatbuffers_builder_t *B, EVP_SDK_StreamParamsResponse_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (EVP_SDK_StreamParamsResponse_start(B)
        || EVP_SDK_StreamParamsResponse_result_pick(B, t)
        || EVP_SDK_StreamParamsResponse_params_pick(B, t)
        || EVP_SDK_StreamParamsResponse_type_pick(B, t)
        || EVP_SDK_StreamParamsResponse_direction_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, EVP_SDK_StreamParamsResponse_end(B));
}

#include "flatcc/flatcc_epilogue.h"
#endif /* SDK_BUILDER_H */
