/*
 * SPDX-FileCopyrightText: 2023-2024 Sony Semiconductor Solutions Corporation
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef SDK_VERIFIER_H
#define SDK_VERIFIER_H

/* Generated by flatcc 0.6.1 FlatBuffers schema compiler for C by dvide.com */

#ifndef SDK_READER_H
#include "sdk_reader.h"
#endif
#include "flatcc/flatcc_verifier.h"
#include "flatcc/flatcc_prologue.h"

static int EVP_SDK_Config_verify_table(flatcc_table_verifier_descriptor_t *td);
static int EVP_SDK_StateInput_verify_table(flatcc_table_verifier_descriptor_t *td);
static int EVP_SDK_StateOutput_verify_table(flatcc_table_verifier_descriptor_t *td);
static int EVP_SDK_Exit_verify_table(flatcc_table_verifier_descriptor_t *td);
static int EVP_SDK_BlobRequestAzureBlob_verify_table(flatcc_table_verifier_descriptor_t *td);
static int EVP_SDK_BlobRequestEvp_verify_table(flatcc_table_verifier_descriptor_t *td);
static int EVP_SDK_BlobRequestHttp_verify_table(flatcc_table_verifier_descriptor_t *td);
static int EVP_SDK_BlobRequestHttpExt_verify_table(flatcc_table_verifier_descriptor_t *td);
static int EVP_SDK_BlobInput_verify_table(flatcc_table_verifier_descriptor_t *td);
static int EVP_SDK_BlobResultAzureBlob_verify_table(flatcc_table_verifier_descriptor_t *td);
static int EVP_SDK_BlobResultEvp_verify_table(flatcc_table_verifier_descriptor_t *td);
static int EVP_SDK_BlobResultHttp_verify_table(flatcc_table_verifier_descriptor_t *td);
static int EVP_SDK_BlobResultHttpExt_verify_table(flatcc_table_verifier_descriptor_t *td);
static int EVP_SDK_BlobOutput_verify_table(flatcc_table_verifier_descriptor_t *td);
static int EVP_SDK_MessageSentInput_verify_table(flatcc_table_verifier_descriptor_t *td);
static int EVP_SDK_MessageSentOutput_verify_table(flatcc_table_verifier_descriptor_t *td);
static int EVP_SDK_MessageReceived_verify_table(flatcc_table_verifier_descriptor_t *td);
static int EVP_SDK_TelemetryEntry_verify_table(flatcc_table_verifier_descriptor_t *td);
static int EVP_SDK_TelemetryInput_verify_table(flatcc_table_verifier_descriptor_t *td);
static int EVP_SDK_TelemetryOutput_verify_table(flatcc_table_verifier_descriptor_t *td);
static int EVP_SDK_RpcRequest_verify_table(flatcc_table_verifier_descriptor_t *td);
static int EVP_SDK_RpcResponseInput_verify_table(flatcc_table_verifier_descriptor_t *td);
static int EVP_SDK_RpcResponseOutput_verify_table(flatcc_table_verifier_descriptor_t *td);
static int EVP_SDK_Event_verify_table(flatcc_table_verifier_descriptor_t *td);
static int EVP_SDK_GetEvent_verify_table(flatcc_table_verifier_descriptor_t *td);
static int EVP_SDK_RequestResendConfig_verify_table(flatcc_table_verifier_descriptor_t *td);
static int EVP_SDK_Request_verify_table(flatcc_table_verifier_descriptor_t *td);
static int EVP_SDK_Simple_verify_table(flatcc_table_verifier_descriptor_t *td);
static int EVP_SDK_Response_verify_table(flatcc_table_verifier_descriptor_t *td);
static int EVP_SDK_StreamParamsRequest_verify_table(flatcc_table_verifier_descriptor_t *td);
static int EVP_SDK_StreamNng_verify_table(flatcc_table_verifier_descriptor_t *td);
static int EVP_SDK_StreamParamsResponse_verify_table(flatcc_table_verifier_descriptor_t *td);

static int EVP_SDK_BlobRequestUnion_union_verifier(flatcc_union_verifier_descriptor_t *ud)
{
    switch (ud->type) {
    case 1: return flatcc_verify_union_table(ud, EVP_SDK_BlobRequestAzureBlob_verify_table); /* azureBlob */
    case 2: return flatcc_verify_union_table(ud, EVP_SDK_BlobRequestEvp_verify_table); /* evp */
    case 3: return flatcc_verify_union_table(ud, EVP_SDK_BlobRequestHttp_verify_table); /* http */
    case 4: return flatcc_verify_union_table(ud, EVP_SDK_BlobRequestHttpExt_verify_table); /* http_ext */
    default: return flatcc_verify_ok;
    }
}

static int EVP_SDK_BlobResultUnion_union_verifier(flatcc_union_verifier_descriptor_t *ud)
{
    switch (ud->type) {
    case 1: return flatcc_verify_union_table(ud, EVP_SDK_BlobResultAzureBlob_verify_table); /* azureBlob */
    case 2: return flatcc_verify_union_table(ud, EVP_SDK_BlobResultEvp_verify_table); /* evp */
    case 3: return flatcc_verify_union_table(ud, EVP_SDK_BlobResultHttp_verify_table); /* http */
    case 4: return flatcc_verify_union_table(ud, EVP_SDK_BlobResultHttpExt_verify_table); /* http_ext */
    default: return flatcc_verify_ok;
    }
}

static int EVP_SDK_EventBody_union_verifier(flatcc_union_verifier_descriptor_t *ud)
{
    switch (ud->type) {
    case 1: return flatcc_verify_union_table(ud, EVP_SDK_Config_verify_table); /* config */
    case 2: return flatcc_verify_union_table(ud, EVP_SDK_StateOutput_verify_table); /* state */
    case 3: return flatcc_verify_union_table(ud, EVP_SDK_Exit_verify_table); /* exit */
    case 4: return flatcc_verify_union_table(ud, EVP_SDK_BlobOutput_verify_table); /* blob */
    case 5: return flatcc_verify_union_table(ud, EVP_SDK_MessageSentOutput_verify_table); /* messageSent */
    case 6: return flatcc_verify_union_table(ud, EVP_SDK_MessageReceived_verify_table); /* messageReceived */
    case 7: return flatcc_verify_union_table(ud, EVP_SDK_TelemetryOutput_verify_table); /* telemetry */
    case 8: return flatcc_verify_union_table(ud, EVP_SDK_RpcRequest_verify_table); /* rpcRequest */
    case 9: return flatcc_verify_union_table(ud, EVP_SDK_RpcResponseOutput_verify_table); /* rpcResponse */
    default: return flatcc_verify_ok;
    }
}

static int EVP_SDK_RequestUnion_union_verifier(flatcc_union_verifier_descriptor_t *ud)
{
    switch (ud->type) {
    case 1: return flatcc_verify_union_table(ud, EVP_SDK_GetEvent_verify_table); /* getEvent */
    case 2: return flatcc_verify_union_table(ud, EVP_SDK_StateInput_verify_table); /* sendState */
    case 3: return flatcc_verify_union_table(ud, EVP_SDK_RequestResendConfig_verify_table); /* requestResendConfig */
    case 4: return flatcc_verify_union_table(ud, EVP_SDK_BlobInput_verify_table); /* blobOperation */
    case 5: return flatcc_verify_union_table(ud, EVP_SDK_TelemetryInput_verify_table); /* sendTelemetry */
    case 6: return flatcc_verify_union_table(ud, EVP_SDK_MessageSentInput_verify_table); /* sendMessage */
    case 7: return flatcc_verify_union_table(ud, EVP_SDK_RpcResponseInput_verify_table); /* sendRpcResponse */
    case 8: return flatcc_verify_union_table(ud, EVP_SDK_StreamParamsRequest_verify_table); /* streamParamsRequest */
    default: return flatcc_verify_ok;
    }
}

static int EVP_SDK_ResponseUnion_union_verifier(flatcc_union_verifier_descriptor_t *ud)
{
    switch (ud->type) {
    case 1: return flatcc_verify_union_table(ud, EVP_SDK_Event_verify_table); /* getEvent */
    case 2: return flatcc_verify_union_table(ud, EVP_SDK_Simple_verify_table); /* simple */
    case 3: return flatcc_verify_union_table(ud, EVP_SDK_StreamParamsResponse_verify_table); /* streamParamsResponse */
    default: return flatcc_verify_ok;
    }
}

static int EVP_SDK_StreamParams_union_verifier(flatcc_union_verifier_descriptor_t *ud)
{
    switch (ud->type) {
    case 1: return flatcc_verify_union_table(ud, EVP_SDK_StreamNng_verify_table); /* nng */
    default: return flatcc_verify_ok;
    }
}

static int EVP_SDK_Config_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_string_field(td, 0, 1) /* topic */)) return ret;
    if ((ret = flatcc_verify_vector_field(td, 1, 1, 1, 1, INT64_C(4294967295)) /* blob */)) return ret;
    return flatcc_verify_ok;
}

static inline int EVP_SDK_Config_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, EVP_SDK_Config_identifier, &EVP_SDK_Config_verify_table);
}

static inline int EVP_SDK_Config_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, EVP_SDK_Config_type_identifier, &EVP_SDK_Config_verify_table);
}

static inline int EVP_SDK_Config_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &EVP_SDK_Config_verify_table);
}

static inline int EVP_SDK_Config_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &EVP_SDK_Config_verify_table);
}

static int EVP_SDK_StateInput_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_string_field(td, 0, 1) /* topic */)) return ret;
    if ((ret = flatcc_verify_vector_field(td, 1, 1, 1, 1, INT64_C(4294967295)) /* blob */)) return ret;
    if ((ret = flatcc_verify_field(td, 2, 8, 8) /* cb */)) return ret;
    if ((ret = flatcc_verify_field(td, 3, 8, 8) /* cb_userdata */)) return ret;
    return flatcc_verify_ok;
}

static inline int EVP_SDK_StateInput_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, EVP_SDK_StateInput_identifier, &EVP_SDK_StateInput_verify_table);
}

static inline int EVP_SDK_StateInput_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, EVP_SDK_StateInput_type_identifier, &EVP_SDK_StateInput_verify_table);
}

static inline int EVP_SDK_StateInput_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &EVP_SDK_StateInput_verify_table);
}

static inline int EVP_SDK_StateInput_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &EVP_SDK_StateInput_verify_table);
}

static int EVP_SDK_StateOutput_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 8, 8) /* cb */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 4, 4) /* reason */)) return ret;
    if ((ret = flatcc_verify_field(td, 2, 8, 8) /* cb_userdata */)) return ret;
    return flatcc_verify_ok;
}

static inline int EVP_SDK_StateOutput_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, EVP_SDK_StateOutput_identifier, &EVP_SDK_StateOutput_verify_table);
}

static inline int EVP_SDK_StateOutput_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, EVP_SDK_StateOutput_type_identifier, &EVP_SDK_StateOutput_verify_table);
}

static inline int EVP_SDK_StateOutput_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &EVP_SDK_StateOutput_verify_table);
}

static inline int EVP_SDK_StateOutput_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &EVP_SDK_StateOutput_verify_table);
}

static int EVP_SDK_Exit_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    return flatcc_verify_ok;
}

static inline int EVP_SDK_Exit_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, EVP_SDK_Exit_identifier, &EVP_SDK_Exit_verify_table);
}

static inline int EVP_SDK_Exit_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, EVP_SDK_Exit_type_identifier, &EVP_SDK_Exit_verify_table);
}

static inline int EVP_SDK_Exit_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &EVP_SDK_Exit_verify_table);
}

static inline int EVP_SDK_Exit_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &EVP_SDK_Exit_verify_table);
}

static int EVP_SDK_BlobRequestAzureBlob_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_string_field(td, 0, 1) /* url */)) return ret;
    return flatcc_verify_ok;
}

static inline int EVP_SDK_BlobRequestAzureBlob_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, EVP_SDK_BlobRequestAzureBlob_identifier, &EVP_SDK_BlobRequestAzureBlob_verify_table);
}

static inline int EVP_SDK_BlobRequestAzureBlob_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, EVP_SDK_BlobRequestAzureBlob_type_identifier, &EVP_SDK_BlobRequestAzureBlob_verify_table);
}

static inline int EVP_SDK_BlobRequestAzureBlob_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &EVP_SDK_BlobRequestAzureBlob_verify_table);
}

static inline int EVP_SDK_BlobRequestAzureBlob_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &EVP_SDK_BlobRequestAzureBlob_verify_table);
}

static int EVP_SDK_BlobRequestEvp_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_string_field(td, 0, 1) /* remoteName */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 1, 0) /* storageName */)) return ret;
    return flatcc_verify_ok;
}

static inline int EVP_SDK_BlobRequestEvp_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, EVP_SDK_BlobRequestEvp_identifier, &EVP_SDK_BlobRequestEvp_verify_table);
}

static inline int EVP_SDK_BlobRequestEvp_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, EVP_SDK_BlobRequestEvp_type_identifier, &EVP_SDK_BlobRequestEvp_verify_table);
}

static inline int EVP_SDK_BlobRequestEvp_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &EVP_SDK_BlobRequestEvp_verify_table);
}

static inline int EVP_SDK_BlobRequestEvp_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &EVP_SDK_BlobRequestEvp_verify_table);
}

static int EVP_SDK_BlobRequestHttp_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_string_field(td, 0, 1) /* url */)) return ret;
    return flatcc_verify_ok;
}

static inline int EVP_SDK_BlobRequestHttp_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, EVP_SDK_BlobRequestHttp_identifier, &EVP_SDK_BlobRequestHttp_verify_table);
}

static inline int EVP_SDK_BlobRequestHttp_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, EVP_SDK_BlobRequestHttp_type_identifier, &EVP_SDK_BlobRequestHttp_verify_table);
}

static inline int EVP_SDK_BlobRequestHttp_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &EVP_SDK_BlobRequestHttp_verify_table);
}

static inline int EVP_SDK_BlobRequestHttp_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &EVP_SDK_BlobRequestHttp_verify_table);
}

static int EVP_SDK_BlobRequestHttpExt_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_string_field(td, 0, 1) /* url */)) return ret;
    if ((ret = flatcc_verify_string_vector_field(td, 1, 1) /* headers */)) return ret;
    return flatcc_verify_ok;
}

static inline int EVP_SDK_BlobRequestHttpExt_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, EVP_SDK_BlobRequestHttpExt_identifier, &EVP_SDK_BlobRequestHttpExt_verify_table);
}

static inline int EVP_SDK_BlobRequestHttpExt_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, EVP_SDK_BlobRequestHttpExt_type_identifier, &EVP_SDK_BlobRequestHttpExt_verify_table);
}

static inline int EVP_SDK_BlobRequestHttpExt_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &EVP_SDK_BlobRequestHttpExt_verify_table);
}

static inline int EVP_SDK_BlobRequestHttpExt_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &EVP_SDK_BlobRequestHttpExt_verify_table);
}

static int EVP_SDK_BlobInput_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 4, 4) /* type */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 4, 4) /* op */)) return ret;
    if ((ret = flatcc_verify_union_field(td, 3, 1, &EVP_SDK_BlobRequestUnion_union_verifier) /* request */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 4, 1) /* filename */)) return ret;
    if ((ret = flatcc_verify_field(td, 5, 8, 8) /* cb */)) return ret;
    if ((ret = flatcc_verify_field(td, 6, 8, 8) /* cb_userdata */)) return ret;
    return flatcc_verify_ok;
}

static inline int EVP_SDK_BlobInput_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, EVP_SDK_BlobInput_identifier, &EVP_SDK_BlobInput_verify_table);
}

static inline int EVP_SDK_BlobInput_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, EVP_SDK_BlobInput_type_identifier, &EVP_SDK_BlobInput_verify_table);
}

static inline int EVP_SDK_BlobInput_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &EVP_SDK_BlobInput_verify_table);
}

static inline int EVP_SDK_BlobInput_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &EVP_SDK_BlobInput_verify_table);
}

static int EVP_SDK_BlobResultAzureBlob_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 4, 4) /* result */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 4, 4) /* error */)) return ret;
    if ((ret = flatcc_verify_field(td, 2, 4, 4) /* http_status */)) return ret;
    return flatcc_verify_ok;
}

static inline int EVP_SDK_BlobResultAzureBlob_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, EVP_SDK_BlobResultAzureBlob_identifier, &EVP_SDK_BlobResultAzureBlob_verify_table);
}

static inline int EVP_SDK_BlobResultAzureBlob_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, EVP_SDK_BlobResultAzureBlob_type_identifier, &EVP_SDK_BlobResultAzureBlob_verify_table);
}

static inline int EVP_SDK_BlobResultAzureBlob_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &EVP_SDK_BlobResultAzureBlob_verify_table);
}

static inline int EVP_SDK_BlobResultAzureBlob_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &EVP_SDK_BlobResultAzureBlob_verify_table);
}

static int EVP_SDK_BlobResultEvp_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 4, 4) /* result */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 4, 4) /* error */)) return ret;
    if ((ret = flatcc_verify_field(td, 2, 4, 4) /* http_status */)) return ret;
    return flatcc_verify_ok;
}

static inline int EVP_SDK_BlobResultEvp_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, EVP_SDK_BlobResultEvp_identifier, &EVP_SDK_BlobResultEvp_verify_table);
}

static inline int EVP_SDK_BlobResultEvp_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, EVP_SDK_BlobResultEvp_type_identifier, &EVP_SDK_BlobResultEvp_verify_table);
}

static inline int EVP_SDK_BlobResultEvp_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &EVP_SDK_BlobResultEvp_verify_table);
}

static inline int EVP_SDK_BlobResultEvp_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &EVP_SDK_BlobResultEvp_verify_table);
}

static int EVP_SDK_BlobResultHttp_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 4, 4) /* result */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 4, 4) /* error */)) return ret;
    if ((ret = flatcc_verify_field(td, 2, 4, 4) /* http_status */)) return ret;
    return flatcc_verify_ok;
}

static inline int EVP_SDK_BlobResultHttp_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, EVP_SDK_BlobResultHttp_identifier, &EVP_SDK_BlobResultHttp_verify_table);
}

static inline int EVP_SDK_BlobResultHttp_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, EVP_SDK_BlobResultHttp_type_identifier, &EVP_SDK_BlobResultHttp_verify_table);
}

static inline int EVP_SDK_BlobResultHttp_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &EVP_SDK_BlobResultHttp_verify_table);
}

static inline int EVP_SDK_BlobResultHttp_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &EVP_SDK_BlobResultHttp_verify_table);
}

static int EVP_SDK_BlobResultHttpExt_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 4, 4) /* result */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 4, 4) /* error */)) return ret;
    if ((ret = flatcc_verify_field(td, 2, 4, 4) /* http_status */)) return ret;
    return flatcc_verify_ok;
}

static inline int EVP_SDK_BlobResultHttpExt_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, EVP_SDK_BlobResultHttpExt_identifier, &EVP_SDK_BlobResultHttpExt_verify_table);
}

static inline int EVP_SDK_BlobResultHttpExt_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, EVP_SDK_BlobResultHttpExt_type_identifier, &EVP_SDK_BlobResultHttpExt_verify_table);
}

static inline int EVP_SDK_BlobResultHttpExt_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &EVP_SDK_BlobResultHttpExt_verify_table);
}

static inline int EVP_SDK_BlobResultHttpExt_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &EVP_SDK_BlobResultHttpExt_verify_table);
}

static int EVP_SDK_BlobOutput_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_union_field(td, 1, 0, &EVP_SDK_BlobResultUnion_union_verifier) /* result */)) return ret;
    if ((ret = flatcc_verify_field(td, 2, 8, 8) /* cb */)) return ret;
    if ((ret = flatcc_verify_field(td, 3, 4, 4) /* reason */)) return ret;
    if ((ret = flatcc_verify_field(td, 4, 8, 8) /* cb_userdata */)) return ret;
    return flatcc_verify_ok;
}

static inline int EVP_SDK_BlobOutput_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, EVP_SDK_BlobOutput_identifier, &EVP_SDK_BlobOutput_verify_table);
}

static inline int EVP_SDK_BlobOutput_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, EVP_SDK_BlobOutput_type_identifier, &EVP_SDK_BlobOutput_verify_table);
}

static inline int EVP_SDK_BlobOutput_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &EVP_SDK_BlobOutput_verify_table);
}

static inline int EVP_SDK_BlobOutput_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &EVP_SDK_BlobOutput_verify_table);
}

static int EVP_SDK_MessageSentInput_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_string_field(td, 0, 1) /* topic */)) return ret;
    if ((ret = flatcc_verify_vector_field(td, 1, 1, 1, 1, INT64_C(4294967295)) /* blob */)) return ret;
    if ((ret = flatcc_verify_field(td, 2, 8, 8) /* cb */)) return ret;
    if ((ret = flatcc_verify_field(td, 3, 8, 8) /* cb_userdata */)) return ret;
    return flatcc_verify_ok;
}

static inline int EVP_SDK_MessageSentInput_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, EVP_SDK_MessageSentInput_identifier, &EVP_SDK_MessageSentInput_verify_table);
}

static inline int EVP_SDK_MessageSentInput_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, EVP_SDK_MessageSentInput_type_identifier, &EVP_SDK_MessageSentInput_verify_table);
}

static inline int EVP_SDK_MessageSentInput_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &EVP_SDK_MessageSentInput_verify_table);
}

static inline int EVP_SDK_MessageSentInput_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &EVP_SDK_MessageSentInput_verify_table);
}

static int EVP_SDK_MessageSentOutput_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 8, 8) /* cb */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 4, 4) /* reason */)) return ret;
    if ((ret = flatcc_verify_field(td, 2, 8, 8) /* cb_userdata */)) return ret;
    return flatcc_verify_ok;
}

static inline int EVP_SDK_MessageSentOutput_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, EVP_SDK_MessageSentOutput_identifier, &EVP_SDK_MessageSentOutput_verify_table);
}

static inline int EVP_SDK_MessageSentOutput_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, EVP_SDK_MessageSentOutput_type_identifier, &EVP_SDK_MessageSentOutput_verify_table);
}

static inline int EVP_SDK_MessageSentOutput_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &EVP_SDK_MessageSentOutput_verify_table);
}

static inline int EVP_SDK_MessageSentOutput_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &EVP_SDK_MessageSentOutput_verify_table);
}

static int EVP_SDK_MessageReceived_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_string_field(td, 0, 1) /* topic */)) return ret;
    if ((ret = flatcc_verify_vector_field(td, 1, 1, 1, 1, INT64_C(4294967295)) /* blob */)) return ret;
    return flatcc_verify_ok;
}

static inline int EVP_SDK_MessageReceived_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, EVP_SDK_MessageReceived_identifier, &EVP_SDK_MessageReceived_verify_table);
}

static inline int EVP_SDK_MessageReceived_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, EVP_SDK_MessageReceived_type_identifier, &EVP_SDK_MessageReceived_verify_table);
}

static inline int EVP_SDK_MessageReceived_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &EVP_SDK_MessageReceived_verify_table);
}

static inline int EVP_SDK_MessageReceived_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &EVP_SDK_MessageReceived_verify_table);
}

static int EVP_SDK_TelemetryEntry_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_string_field(td, 0, 1) /* key */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 1, 1) /* value */)) return ret;
    return flatcc_verify_ok;
}

static inline int EVP_SDK_TelemetryEntry_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, EVP_SDK_TelemetryEntry_identifier, &EVP_SDK_TelemetryEntry_verify_table);
}

static inline int EVP_SDK_TelemetryEntry_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, EVP_SDK_TelemetryEntry_type_identifier, &EVP_SDK_TelemetryEntry_verify_table);
}

static inline int EVP_SDK_TelemetryEntry_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &EVP_SDK_TelemetryEntry_verify_table);
}

static inline int EVP_SDK_TelemetryEntry_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &EVP_SDK_TelemetryEntry_verify_table);
}

static int EVP_SDK_TelemetryInput_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_table_vector_field(td, 0, 0, &EVP_SDK_TelemetryEntry_verify_table) /* entries */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 8, 8) /* cb */)) return ret;
    if ((ret = flatcc_verify_field(td, 2, 8, 8) /* cb_userdata */)) return ret;
    return flatcc_verify_ok;
}

static inline int EVP_SDK_TelemetryInput_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, EVP_SDK_TelemetryInput_identifier, &EVP_SDK_TelemetryInput_verify_table);
}

static inline int EVP_SDK_TelemetryInput_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, EVP_SDK_TelemetryInput_type_identifier, &EVP_SDK_TelemetryInput_verify_table);
}

static inline int EVP_SDK_TelemetryInput_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &EVP_SDK_TelemetryInput_verify_table);
}

static inline int EVP_SDK_TelemetryInput_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &EVP_SDK_TelemetryInput_verify_table);
}

static int EVP_SDK_TelemetryOutput_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 8, 8) /* cb */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 4, 4) /* reason */)) return ret;
    if ((ret = flatcc_verify_field(td, 2, 8, 8) /* cb_userdata */)) return ret;
    return flatcc_verify_ok;
}

static inline int EVP_SDK_TelemetryOutput_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, EVP_SDK_TelemetryOutput_identifier, &EVP_SDK_TelemetryOutput_verify_table);
}

static inline int EVP_SDK_TelemetryOutput_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, EVP_SDK_TelemetryOutput_type_identifier, &EVP_SDK_TelemetryOutput_verify_table);
}

static inline int EVP_SDK_TelemetryOutput_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &EVP_SDK_TelemetryOutput_verify_table);
}

static inline int EVP_SDK_TelemetryOutput_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &EVP_SDK_TelemetryOutput_verify_table);
}

static int EVP_SDK_RpcRequest_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 8, 8) /* id */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 1, 1) /* method */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 2, 1) /* params */)) return ret;
    return flatcc_verify_ok;
}

static inline int EVP_SDK_RpcRequest_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, EVP_SDK_RpcRequest_identifier, &EVP_SDK_RpcRequest_verify_table);
}

static inline int EVP_SDK_RpcRequest_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, EVP_SDK_RpcRequest_type_identifier, &EVP_SDK_RpcRequest_verify_table);
}

static inline int EVP_SDK_RpcRequest_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &EVP_SDK_RpcRequest_verify_table);
}

static inline int EVP_SDK_RpcRequest_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &EVP_SDK_RpcRequest_verify_table);
}

static int EVP_SDK_RpcResponseInput_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 8, 8) /* id */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 1, 0) /* response */)) return ret;
    if ((ret = flatcc_verify_field(td, 2, 4, 4) /* status */)) return ret;
    if ((ret = flatcc_verify_field(td, 3, 8, 8) /* cb */)) return ret;
    if ((ret = flatcc_verify_field(td, 4, 8, 8) /* cb_userdata */)) return ret;
    return flatcc_verify_ok;
}

static inline int EVP_SDK_RpcResponseInput_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, EVP_SDK_RpcResponseInput_identifier, &EVP_SDK_RpcResponseInput_verify_table);
}

static inline int EVP_SDK_RpcResponseInput_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, EVP_SDK_RpcResponseInput_type_identifier, &EVP_SDK_RpcResponseInput_verify_table);
}

static inline int EVP_SDK_RpcResponseInput_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &EVP_SDK_RpcResponseInput_verify_table);
}

static inline int EVP_SDK_RpcResponseInput_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &EVP_SDK_RpcResponseInput_verify_table);
}

static int EVP_SDK_RpcResponseOutput_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 8, 8) /* cb */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 4, 4) /* reason */)) return ret;
    if ((ret = flatcc_verify_field(td, 2, 8, 8) /* cb_userdata */)) return ret;
    return flatcc_verify_ok;
}

static inline int EVP_SDK_RpcResponseOutput_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, EVP_SDK_RpcResponseOutput_identifier, &EVP_SDK_RpcResponseOutput_verify_table);
}

static inline int EVP_SDK_RpcResponseOutput_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, EVP_SDK_RpcResponseOutput_type_identifier, &EVP_SDK_RpcResponseOutput_verify_table);
}

static inline int EVP_SDK_RpcResponseOutput_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &EVP_SDK_RpcResponseOutput_verify_table);
}

static inline int EVP_SDK_RpcResponseOutput_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &EVP_SDK_RpcResponseOutput_verify_table);
}

static int EVP_SDK_Event_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_union_field(td, 1, 0, &EVP_SDK_EventBody_union_verifier) /* body */)) return ret;
    return flatcc_verify_ok;
}

static inline int EVP_SDK_Event_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, EVP_SDK_Event_identifier, &EVP_SDK_Event_verify_table);
}

static inline int EVP_SDK_Event_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, EVP_SDK_Event_type_identifier, &EVP_SDK_Event_verify_table);
}

static inline int EVP_SDK_Event_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &EVP_SDK_Event_verify_table);
}

static inline int EVP_SDK_Event_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &EVP_SDK_Event_verify_table);
}

static int EVP_SDK_GetEvent_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 8, 8) /* timeout_sec */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 8, 8) /* timeout_nsec */)) return ret;
    return flatcc_verify_ok;
}

static inline int EVP_SDK_GetEvent_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, EVP_SDK_GetEvent_identifier, &EVP_SDK_GetEvent_verify_table);
}

static inline int EVP_SDK_GetEvent_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, EVP_SDK_GetEvent_type_identifier, &EVP_SDK_GetEvent_verify_table);
}

static inline int EVP_SDK_GetEvent_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &EVP_SDK_GetEvent_verify_table);
}

static inline int EVP_SDK_GetEvent_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &EVP_SDK_GetEvent_verify_table);
}

static int EVP_SDK_RequestResendConfig_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    return flatcc_verify_ok;
}

static inline int EVP_SDK_RequestResendConfig_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, EVP_SDK_RequestResendConfig_identifier, &EVP_SDK_RequestResendConfig_verify_table);
}

static inline int EVP_SDK_RequestResendConfig_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, EVP_SDK_RequestResendConfig_type_identifier, &EVP_SDK_RequestResendConfig_verify_table);
}

static inline int EVP_SDK_RequestResendConfig_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &EVP_SDK_RequestResendConfig_verify_table);
}

static inline int EVP_SDK_RequestResendConfig_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &EVP_SDK_RequestResendConfig_verify_table);
}

static int EVP_SDK_Request_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_union_field(td, 1, 1, &EVP_SDK_RequestUnion_union_verifier) /* body */)) return ret;
    return flatcc_verify_ok;
}

static inline int EVP_SDK_Request_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, EVP_SDK_Request_identifier, &EVP_SDK_Request_verify_table);
}

static inline int EVP_SDK_Request_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, EVP_SDK_Request_type_identifier, &EVP_SDK_Request_verify_table);
}

static inline int EVP_SDK_Request_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &EVP_SDK_Request_verify_table);
}

static inline int EVP_SDK_Request_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &EVP_SDK_Request_verify_table);
}

static int EVP_SDK_Simple_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 4, 4) /* result */)) return ret;
    return flatcc_verify_ok;
}

static inline int EVP_SDK_Simple_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, EVP_SDK_Simple_identifier, &EVP_SDK_Simple_verify_table);
}

static inline int EVP_SDK_Simple_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, EVP_SDK_Simple_type_identifier, &EVP_SDK_Simple_verify_table);
}

static inline int EVP_SDK_Simple_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &EVP_SDK_Simple_verify_table);
}

static inline int EVP_SDK_Simple_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &EVP_SDK_Simple_verify_table);
}

static int EVP_SDK_Response_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_union_field(td, 1, 1, &EVP_SDK_ResponseUnion_union_verifier) /* body */)) return ret;
    return flatcc_verify_ok;
}

static inline int EVP_SDK_Response_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, EVP_SDK_Response_identifier, &EVP_SDK_Response_verify_table);
}

static inline int EVP_SDK_Response_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, EVP_SDK_Response_type_identifier, &EVP_SDK_Response_verify_table);
}

static inline int EVP_SDK_Response_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &EVP_SDK_Response_verify_table);
}

static inline int EVP_SDK_Response_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &EVP_SDK_Response_verify_table);
}

static int EVP_SDK_StreamParamsRequest_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_string_field(td, 0, 0) /* name */)) return ret;
    return flatcc_verify_ok;
}

static inline int EVP_SDK_StreamParamsRequest_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, EVP_SDK_StreamParamsRequest_identifier, &EVP_SDK_StreamParamsRequest_verify_table);
}

static inline int EVP_SDK_StreamParamsRequest_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, EVP_SDK_StreamParamsRequest_type_identifier, &EVP_SDK_StreamParamsRequest_verify_table);
}

static inline int EVP_SDK_StreamParamsRequest_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &EVP_SDK_StreamParamsRequest_verify_table);
}

static inline int EVP_SDK_StreamParamsRequest_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &EVP_SDK_StreamParamsRequest_verify_table);
}

static int EVP_SDK_StreamNng_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 1, 1) /* mode */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 1, 1) /* protocol */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 2, 0) /* connection */)) return ret;
    return flatcc_verify_ok;
}

static inline int EVP_SDK_StreamNng_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, EVP_SDK_StreamNng_identifier, &EVP_SDK_StreamNng_verify_table);
}

static inline int EVP_SDK_StreamNng_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, EVP_SDK_StreamNng_type_identifier, &EVP_SDK_StreamNng_verify_table);
}

static inline int EVP_SDK_StreamNng_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &EVP_SDK_StreamNng_verify_table);
}

static inline int EVP_SDK_StreamNng_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &EVP_SDK_StreamNng_verify_table);
}

static int EVP_SDK_StreamParamsResponse_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 4, 4) /* result */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 1, 1) /* type */)) return ret;
    if ((ret = flatcc_verify_field(td, 2, 1, 1) /* direction */)) return ret;
    if ((ret = flatcc_verify_union_field(td, 4, 0, &EVP_SDK_StreamParams_union_verifier) /* params */)) return ret;
    return flatcc_verify_ok;
}

static inline int EVP_SDK_StreamParamsResponse_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, EVP_SDK_StreamParamsResponse_identifier, &EVP_SDK_StreamParamsResponse_verify_table);
}

static inline int EVP_SDK_StreamParamsResponse_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, EVP_SDK_StreamParamsResponse_type_identifier, &EVP_SDK_StreamParamsResponse_verify_table);
}

static inline int EVP_SDK_StreamParamsResponse_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &EVP_SDK_StreamParamsResponse_verify_table);
}

static inline int EVP_SDK_StreamParamsResponse_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &EVP_SDK_StreamParamsResponse_verify_table);
}

#include "flatcc/flatcc_epilogue.h"
#endif /* SDK_VERIFIER_H */
